---
title: '2장 9절: 커넥톰과 기능적 연결성'
description: Connectome and Functional Connectivity
bibliography: references/02-09.bib
link-citation: yes
---

<a href="article-02-08.html"><i class="arrow far fa-arrow-alt-circle-left"></i></a>

<a href="article-02-10.html"><i class="arrow far fa-arrow-alt-circle-right"></i></a>

## 9-1. 커넥톰

뇌 기능은 신경세포에서 비롯되지 않는다. 또한 하나의 뇌 구조물이 단일한 기능을 발휘하는 것도 아니다. 신경계의 기능이 발현되는 곳은 뉴런과 뉴런의 연결패턴이요 그들이 이루는 신경연결망(neural network)이다. 해부학적 구조물 또한 다른 구조물과의 연결을 통해 합목적적 기능을 창출해낸다. "전체는 부분의 합보다 크다.(The whole is greater than the sum of its part)"라는 경구는 <s>일반시스템 이론</s>이나 <s>복잡계 이론</s>을 확립한 현대의 선구적인 학자들이 아니라, 무려 2,500년전에 활약한 아리스토텔레스였다.

<aside>

**일반시스템 이론(general system theory)**: 시스템이란 상호의존적이고 상호 작용하는 부분들로 구성된 전체, 즉 구성 요소들과 그들의 상호 작용의 합으로 정의된다. 오스트리아의 생물학자인 Ludwig von Bertalanffy에 의해 창안되었다. 이전까지 과학은 개개 부분을 전체에서 고립시킨 후 그 성질을 분석하는 환원주의 원칙에 따라 진행되어왔다. 이에 반해, Bertalanffy는 시스템을 이해하기 위해 더욱 중요한 것은 개개 부분들이 다른 요소들과 맺는 관계라고 지적하였다. 초기에는 인간사회나 기업조직을 이해하고자 하는 데 응용되었으나, 점차 생물학 및 물리 시스템의 이해에도 적용되면서 범위를 넓혀오고 있다.

**복잡계 이론(complexity theory)**: 시스템을 이루는 다양한 구성 요소들이 서로 비선형적으로 관계맺고 있는 경우, 그들 전체에서 비롯되는 거시적인 성질은 완전한 질서도 무질서도 아닌 카오스적인 양상을 보인다. 시스템 구성요소에서는 발견할 수 없는 성질이 그들이 구성하는 시스템에서 나타나는 소위 창발현상을 연구하는 이론을 복잡계 이론이라 한다.

</aside>

뉴런과 뉴런의 연결 역시 <s>서로 다른 층위</s>에서 바라볼 수 있다. 특정한 대뇌 피질층(cortical layer)([2장 7-5절 참조](article-02-07.html#hypofrontality))에 위치한 피라미드 뉴런과 사이뉴런의 국소적 연결회로를 비롯하여, 동일한 <s>피질 기둥</s>에 속하지만 서로 다른 피질층 간의 원격 연결, 서로 다른 피질 기둥 간의 연결 등을 고려해 볼 수 있다. 이보다 좀더 거시적으로 보면, 하나의 해부학적 구조와 다른 구조 사이의 연결이 있다. 뇌는 이러한 규모가 큰 연결을 하나로 묶어 신경 경로(neural pathway)를 구성한다. 이들은 해부학적으로 bundle, fasciculus, tract, commissure 등의 용어로 불리운다.

<aside>

시스템은 거의 예외없이 계층적 구조를 이루고 있다. 하위 단계의 구성 요소들이 모여 새로운 성질을 발현하면, 그렇게 창발된 현상들이 모여 보다 상위의 구조를 만들고 또 다른 성질을 창발시킨다. 따라서 전체 시스템을 분석하기 위해선 어느 하나의 층위만을 이해해선 부족하며, 상위단계와 하위단계가 맺는 관계까지도 이해해야 한다.

**피질 기둥(cortical column)**: 6개의 층으로 구성된 대뇌 피질은 기둥 구조로 조직화되어 있다. 피질 표면의 조그마한 영역과 여기에 수직인 내측 피질은 서로 활발한 시냅스를 이루고 있으며, 하나의 연산단위를 이룬다.여기서 연산된 신호는 layer III에서 뻗어나가는 축삭돌기를 통해 다른 피질 기둥으로 보내진다.

</aside>

커넥톰(Connectome)이란 이렇게 거시적인 층위에서 신경 세포들의 연결을 종합적으로 표현한 것으로 일종의 뇌 회로도(blueprint)라고 생각할 수 있다. 좀 더 넓은 의미로는 단순히 뇌 내 신경세포 뿐만이 아니라 전신에 분포되어있는 신경세포들 간의 연결망을 가리킨다. 2009년 시작된 인간 커넥톰 프로젝트(Human Connectome Project)는 게놈 프로젝트 이후 최대의 과학 혁명으로 불린다. 이 연구를 통해 1000억 개 신경 세포의 연결구조와 활동원리를 파악해서 인간의 기억, 의식, 성격 등의 비밀을 밝히려고 한다. 이를 통하여 치매, 우울증, 자폐증, 조현병 등의 발병 기전과 치료법을 찾는데 기여할 정보를 얻는다는 목표를 갖고 있다.

인간 커넥톰은 한국 혈통의 미국인 과학자인 <s>승현준</s>에 의해서 더욱 우리에게 친숙하다. 원래 컴퓨터 공학자이던 그는 인간 커넥톰 프로젝트의 출범 이후 그 가능성을 높이 평가하여, [저서](https://en.wikipedia.org/wiki/Connectome_(book)) 와 [공개 강연](https://www.ted.com/talks/sebastian_seung_i_am_my_connectome?language=en)을 통해 이 접근법의 무궁무진한 잠재력을 역설하였다.

<aside>

**Sebastian Seung (1966\~)**: 한국계 미국 컴퓨터 공학자. 40세에 신경생물학으로 전공을 바꾼 후 뇌 영상을 통해 커넥톰을 측정하는 컴퓨터 프로그램을 만들기 시작한다. 2010년 TED 강연에 출연하여 "나는 내 커넥톰이다(I am my connectome)"이라는 강연을 하였고, 2012년 "Connectome: How the Brain's Wiring Makes Us Who We Are"이라는 저서를 써서, 커넥톰을 대중에게 알리는데 큰 역할을 하였다. 2018년부터는 삼성전자에서 인공지능 개발팀을 이끌고 있다.

</aside>

커넥톰을 그리는 것은 확산강조 MRI (diffusion-weighted MRI)를 촬영하는 것으로 시작한다. 아무런 방해물이 없을 때 물 분자는 방사선으로 확산되며 이는 구형(sphere)으로 모델링 할 수 있다. 이렇게 모든 방향으로 균일하게 확산되는 상태를 "등방성(isotropic)"이라고 한다. 만약 미엘린 수초에 의해 신경 경로가 외부로부터 절연되어 있으면, 물 분자는 어느 한방향으로 확산되는데 이러한 상태를 "비등방성(anisotropic)"이라고 한다. 확산이 비등방성으로 일어나면 구형이 아니라 타원체(ellipsoid)를 이용하여 모델링하게 되는데, 이러한 방식으로 얻는 이미지를 뇌 확산텐서영상(diffusion tensor imaging, DTI)이라고 한다. 이렇게 얻어진 영상에 특별한 컴퓨터 알고리즘을 적용하면, 신경 경로를 추적함은 물론 3차원 그래픽으로 표시할 수 있는데, 이를 신경섬유경로영상(fiber tractography)이라고 한다. 미국 국립보건원(NIH)에서 후원하고 있는 인간 커넥톰 프로젝트를 통해 얻어진 원자료는 [웹사이트](https://db.humanconnectome.org/app/template/Login.vm)를 통해 내려받을 수 있으며, 이는 다양한 연구에 활용되고 있다.

![Human connectome revealed by diffusion tensor imaging\
from <http://www.humanconnectomeproject.org/gallery/>](images/02-09/img_0.png){#fig:dti}

## 9-2. 기능적 연결성

DTI를 통해서 얻어낸 자료는 해부학적 커넥톰에 해당한다. 그러나 해부학적으로 밝혀진 경로가 반드시 기능적으로도 의미가 있는 경로인지는 확신할 수 없다. 기능적 연결성(functional connectivity)이란 서로 떨어진 뇌 부위가 기능적으로도 서로 연결되어 있는지를 알아내는 방법이다. 이는 기능적 MRI(functional MRI)를 이용하여 안정상태 혹은 과업수행 상태에서 뇌의 각 부위에서 발생하는 동시다발적 신호의 연결성을 분석하여 얻어낸다. 이 작업에는 고도로 복잡한 컴퓨터 알고리즘이 적용되며, 현재까지도 어떤 것이 가장 정확하고 효율적인 알고리즘인지는 결정되지 않았다. 기능적 연결성을 통해 기능적 커넥톰을 제쟉할 수 있다. 기능적 커넥톰은 해부학적 커넥톰의 부분집합이라는 견해, 즉 해부학적 연결이 있어야, 기능적 연결도 있을 수 있다는 견해도 있지만, 반드시 그렇지만은 않다는 이론도 있다.[@Tewarie2020-vv] 뇌의 신비를 벗겨내기 위해 좀더 중요한 것은 기능적 커넥톰이겠지만, 이를 매핑하는 과정은 해부학적 커넥텀의 경우보다도 훨씬 더 어려운 과업이다.[@Lang2012-gs]

## 9-3. 커넥톰 핑거프린트 {#connectome-fingerprint}

커넥톰은 독특한 연결 패턴을 알 수 있도록 해준다. 이러한 패턴을 일종의 지문(fingerprint)과 같다고 빗대기도 하는데, 여기서 "커넥톰 핑거프린트(connectome fingerprint)"라는 표현이 등장하였다. 커넥톰 패턴은 개인마다 독특한 양상을 보이고 있으며, 시간이 지나도 그리 변하지 않는다. 따라서 커넥톰 패턴을 갖고 특정 개인의 신원을 확인할 수 있으며, 특히 이 패턴은 그 사람의 인지기능과도 상관이 있다고 한다.[@Finn2015-jj][@Munsell2020-nt]

당연한 이야기이겠지만 개인마다 커넥톰 핑거프린트가 다르다면, 이를 그룹과 그룹 간에도 비교할 수 있다는 뜻이 된다. 환자와 대조군, 각양 각색의 진단군의 핑거프린트를 비교하면, 개인이 아니라 진단특이적인 핑거프린트를 얻어낼 수 있을런지도 모른다.[@Wang2020-tu] 다만 이러한 연구의 어려운 점은, 커넥톰 핑거프린트와 대응하는 표현형이 대체 어떤 것일지 미리 알 수 없다는 점이다. 주지하다시피, 정신과 진단이란 생물학적 병태생리와 일대일로 대응하지 않는다. 진단의 경계는 너무나 느슨하고, 진단을 범주적(categorical diagnosis)으로 내려야할 지 차원적(dimensional diagnosis)으로 내려야할 지도 의견이 모이지 않았다. 만약 정신병적 증상에 해당하는 핑거프린트가 있다면 이는 조현병, 양극성 장애, 정신병적 우울증을 막론하고 나타날 것이다. 인지기능과 관련된 핑거프린트가 있다고 해도, 치매와 조현병을 구분하기 어려울 지 모른다.[@Baker2019-gz]

커넥톰 연구를 통해 세가지 광역 네트워크의 구조가 제시되었다. 첫번째, **"전두-두정엽 조절 네트워크(frontoparietal control network, FPCN)"**는 전전두엽과, 하두정소엽(inferior parietal lobule), 대상회의 중앙부위(middle cingulate gyrus)을 중심으로 연결되며, 과거 전전두엽이 맡고 있다고 여겨진 작업 기억과 집행 기능을 행사한다. 둘째, **"현저성 네트워크(salience network)"**는 전측 섬엽(anterior insula)과 전측 대상회(anterior cingulate gyrus)로 구성되며, 의사소통, 사회적 행위, 자기 의식 등과 관련된 복잡한 기능을 맡는다. 혹자는 이를 "대상-판개 네트워크(cingulo-opercular network, CON)"라고 부르기도 한다. 마지막으로는 **"디폴트 모드 네트워크(default mode network, DMN)"**가 있다. 이는 내측 전전두엽(medial prefrontal cortex), 후측 대상회(posterior cingulate gyrus) 그리고 각회(angular gyrus)로 이루어진다. DMN은 아무런 과업도 수행하지 않고 절대적 안정 상태에 있는 뇌에서 활성화되는 부분인데, 자아감이나 과거 회상, 미래에 대한 예측, 마음 이론, 도덕 판단 등 인간 고유의 고위 기능을 행사할 때 사용된다고 여겨진다.[@Andrews-Hanna2012-lz]

![Figure 2. Global connectome network in the human brain\
from [@Chabran2020-me]](images/02-09/img_1.png){#fig:global-network}

이런 식으로 커넥톰에서 다루어지는 네트워크는 국소적 미세 연결부터 광역 네트워크까지 다양한 층위로 존재하며[@Mars2018-fz], 이에 대응하는 표현형 역시 다양한 층위로 고려될 수 있다. 광역 네트워크 이상에 해당되는 표현형은 지엽적인 진단명을 넘어서는 좀더 높은 층위에 해당할 것이다. 이러한 층위의 결정이 커넥톰 연구의 걸림돌로 남아있다.

## 9-4. 조현병의 커넥톰 이상

이러한 어려움에도 불구하고, 최근에는 정신과 진단에 따라 세가지 광역 네트워크에 어떤 변화가 있는 지를 알아내려는 연구가 활발히 진행되고 있다. Baker 등​[@Baker2019-gz]**​**은 조현병 및 기분 장애에서 모두 FPCN의 연결성이 떨어지는 것이 발견되었으나, DMN의 연결성 저하는 조현병 그리고 정신병적 증상이 동반된 기분 장애 환자에서만 발견되었다고 하였다. 그러나 동시에 FPCN의 연결성 저하가 PANSS로 측정한 양성 증상과 비례 관계에 있었기 때문에, FPCN 역시 정신병적 증상 발현에 기여하는 것 같다고 하였다. 또 다른 연구자들은 조현병의 다유전자 위험 점수(PRS, [2장 1-6절 참조](article-02-01.html#influence-genetic-research))가 FPCN과 DMN의 전반적 연결성과 역비례 관계에 있다고 하였다.[@Cao2020-mn]

유사한 연구에서 반복적으로 발견되는 조현병과 FPCN의 이상은, 조현병의 증상이 인지적 조절(cognitive control)이라는 집행 기능의 결함으로 비롯될 수 있음을 시사한다. 인지적 조절이란 의식적으로 인지적 자원을 당면한 과제 해결에 집중시키는 능력을 의미한다.[@Marek2018-gp] FPCN은 그 안에 포함된 구조들간의 왕성한 연결 말고도, 다른 광역 네트워크와의 활발한 연결을 맺는 것을 특징으로 한다. 집행 기능이라는 이름에 걸맞게, 다양한 네트워크 들의 기능을 동조시키거나 조율한다. 그래서 이를 기능적 허브(functional hub)라고 간주하기도 한다.[@Power2013-vz] 특히 FPCN은 학습/경험과 무관한 <s>유동성 지능</s>과 관계가 깊다.[@Cole2015-oo] 조현병 환자는 FPCN과 CON 혹은 DMN과의 연결성이 현저히 떨어진다.[@Sheffield2015-gl] 조현병 환자 뿐 아니라 우울증, 불안장애, 강박증 등에서도 FPCN의 연결성이 떨어지는 것이 발견되지만, 두 경우는 좀 차이가 난다. Cole 등[@Cole2014-pi]**​**은 이를 일차성과 이차성 기능저하로 나눠 설명한다. 일차성 기능 저하는 그야말로 FPCN을 구성하는 회로 자체나 신경 세포의 손상 때문에 기능이 떨어지는 경우이다. 이에 비해, 이차성 기능 저하는, 회로 자체의 손상은 없으나 우울/불안 등의 다른 증상을 억누르기 위해 FPCN의 자원을 소진한 나머지, 정작 인지기능에 사용할 여지가 남지 않은 경우를 말한다. Cole 등은 FPCN의 일차성 기능저하는 조현병과 양극성 장애의 특징이라고 주장한다.[@Cole2014-pi] 이상을 종합하면, 조현병 환자의 뇌는 FPCN의 일차적 기능 저하를 특징적으로 보이며, FPCN 내부의 연결성이 떨어질 뿐 아니라 FPCN과 다른 광역 네트워크와의 연결성도 떨어진다. 이 때문에 유동성 지능을 떨어뜨릴 뿐 아니라, CON과 DMN의 활성을 조율시키지 못하여 정신병적 증상을 유발하기도 한다.

<aside>

**유동성 지능 (fluid intelligence)**: 유동성 지능은 추리능력, 연산능력, 기억, 도형지각 능력 등 경험과 무관한 지능이고, 결정형 지능(Crystallized Intelligence)은 어휘, 일반상식, 언어이해, 판단과 같이 경험, 훈련 및 교육 등의 환경적 요인에 의하여 발달, 축적된 지능이다.

</aside>

FPCN이 과업을 시작하는데 필요한 초기 인지적 조절을 담당한다면, CON은 목표를 놓치지 않도록 유지하며, 오류가 생겼을 때 행동을 조절하는 역할을 맡고 있다.[@Godwin2017-it] 또한 내부로 부터 혹은 외부로 부터 전달되는 신호 중에서 현저하다고 여겨지는 신호를 탐지, 가공, 통합하는 역할을 맡는다.[@Huang2020-nw] CON의 연결성은 주어진 과제의 난이도가 높아질수록 강해지는 경향을 보인다.[@Sheffield2015-gl] 일부 연구에서는 조현병 환자에서 CON의 내부 연결성이 정상 대조군보다 낮으며, 그 정도는 음성 증상과 상관관계가 있다고 관찰되었다.[@Tu2012-dd] 그러나 다른 연구에서는 환자군이든 대조군이든, 인지과제의 난이도와 CON 연결성의 관계는 크게 차이나지 않는 것으로 나타났다.[@Sheffield2015-gl][@Godwin2017-it] 또 다른 연구에서는 정신병적 증상을 잠깐이나마 경험했던 일반인을 대상으로, 그 정도와 CON 연결성을 비교했더니 음의 상관관계가 관찰되었다.[@Sheffield2016-ld]

비정상적 현저성 이론([2장 6-4절 참조](article-02-06.html#aberrant-salience))은 망상을 형성하는 과정을 설명하는 주요 이론 중 하나이기 때문에, CON에 대한 관심은 여전히 높은 편이다. 더구나 CON은 FPCN과 DMN 사이를 매개하는 일종의 스위치 역할을 하기 때문에 더욱 중요성이 강조되었다.[@Dosenbach2007-vn] 앞에서도 잠깐 언급되었지만 FPCN은 목표 지향적으로 과제를 해결해야할 때 활성화되는 네트워크인 반면, DMN은 자극이나 과제가 없는 상태에서 정신내적 세계에 머무를 때 활성화된다. 안정상태에서 DMN이 활성화되어 있는 개체가 무언가 평소와 다른 자극을 감지하면, CON은 이 자극이 해결을 요구하는 가치가 있는지 아니면 무시해도 되는지를 결정한다. 만약 전자라면 DMN을 비활성화하는 대신, FPCN을 활성화시킴으로써 새로운 과제를 해결할 수 있도록 한다. 조현병 환자는 외적 세계와 내적 세계를 혼동하는 경향이 있으며, 무시해도 될 자극과 중요한 자극을 걸러내지 못한다. 이러한 인지적 메커니즘이 제대로 작동하려면 CON 기능이 온전해야만 한다. 따라서 연구자들이 CON의 이상을 확인하고자 애쓰는 것도 무리가 아니다.[@Huang2020-nw]

DMN이란 개념은 2001년 Raichle에 의해 제안되었다.[@Raichle2001-xd] fMRI 연구를 할 때는 특정 과업을 주었을 때 활성화되는 뇌 영역을 찾기 위해 아무 과제도 주지 않은 안정상태와 비교하게 되는데, 이 안정상태에서도 특정 뇌 부위가 독특한 패턴으로 활성 상태에 놓이게 된다는 것이 DMN을 찾게된 계기가 되었다. DMN을 이루는 뇌 구조물은 예로부터 조현병과 관련하여 많이 연구되던 부위들이고, DMN이 담당하는 뇌 기능 역시 조현병 증상과 연관이 있기 때문에 일찌기 조현병과의 관련여부가 연구되었다.[@Hu2017-bx]

조현병과 관련한 DMN 이상을 최초로 보고한 연구자는 Garrity등이다.[@Garrity2007-lr] 이들은 DMN 활성을 유도하는 인지과제를 주고, 뇌 대사가 활성화되는 부위와 주파수 특성을 측정한 후 환자군과 정상 대조군을 비교하였다. 그 결과 두 군사이의 유의한 차이를 발견해내었다. 같은 해 Bluhm 등은 DMN의 중심 구조인 후측 대상회(posterior cingulate gyrus)와 기타 영역들 간의 연결성이 떨어진다고 하였다.[@Bluhm2007-cu] 혼란스럽게도 이후 DMN의 활성 정도와 기능적 연결성(functional connectivity)을 대조군과 비교하는 유사한 연구들이 이어졌으나, 일관된 결과를 얻지는 못하였다.[@Hu2017-bx]

실험결과를 떠나서 연구자들은, 안정상태에서는 DMN이 활성화되어 있다가 현저성(salience)을 지닌 자극이 입력되면 순간적으로 DMN이 비활성화되면서 FPCN으로 활성이 옮겨간다고 생각하며, 이러한 역동적 전환이 제대로 이루어지지 않는 것이 조현병 환자의 특성이라 여긴다. FPCN과 DMN은 서로 음의 상관관계(anti-correlation)를 갖는 것이 정상적인데[@Uddin2009-ow], 조현병 환자에서는 이러한 음의 상관관계가 덜 현저하게 나타난다.[@Whitfield-Gabrieli2009-ln][@Wotruba2014-mj]

DMN의 활성과 연결성은 대체로 정비례하며 양성 및 음성 증상과도 유의미한 상관관계를 보인다.[@Whitfield-Gabrieli2009-ln], 따라서 DMN의 과활성과 과연결성을 조현병과 결부시키는 연구자가 많은 편이다.[@Whitfield-Gabrieli2012-cd] 이러한 DMN의 과활성과 과연결성은 약물 치료 중인 환자는 물론 약물을 한번도 사용한적이 없는 환자에게도 나타날 뿐더러, 발병하지 않은 환자 가족에게서도 발견할 수 있다.[@Galindo2017-cv][@Guo2017-pa] 한편 연결성의 이상은 조현병 환자에게 흔히 동반되는 연성 신경학적 징후(neurological soft signs)와도 연관이 있다고 한다.[@Kong2020-lw] 적지 않은 연구자들은 DMN의 활성 및 연결성을 조현병의 대표적인 생물학적 지표의 하나로 간주하고 있다
