---
title: "2절 근대적 조현병 개념과 DSM"
description: Modern Concept of Schizophrenia and DSM
bibliography: references/01-02.bib
link-citation: yes
---

<a href="article-01-01.html"><i class="arrow far fa-arrow-alt-circle-left"></i></a>

<a href="article-01-03.html"><i class="arrow far fa-arrow-alt-circle-right"></i></a>

## 2-1. 미국의 상황과 정신분열병 개념의 도입

미국 정신의학회(American Psychiatric Association, APA) 회장을 지낸 <s>Meyer</s>는 크레펠린의 분류 시스템에 감명을 받아 이를 미국에 최초로 도입하였지만, 역설적으로 블로일러의 개념을 정착시킨 인물이기도 하다. 블로일러의 개념이 발표되기도 전에 이미 그는 조발성 치매는 생물학적 요인을 갖고 있는 환자가 심리사회적 상황에 적응하면서 형성되는 "반응(reaction)"이라고 생각하였다. 이는 모든 정신질환은 생물학적, 심리학적, 사회학적 맥락에서 고려되어야 한다는 심리생물학(psychobiology) 이론의 토대가 된다.

<aside>

**Adolf Meyer (1866\~1950)**: 스위스 태생의 미국 정신과 의사. 존스 홉킨스 대학 교수이자, 부속 병원의 수석 정신과 의사로 역임하면서, 1913년에는 Henry Phipps 정신의학 진료소 개원을 이끌었다. 1927-28년에는 미국 정신의학회 회장을 역임하였다.

</aside>

따라서 그가 1913년 <s>Phipps 클리닉</s>을 설립하면서 개막식 연자 중 한명으로 블로일러를 초대한 것은 우연이 아닐 것이다. Phipps 클리닉은 미국 최초로 "schizophrenia"라는 진단명을 사용하기 시작하였다. 초창기에는 조발성 치매와 정신분열병 개념이 혼재되면서, 4A 증상을 보이며 증상이 그리 심하지 않은 환자에게는 "정신분열적 반응(schizophrenic reaction)"이라는 진단이 붙여지고, 퇴행이 명백한 경우에는 조발성 치매라는 진단을 붙여지곤 하였다.

<aside>

**Henry Phipps Psychiatric Clinic**: 볼티모어에 위치한 존스 홉킨스 의과대학의 부속 정신과 병원. 철강 사업가 였던 Henry Phipps Jr.의 기부로 설립되었다.

</aside>

그러나 정신분열병 개념이 승리한 결정적인 계기는 미국 정신의학 대부로서의 Meyer의 정치적 지위와 함께, 나찌의 권력 장악과 유대인 박해에 있었다. 블로일러와는 대조적으로 크레펠린은 자신의 민족주의적 정치색을 마음껏 드러내었고, 크레펠린의 분류를 받아들이는 것은 친나찌 성향을 드러내는 것으로 분위기가 반전되었다. 1918년 미국 정신의학회의 전신인 American Medico-Psychological Association (AMPA)은 조발성 치매 대신 정신분열병을 사용할 것을 공식화하였고, 그와 함께 블로일러가 제안하고 Meyer가 지지하였던 단순 조현병 및 잠재 조현병 개념 역시 공식적으로 인정된다. 이렇게 해서 "정신분열병"의 시대가 열리게 되었다.

## 2-2 DSM의 제정 {#dsm-constitute}

전통적으로 독일권 정신의학자들은 기술과 분류(description and classification)에 열정적이었다. 당시의 의학 학술지는 상세한 증례를 보고하는 논문이 넘쳐났고, 현상학 전통을 물려받은 의학자들은 정신분석과는 또 다른 의미에서 환자의 심층적 경험을 추적하였다. 반면 실용주의에 기울어있던 미국 정신의학자들은 이론보다는 환자를 돌보는데 집중한 나머지, 정확한 진단을 내리거나 질병의 정체를 숙고하는데는 그다지 관심이 없었다. 따라서 미국 최초의 진단분류체계가 연구를 위해서가 아니라 행정적 필요에 의해 탄생했다는 사실은 그리 놀랄 일이 아니다.

애초에 AMPA는 통계청의 위탁을 받아 미국 전역에 흩어진 정신병원의 현황을 조사한다는 기본 계획을 세웠다. 1921년 AMPA는 미국 정신의학회(American Psychiatric Association, APA)로 이름을 바꾸고, 본격적으로 분류체계의 기초를 닦기 시작하였다. 바야흐로 2차 대전이 끝나자, 미 육군은 재향 군인을 대상으로 정신질환 현황과 정신건강 서비스 수요를 조사하는 과업을 APA에 의뢰하였다. 마침 1948년 국제보건기구(World Health Organization, WHO)에 의해 발표된 국제질병분류(International Classification of Disease, ICD) 6판은 최초로 정신질환에 대한 챕터를 포함하고 있었고, 미국 정신의학회는 이를 보완하는 수준에서 1952년 정신질환 진단 및 통계 편람(Diagnostic and Statistical Manual of Mental Disorders, DSM)을 내어놓는다.

![Figure 1. 1952 edition of the DSM (DSM-I).\
Retrieved from [Wikipedia](https://en.wikipedia.org/w/index.php?curid=61363721)](images/01-02/dsm-i.jpg){#fig:dsm-i width="60%"}

Meyer의 영향 하에 첫번째 DSM에서는 환경적인 원인을 염두에 두어 정신증 진단과 관련된 용어에는 "반응(reaction)"이라는 표현이 반드시 포함되었다.[@Grob1991-ul] 따라서 조현병은 "정신분열적 반응"이라 불리워졌다. Meyer를 비롯한 정신분석가들은, 정신질환은 생물학적, 심리적, 사회적 요소의 통합체로서의, 개인이 자신을 둘러싼 환경이나 닥쳐진 상황에 제대로 적응하지 못했기 때문에 생긴다고 보았다.[@Lidz1985-gv] 이는 단일정신병 개념에 접근하고 있다는 점에서, 크레펠린 식 질병단위 개념을 부정한 것으로 생각할 수 있다. 진단 분류표가 나왔다고 하지만, 당시에는 조현병의 정의 자체가 모호했고, 감별 진단에 대한 언급도 없었으며, 구체적인 진단기준도 제시되지 않았다.

### 2-2-1. DSM-II

1960년대에 들어서면서 미국 정신의학은 서서히 Meyer의 영향으로부터 벗어났지만 여전히 미국 정신의학회의 주도권을 쥐고 있던 것은 역동 정신의학과 정신분석학파였다. 1967년 WHO는 정신장애 분류를 대폭 수정한 ICD-8을 출간했다. 정신장애는 1) 정신증, 2) 신경증, 인격장애 및 비정신병적 정신장애, 3) 정신지체의 세 가지로 대별되었다. 1968년 미국 정신의학회는 ICD-8에 대응되는 DSM-II를 발표한다. 가장 큰 특징은 "반응"이라는 용어가 완전히 삭제되었고, 특정 이론적 틀을 사용하지 않는 기술적인(descriptive) 분류가 시도되었다는 것이다. 이는 크레펠린 철학으로 회귀하는 첫번째 시도라 볼 수 있다. 그러나 정신분석가들은 여전히 블로일러의 생각에 매달려있었고, 결과적으로 조현병의 진단범위가 무척이나 넓어졌고, 불로일러의 단순형 조현병(simple schizophrenia), 또는 Hoch와 Polatin이 제안한 <s>가성 신경증성 조현병</s> 등이 포함되었다.[@OConnor2009-jv] 그러나 DSM-II에도 역시 구체적인 진단 기준이 제시된 것은 아니었고, 어디까지나 전형적인 환자에 대한 묘사만이 실려있었다.

<aside>

**가성 신경증성 조현병 (pseudo-neurotic schizophrenia)**: Paul Hoch와 Philip Polatin이 제안한 질병명이다. 기본 증상으로는 사고장애, 감정조절 장애, 감각기관이나 자율신경계 기능부전이며, 부수증상으로는 불안, 노이로제, 성적 방종 등이다. 이 개념은 Otto Kernberg에 의해 경계성 인격장애로 흡수되었다.

</aside>

DSM-II가 발표된 1968년은 정신의학계 내외적으로 격동의 시기였다. 정신분석에 치우친 정신의학은 주류 의학에서 배제된 상태였고, 심리학과의 경계도 애매하였다. 비용이 많이 드는 정신분석이 과연 환자를 낫게 하는 지에 대한 반성과 함께, 무의식을 해석하여 통찰을 얻게 된 사람이 얼마나 되겠느냐는 비판이 드세졌다. 미국의 반문화 운동(<s>히피 문화</s>)이나 프랑스의 <s>68 운동</s>은 기존의 가치와 질서를 무너뜨리고자 하는 당시의 세계관을 반영한다. 무의식을 들여다보고 있는 것은 부유층의 지적 유희로 여겨졌고, 동시에 누가 무슨 권리로 미친 사람과 그렇지 않은 사람을 나눌 수 있느냐는 질문이 던져졌다. 이렇게 시작된 반정신의학의 급물결은 현재까지도 영향을 끼치고 있다.

<aside>

**히피 문화 (Hippie culture)**: 1960년대 미국 젊은이들은 2차 대전 이후 강요되었던 보수주의나 군국주의 문화에 저항하였고, 급부상하는 물질주의도 거부하였다. 반전 운동, 인권보장, 성적 자유, 여성과 유색 인종의 권위신장 등이 급물살을 탔다. 이중 주류 문화에 반대하여 LSD나 마리화나를 피우며, 유사종교에 심취하여 전국을 떠도는 생활을 누리던 젊은 층을 히피라고 불렀다.

**68 운동**: 1968년 프랑스 대학생들은 자본주의, 소비만능주의, 미국 중심 제국주의에 반대하여 시위를 거듭하였고, 5월이 되자 노동조합이 합세하면서 전국적인 파업과 봉기로 이어졌다. 결국 정부와 노동자 측과의 근로환경 협상이 타결된 후에야 잦아들었다. 시위 도중 반정신의학의 기치를 내건 학생들이 당시 프랑스 정신의학의 거두인 Jean Delay의 사무실을 점거하였고, 그는 이를 계기로 의업을 중단하였다.

</aside>

한편 1952년 시작된 정신약물학의 혁명은 정신의학이 정신분석을 떠나, 생물정신의학으로 돌아가야할 필요성을 실감하게 하였다. 정신의학은 양립하는 가치관(반정신의학과 생물정신의학) 사이에 끼어 질식할 지경에 이르렀다.

### 2-2-2. DSM-III {#dsm-iii}

갈등이 불거지고 비판이 거세진만큼, 정신질환의 정의를 마련하고 분류기준을 세우는 작업은 철저한 객관성을 확보해야만 했다. WHO가 주도한 <s>International Pilot Study of Schizophrenia (IPSS)</s>와 같이 여러나라가 연구에 참여할 때는, 모든 연구자가 공통적으로 사용할 수 있는 표준화된 평가척도가 필요하였다. 이에 영국 <s>모즐리 병원</s>의 연구팀은 최초의 표준화된 평가척도인 현상태 검사(Present State Examination, PSE)를 제작한다.[@Wing1967-ka] PSE는 블로일러의 기본증상 대신, 슈나이더의 일급증상을 기준으로 삼았고, 이는 일급증상이 널리 알려진 계기가 되었다. 한편 IPSS 연구를 계기로 서로 다른 나라에서 동일한 기준을 적용하여 진단을 내려보니, Meyer의 영향 하에 있던 미국에서 조현병이 지나치게 많이 진단되고 있음이 밝혀졌다. 더군다나 1973년에는 악명높은 <s>로젠한 실험</s>의 결과가 학계를 뒤흔들었다. 이를 통해 정상과 질병의 경계가 얼마나 모호하고, 소위 진단과정이 얼마나 형식적이고 정확성을 결여하고 있는 지가 만천하에 폭로되었다. 미국 정신과 의사들은 자신들의 관행을 되돌아보지 않을 수 없었다. 이러한 계기를 바탕으로 소위 <s>세인트루이스 학파</s>는 Feighner 진단기준[@Feighner1972-ed]**​**과 연구진단기준(Research Diagnostic Criteria, RDC)[@Spitzer1978-uu]**​**을 만들게 되었다.

<aside>

**The International Pilot Study of Schizophrenia**: 이 연구는 문화와 소득수준이 전혀 다른 9개 나라 국민을 대상으로 정신질환의 실태를 조사하는 연구로서 1968년에 시작되었다. 1,202명의 환자가 모집된 당시로서는 대규모 연구이며, 향후 역학조사를 위한 방법론을 마련하는 발판으로 설계되었다.

**모즐리 병원 (Maudsley Hospital)**: 영국 런던에 소재한 정신과 병원. 1907년 정신과 의사 Henry Maudsley의 기부로 건설계획이 세워져 1923년에 문을 열었다. 현재까지도 영국에서 가장 규모가 큰 수련 정신병원이다.

**로젠한 실험 (Rosenhan experiment)**: 스탠포드 대학 심리학과 교수인 David Rosenhan이 미국 내 정신의학 진단의 정확성을 평가하기 위해 행한 실험. 미리 훈련받은 가짜 환자들이 신분을 숨기고 미국 5개 주 12개 정신병원에서 진료를 보았고, 한명만을 제외하고는 모두 조현병으로 진단되어 입원하였다. 입원 직후 가짜 환자들은 자신들이 어떠한 병적 증상도 경함하지 않는다고 주장하였으나, 의사들은 이를 인정하지 않았고 항정신병 약물을 복용할 것을 강요하였다.

**세인트루이스 학파**: 미국 세인트루이스 소재 워싱턴 대학 정신과에 근무하던 Eli Robins, Samuel Guze, George Winokur는 1950년대부터 정신의학을 정신분석 이전으로 되돌려야 한다고 주장하여 소위 신크레펠린 학파(Neo-Kraepelinian)로 불린다. 그들은 명확한 진단과 분류 기준을 세워, 평가자간 진단 신뢰도를 높이고, 정상과 질병의 구별도 분명히 해야한다고 믿었다. 1967년 워싱턴 대학 전공의를 시작한 John Feighner는 세 스승의 토론에 참여하면서 진단 기준 세트를 만드는데 주력한다. 1972년 발표된 이 기준을 "Feighner criteria"라고 한다.

</aside>

1974년 <s>Spitzer</s>는 DSM-III를 만들기 위한 특별위원회의 회장으로 임명되었다. 그는 세인트루이스 학파와 함께 작업했고, Feighner 진단기준을 확장하여 RDC를 만들게 된다.[@Spitzer1978-uu] Feighner 진단기준, 그리고 좀더 복잡해진 RDC가 과거 진단기준과 근본적으로 차이나는 것은, <s>조작적 진단기준</s>의 도입이었다.[@Farmer1993-ca] DSM-III의 조현병 진단기준은 RDC를 거의 그대로 물려받았는데, 여기에는 몇 가지 기준 중에 몇 개 이상을 만족하면 진단한다는 식의 기준들이 포함되어 있다. 조작적 진단기준은 무엇보다 비전문가라도 비교적 용이하게 적용할 수 있었고, 신뢰도가 높아서 누가 진단했더라도 어느 정도는 믿을만 했다.

<aside>

**Robert Leopold Spitzer (1932\~2015)**: 미국의 정신과 의사이자 컬럼비아 의대 교수.1968년 정신과 진단을 위한 컴퓨터 프로그램을 만들 정도로 일찌기 조작적 진단기준을 용호하였으며, 정해진 설문으로 이루어진 구조화된 진단도구 개발에 앞장섰다. 1974년 부터 DSM-III 개발을 주도하였다.

**조작적 진단기준 (operational criteria)**: 질병의 본질이나 정의가 밝혀지지 않았을 때, 객관적으로 관찰가능한 특징(증상, 징후, 검사소견 등)을 중심으로, 진단을 내리려면 어떤 특징이 필요하고 반대로 어떤 특징이 있으면 배제할 수 있다는 식의 기준을 설정한 것. 각 항목은 객관적으로 검증 가능하여 예/아니오로 평가될 수 있어야 하며, 자의적 해석의 여지가 없어야 한다.[@Kendell1975-lc]

</aside>

DSM-III는 최초로 조작적 진단기준을 적용한 체계였으며, 이외에도 무이론적/기술적 접근, 다축 진단 그리고 계층적 진단 체계였다. 무이론적/기술적 (atheoretical/descriptive) 접근이란 정신분석적 이론이든 생물학적 이론이든 질환의 원인에 대한 어떤 선입관도 개입시키지 않겠다는 것이다. DSM-I에서 보았듯이, 진단체계 자체에 이론적 편향이 개입되면 이후 연구를 가로막을 위험이 있다. 당시까지 정신질환의 원인으로 증명된 것이 아무것도 없었던 만큼 미래의 연구를 방해하지 않겠다는 의지의 표현이었다.

증명되지 않은 이론에서 벗어나겠다는 의지의 표현은 "질환(disease)"이라는 용어를 사용하지 않은 것에서도 여실히 드러난다.[@Cooper2004-cw] 질환이란 고유한 병태생리가 존재하는 <s>질병분류학적 단위</s>, 즉 자연적 종을 의미한다.([1장 1-3절 참조](article-01-01.html#modern-period)) DSM-III은 이 대신 "장애(disorder)"라는 말을 사용하는데, 이는 "임상적으로 중요한 행동적 또는 심리적인 증상 또는 패턴"이고, "개인에게 고통을 주거나, 두 가지 이상의 중요한 영역에 있어서 기능 상실을 초래하는 것"으로 정의된다. 따라서 장애가 있다는 말이 정상과 비정상을 나누는 기준이 될 수는 없다. 이는 정신과 의사가 정상의 한계를 규정할 수는 없다는 비판을 염두에 둔 것으로 보인다. 조현병에 있어서도 공식적 명칭은 "조현성 장애(schizophrenic disorder)"라는 단어를 사용하여 "schizophrenia"라는 질병명을 애써 피하고 있다. 마지막으로 정신증과 신경증이라는 구분도 사라졌으며, 대신 "정신병적(psychotic)"이라는 개념만 남게 되었다.[@Thomas2001-dd] 이에 따르면 내인성 정신증과 같은 개념이 들어설 자리는 사라져 버렸으며, WKL 체계와 같이 어떻게든 진단과 그 원인을 짝지우려는 시도와도 함께할 수 없게 되었다.([1장 1-10절 참조](article-01-01.html#wernicke-kleist-leonhard))

<aside>

**질병분류학적 단위 (nosological entity)**: 질병분류학적 계층 구조를 구성하는 기본 단위. 린네의 생물분류체계에서 종(species)의 개념을 도입하여, 뚜렷이 구별되는 원인, 병태생리, 증상, 경과로 정의되는 질병분류학적 단위를 질병(disease)이라고 한다. 질병의 지위를 획득하지는 못했지만 임상적으로 흔히 함께 나타나는 증상군을 증후군(syndrome)이라 하며, 이 역시 질병분류학적 단위의 하나이다. 이러한 단위의 결정은 임의적인 요소가 많고, 자연 현상은 연속적(continuous)/다차원적(dimensional) 이기 때문에, 질병분류학은 "자연을 관절에서 억지로 분리하는 것(carving nature at its join)"이라는 비판을 받아왔다.

</aside>

DSM-III의 조현병 진단 기준은 <s>A 기준</s>에 속한 6개의 증상 중 하나 이상을 급성기 동안 보여야 하며(최소 기간은 명시되지 않음), 전체적인 이환 기간은 6개월 이상이 되어야 한다.([표 1](#tab:dsm-iii-criteria)) 6개 증상 중 두 가지는 슈나이더의 일급 증상을 그대로 나열하고 있다. 반면 사고 장애 및 인지/정서/행동 증상은 뭉뚱그려져 하나의 항목을 이루고 있다. 일급 증상을 진단 기준에 끼워넣으면 신뢰도가 향상되리라는 기대를 엿볼 수 있는 대목이다. 진단 기준에 유의한 기능 수준 저하가 포함되었고, 전구, 잔류 증상에 대한 자세한 기술이 되어있는 것은 크레펠린의 "치매" 개념이 영향을 주고 있기 때문이다.

<aside>

**A 기준 (A criteria)**: DSM에 언급되는 거의 모든 장애의 진단기준은, A 항목에 질병에 걸린 환자가 보이는 주요 증상을 나열하고, 이중 몇 개 이상을 만족해야 진단을 내릴 수 있다는 문구로 시작한다. 그래서 이를 통상적으로 A 기준이라고 한다.

</aside>

::: {#tab:dsm-iii-criteria .table}
```{=html}
<table>
<thead><tr"><th></th><th>A. At least one of the following during a phase of the illness:</th></tr></thead><tbody>
 <tr><td>1</td><td>bizarre delusions (content Is patently absurd and has no possible basis In fact), such as delusions of being controlled, thought broadcasting, thought insertion or thought withdrawal</td></tr>
 <tr><td>2</td><td>somatic, grandiose, religious, nihilistic, or other delusions without persecutory or jealous content</td></tr>
 <tr><td>3</td><td>delusions with persecutory or jealous content if accompanied by hallucinations of any type</td></tr>
 <tr><td>4</td><td>auditory hallucinations in which either a voice keeps up a running commentary on the individual's behavior or thoughts, or two or more voices converse with each other</td></tr>
 <tr><td>5</td><td>auditory hallucinations on several occasions with content of more than one or two words, having no apparent relation to depression or elation</td></tr>
 <tr><td>6</td><td>incoherence, marked loosening of associations, markedly illogical thinking, or marked poverty of content of speech if associated with at least one of the following:</td></tr>
 <tr><td>&nbsp;</td><td>a. blunted, flat, or inappropriate affect</td></tr>
 <tr><td>&nbsp;</td><td>b. delusions or hallucinations</td></tr>
 <tr><td>&nbsp;</td><td>c. catatonic or other grossly disorganized behavior</td></tr>
 <tr><td></td></tr>
</tbody></table>
```
::: {.figcaption}
Table 1. Criterion A of Schizophrenia in DSM-III
:::
:::

### 2-2-3. DSM-IIIR과 DSM-IV {#dsm-iiir-dsm-iv}

DSM-III-R은 1987년에 출판되었다. 어색했던 조현성 장애라는 이름 대신 원래의 "schizophrenia"로 명칭이 바뀌었으며, 45세 이전에 발병해야한다는 기준이 삭제되었다. 6개 증상 중 하나라는 기존의 기준 대신, 일반 증상은 두 개 이상, 일급 증상은 하나 이상으로 비중이 차별화되었다. 눈여겨 보아야 할 것은 사고 장애가 일반 증상에 속한다는 것이다. 즉 블로일러 식의 4A 증상이 있다 하더라도 그것만 갖고는 조현병 진단을 내릴 수가 없었다. 오히려 DSM-III 보다도 더 양성 증상, 특히 일급 증상의 비중이 높아졌다. 또한 급성 증상이 최소한 1주 이상 지속되어야 한다는 단서가 추가되었다.

1994년 발표된 DSM-IV는 기본적 틀에서는 DSM-IIIR에서 크게 변하지 않았지만, 소소한 차이가 있다. 일단 처음으로 음성 증상이라는 용어가 공식적으로 포함된다. ([표 2](#tab:dsm-iv-criteria)) DSM-IIIR은 "둔화되거나 현저히 부적절한 정서"라고 표현했지만, DSM-IV는 대응되는 항목을 "음성 증상, 즉 둔화된 정동, 무언어증(alogia) 혹은 무의욕증(avolition)"이라 표현한다.([표 2](#tab:dsm-iv-criteria)) <s>Andreasen</s>**​**[@Andreasen1982-qk]이 Scale for the Assessment of Negative Symptoms (SANS)를 발표한 것이 1982년이고, Kay 등​[@Kay1987-np]​이 <s>양성 및 음성증후군 척도(PANSS)</s>를 발표한 것이 1987년이다. 이후 수년간에 걸쳐 음성 증상은 조현병 이해에 빼놓을 수 없는 근본 증상이 되었고, DSM 역시 이를 외면할 수 없었다. 슈나이더는 양성 증상, 블로일러는 음성 증상이라는 구도에서, 블로일러의 비중이 조금씩 회복하고 있는 셈이다. 또 다른 변화로는 급성 증상이 1주가 아니라 1달 이상 지속되어야 한다는 것, 그리고 연상의 이완이 와해된 언어로 바뀐 정도이다. 후자는 환자의 사고과정은 언어를 통해 파악할 수 밖에 없으며, 언어를 통해 간접적으로 사고 장애를 추정하는 것 보다는, 언어 자체를 평가하는 것이 진단신뢰도를 높이는데 도움이 된다는 생각을 반영하고 있다.

<aside>

**Nancy Cooper Andreasen (1938\~)**: 미국 아이오와 대학의 정신과학 교수. 조현병의 음성 증상의 개념을 정립하는데 공헌하였고, 조현병의 뇌영상학 연구에도 다수의 업적이 있다. 원래 전공은 영문학, 역사학과 철학이었으며, 뒤늦게 의사의 길을 가게 되었다. 그래서인지 정신의학의 철학적 고찰에 대한 많은 기고를 하였다.

**양성 및 음성 증후군 척도 (Positive and Negative Syndrome Scale, PANSS)**: 조현병 환자의 증상의 심각도를 다면적으로 평가하는 가장 널리 사용되는 평가척도 중 하나이다. 1987년 Stanley Kay, Lewis Opler, and Abraham Fiszbein에 의해 제작되었으며, 현재까지도 항정신병 약물 연구에서 빠져서는 안 되는 표준 척도이다. 인터뷰에 의해 평가자가 총 30문항에 대해 1점에서 7점 사이로 평가한다. 양성, 음성, 일반 정신병리 척도로 구성되어 있다.

</aside>

::: {#tab:dsm-iv-criteria .table}
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|      | A: Characteristic symptoms: Two (or more) of the following, each present for a significant portion of time during a 1-month period:                                                                                                    |
+======+========================================================================================================================================================================================================================================+
| (1)  | Delusions                                                                                                                                                                                                                              |
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| (2)  | Hallucinations                                                                                                                                                                                                                         |
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| (3)  | Disorganized speech                                                                                                                                                                                                                    |
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| (4)  | Grossly disorganized or catatonic behavior                                                                                                                                                                                             |
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| (5)  | Negative symptoms, i.e., affective flattening, alogia, or avolition                                                                                                                                                                    |
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|      | *Note: Only one Criterion A symptom is required if delusions are bizarre or hallucinations consist of a voice keeping up a running commentary on the person's behavior or thoughts, or two or more voices conversing with each other.* |
+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

::: {.figcaption}
Table 2. Criterion A of Schizophrenia in DSM-IV-TR
:::
:::
