---
title: "2장 2절: 후성유전학적 변화"
description: Epigenetic Modifications in Schizophrenia
bibliography: references/02-02.bib
link-citation: yes
---

<a href="article-02-01.html"><i class="arrow far fa-arrow-alt-circle-left"></i></a>

<a href="article-02-03.html"><i class="arrow far fa-arrow-alt-circle-right"></i></a>

## 2-1. 스트레스와 뇌 기능 변화의 연결 경로 {#stress-brain}

소위 조현병의 2회 충격 가설([2장 3-1절 참조](article-02-03.html#neurodevelopment-birth))에 의하면, 유전적 요인 등으로 인해 취약성을 갖고 태어난 개인이라 할 지라도, 차후에 감당하기 어려운 심리사회적 스트레스를 받지 않는 이상 발병 위험은 그다지 높아지지 않는다. 또한 심리사회적 스트레스는 이후 재발의 계기가 되기도 한다. Meyer와 그를 따르는 20세기 전반의 미국 정신의학자들이 조현병을 "조현병적 반응(schizophrenic reaction)"이라고 불렀던 것은, 아무리 조현병이 뇌질환이라 할 지라도, 개인이 자신을 둘러싼 환경이나 주어진 상황에 제대로 적응하지 못해 생긴 문제라고 믿었기 떄문이다. ([1장 2-2절 참조](article-01-02.html#dsm-constitute))

아무리 조현병을 생물학적 질환으로 이해하고자 해도, 심리사회적 스트레스가 발병 및 재발에 중요한 비중을 차지한다는 것을 부인할 수 없다.[@Nuechterlein1992-wb][@Corcoran2002-xa] 그렇다면 신체와 마음, 즉 생물학적 영역과 심리학적 영역 간에 서로 영향을 주고받는 통로가 반드시 있어야만 한다. 과거에는 신경내분비 계통이 이 통로의 역할을 담당한다고 믿어졌다. 장기간에 걸쳐 심리적 고통을 겪으면 스트레스 호르몬이 과도하게 분비되고, 내분비계 조절기전이 혼란상태에 빠진다. 스트레스 호르몬은 세포내 수용체를 통해 세포 내 신호전달계를 교란시키며, 이로 인해 정상적인 신경세포의 기능발휘가 불가능해진다. 따라서 시상하부-뇌하수체-부신 축(Hypothalamic-Pituitary-Adrenal axis, HPA axis)은 조현병을 비롯한 다양한 정신질환을 이해하는데 빠지지 않고 등장하는 단골 소재가 되어 왔다.[@Muller1990-vl][@Chan2010-jl]

물론 스트레스와 뇌 기능 변화를 연결시키는 경로는 HPA 축뿐만이 아니다. 스트레스는 도파민 활성을 직접적으로 변화시킨다.[@Wang1994-xb] 급성 스트레스는 대뇌피질의 도파민 분비를 늘이며, 선조체의 도파민 활성은 억제한다.[@Pani2000-st] 그러나 만성적으로 스트레스에 노출되면 도파민 분비세포가 허탈 상태에 빠지기 때문에 피질의 도파민 활성이 점차 감소하게 된다.[@Mizoguchi2000-qw] 최근에는 또 다른 스트레스 연관 통로로 <s>내인성 카나비노이드 체계</s>가 각광받고 있다. 카나비노이드는 스트레스에 대한 반응을 경감시켜주는데**​**[@Cota2008-lj], 조현병 환자에게서 이 체계의 이상이 자주 발견된다.[@Muguruza2019-fr]

<aside>

**내인성 카나비노이드 체계 (endocannabinoid system)**: 카나비노이드 화합물은 식물 및 동물에서 자연적으로 합성되며, 인간 역시 anandamide, 2-arachidonoylglycerol 등을 합성할 수 있다. 이들은 주로 중추신경계에 분포하는 카나비노이드 수용체, CB1, CB2에 결합하여 수면, 기분, 식욕, 생식, 통증 감각, 인지기능 등을 조절한다. 대마초의 주성분인 tetrahydrocannabinol (THC)는 대표적인 외인성 카나비노이드이며, 최근 정신질환 치료 효과로 주목받고 있는 cannabidiol (CBD)은 불안, 운동장애, 통증을 가라앉히는 효과가 있다.

</aside>

그러나 위에 연결한 경로들은 순간순간 스트레스와 뇌 기능 변화사이를 매개하는 데는 적합할 지 몰라도, 수년간에 걸쳐 장기간 지속되는 구조적 변화를 설명하기 어렵다. 조현병의 신경발달학적 가설에 따르면, 취약성을 높이는 유전자 변이는 신경회로의 구조적 이상을 낳고, 구조적 이상은 돌이키기 어려운 기능의 결함을 부른다. 하지만 취약성을 높이는 유전자 변이는 단지 발병의 확률을 조금 높일 뿐 거스를 수 없는 운명이 아니다. 게다가 취약 유전자를 물려받지 않은 경우에도 과도한 스트레스에 의해 여전히 조현병이 발생한다는 것은, 스트레스와 유전자 기능이 서로 무관하지 않음을 시사한다. 구조적 변화가 생기기 위해선 유전자 단계에서 이상이 있어야만 하는데, 그렇다고 후천적 스트레스가 <s>신생 돌연변이</s>를 일으키는 것은 불가능하다. 그렇다면 유전자 서열을 바꾸지 않으면서도, 유전자 기능을 켰다 껐다하는 스위치가 어딘가에는 존재해야 한다는 결론에 도달한다.

<aside>

**신생 돌연변이(de novo mutation)**: 부모에게서는 발견되지 않으나, 자식 세대에서 새롭게 발견되는 유전자 서열의 변이. 생식세포에서 DNA 복제나 복구 과정에 문제가 생기면서 변이가 발생한 것이 자식에게 전달된 것이다. 난자보다는 주로 정자에서 발생하며, 한 세대당 약 70개 정도의 변이가 생긴다고 한다.

</aside>

더불어 신체의 모든 세포가 애초에는 하나의 수정란에서 출발했다는 것을 상기해본다면, 유전자 정보가 같은 수많은 세포가 각기 다른 종류의 세포들로 분화되는 것 역시, 유전자 스위치의 존재를 암시한다. 후성 유전학(epigenetics)은 바로 이렇게 후천적으로 작동하는 유전자 스위치에 대한 유력한 이론이다. 후성 유전학의 발견은 개체가 갖고 있는 게놈이 개략적인 청사진일뿐, 결코 개체의 운명을 세부사항까지 못 박아 놓은 것이 아님을 분명히 해주었다. 게놈에는 수없이 많은 스위치들이 있으며, 이는 환경적 영향에 의해 켜지기도 하고, 꺼지기도 한다. 후성 유전학적 메카니즘은 개체에게 수없이 많은 가능성을 실현할 수 있도록 해주며, 따라서 변화하는 환경에 유연하게 적응하는데 없어서는 안될 기전이다.

## 2-2. 후성 유전학

후성 유전학 이론은 그 전까지 분자생물학을 이끌어왔던 <s>중심 도그마</s>, 즉 생물학적 정보는 한 방향으로만 흐른다는 원리에 과감한 도전장을 내민다.[@Crick1970-vi] 중심 도그마에 의하면 DNA에서 RNA(전사), 그리고 RNA에서 단백질(번역)로 정보가 전달되며, 역 방향으로의 전달, 즉 단백질에서 DNA나 RNA로의 정보 전달은 일어날 수 없다. 이 이론을 확장하면, 생명체의 모든 정보는 DNA가 쥐고 있으며 염기서열이 바뀌지 않는 한 정보 자체가 변할 일은 없다는 것이다. 이에 반해 후성 유전학에서는 단백질에서 RNA로의 정보전달이 가능하며, 이를 통해 환경적 변화가 새로운 정보로서 DNA와 RNA에 기입될 수 있다고 주장한다.

<aside>

**중심 도그마(central dogma of molecular biology)**: 중심 도그마는 두 개의 버전이 존재한다. Francis Crick은 정보가 핵산에서 단백질로 흐를 뿐 그 역으로의 흐름은 있을 수 없다고 주장했으며, James Watson은 정보는 DNA에서 RNA로 그리고 RNA에서 단백질로만 전달될 수 있다고 주장하였다. 이후 역전사효소(reverse transcriptase)의 발견에 의해 Watson의 주장은 사실이 아니라는 것이 명백해졌다.

</aside>

인간 게놈에 포함된 DNA 중 대다수는 기능이 밝혀지지 않은 <s>비코딩 DNA</s>이다. 또한 설령 전사되었다 하더라도 아미노산을 만들지 않는 <s>비코딩 RNA</s>가 존재한다.[@St_Laurent2007-xa] 이들 코딩되지 않는 염기서열들은 코딩 영역의 전사나 발현 정도를 조절하고 있다. 그 기전은 첫째, 역시 비코딩 DNA에 위치한 <s>CpG 영역</s>의 메틸화, 그리고 히스톤 단백질의 메틸화를 통한 <s>염색질</s> 구조의 변화이다.

<aside>

**비코딩 DNA (non-coding DNA)**: 게놈에서 단백질로 번역되지 않는 염기서열로 전체 게놈의 98%를 차지한다. 대부분은 유전자와 유전자 사이의 광활한 공백에 위치하며, 일부는 유전자 내의 intron에 존재한다. 이중 소수는 프로모터(promoter) 등 조절 유전자에 속하지만, 전혀 기능이 밝혀지지 않은 서열이 더 많다. Junk DNA라고도 불리운다.

**비코딩 RNA (non-coding RNA)**: 단백질로 번역되지 않는 RNA. 여기에는 miRNA, siRNA, piRNA, lncRNA 등 다양한 종류가 있다. 이들은 전사, 전사 후 변형(post-transcriptional modification), 번역, 번역 후 변형(post-translational modification) 단계에서 세밀한 조절에 관여한다.

**CpG 영역**: DNA에서 cytosine (C)과 guanine (G)의 서로 연달아있는 염기서열이 높은 빈도로 반복되는 영역. 특히 빈도가 높은 영역을 CpG island라고 부른다. CpG 영역은 유전자의 프로모터에 주로 위치하는데, DNA methyltransferases (DNMTs)에 의해 이중 cytosine에 메틸화(methylation)가 일어나면 해당 유전자는 더 이상 전사되지 못한다.

**염색질 (chromatin)**: DNA, RNA, 단백질로 구성된 거대분자 복합체이다. 세포 내의 DNA를 모두 풀어놓으면 약 3미터에 달한다. 이렇게 긴 DNA를 작은 세포핵 내부에 담아두기 위해서 히스톤 단백질을 중심으로 단단하게 꼬아놓아야 한다. 이렇게 부피를 줄이고, 외부 충격으로 부터 DNA를 보호하며, 필요한 부분만을 풀어놓아 전사가 이뤄지게 하는 구조가 바로 염색질이다. 세포가 분열 준비를 하면 더욱 단단히 꼬아지면서 광학 현미경으로 관찰할 수 있는 염색체 구조를 만들어낸다.

</aside>

CpG 영역의 메틸화는 보편적인 유전자 발현 조절 기전으로 <s>유전체 각인</s>과 관련된 기전으로 잘 알려져 있다. 부모로부터 물려받는 한 쌍의 대립 유전자 중에서 어느 하나를 침묵시키는 것은 CpG 영역의 메틸화에 의해 결정된다. 그 밖에도 환경적 영향에 따라 후천적으로 CpG 영역이 메틸화가 되면 해당 유전자는 발현이 일시적으로 중단된다.[@Jang2017-wr]

<aside>

**유전체 각인 (Genomic imprinting)**: 인간은 부모로부터 하나 씩의 상동 염색체를 물려받기 때문에 모든 유전자는 한 쌍의 대립유전자로 존재한다. 한 쌍의 유전자 중 어느 하나만 기능을 하고 나머지는 침묵하게 되는데, 이러한 결정이 유전자가 어머니, 아버지 중 누구에게서 비롯되었느냐에 따라 결정되는 것을 유전체 각인이라 한다. 예를 들어 정자에 있는 Igf2 유전자는 CpG 메틸화가 되어 기능을 하지 않는 반면, 난자에 있는 Igf2는 메틸화 되지 않는다. 따라서 예외없이 어머니로부터 물려받은 Igf2 만 기능하게 된다.

</aside>

한편 히스톤 단백질은 DNA가 염색질 구조로 존재할 수 있게 하는데 가장 중요한 역할을 하는데, 그 자신이 메틸화, 아세틸화, 유비퀴틴화 등 공유결합이 추가될 수 있다. 이렇게 공유결합이 변경되면, 히스톤의 3차원 구조가 바뀜으로써 염색질이 꼬이는 정도를 느슨하게도 팽팽하게도 변화시킬 수 있다. 예를 들어 히스톤 복합체 구성 요소 중 하나인 histone H3의 4번째 lysine이 메틸화되면 염색질이 느슨해지면서 유전자 발현이 촉진되지만, 동일한 히스톤의 9번째 혹은 27번째 lysine이 메틸화되면 반대 방향의 효과가 나타난다.[@Peterson2004-bz] 반대로 염색질이 팽팽하게 꼬이면 전사의 정도가 줄어들기 때문에, 이를 통해 유전자 활성을 조절할 수 있다.[@Wei2017-py]

![Epigenetic modification\
Retrieved from [What is epigenetics](https://www.whatisepigenetics.com/histone-modifications)](images/02-02/img_0.png){#fig:epigenetics}

현재까지 가장 활발히 연구된 후성 유전학적 조절은 위에 설명한 두 가지 기전에 의한다. 비코딩 DNA는 세포핵막 (nuclear envelope), 핵공 (nuclear pore) 혹은 핵소체(nucleolus)에 맞닿아 있는 채로 존재한다.[@Mekhail2010-nu] 이들이 외부로부터의 신호를 받아들이는 감지기 역할을 한다. 신호가 감지되면 후성 유전학적 기전에 따라 세포핵 내에 위치한 코딩 DNA와 이를 둘러싼 히스톤의 공유결합 변화를 불러일으킨다. 이러한 복잡다단한 조절 기전이 알려지면서, 세포핵과 그 안에 포함된 염색질이 단순한 정보 저장소가 아니라, 세포의 기능과 필요성에 따라 역동적이고 민첩하게 단백질 생성을 조절하는 고도로 특화된 기능적 단위라는 것이 명백해졌다.[@Qureshi2010-wf] 한가지 더 주목할만한 것은, 후성 유전학적 변화의 일부는 세대를 건너 유전될 수 있다는 점이다. 이는 DNA 염기서열을 통하지 않고도, 부모 세대의 경험이 자손 세대로 물려내려갈 수 있는 또 하나의 경로가 된다.[@Lacal2018-wk]

## 2-3. 후성 유전학과 조현병

후성 유전학과 조현병의 연관이 제기된 최초의 계기는 2차 대전 당시 나치에 의해 출입이 봉쇄되어 오랜 기간 동안 심한 기근을 겪어야만 했던 네덜란드 산모에 대한 연구였다.[@Kirkbride2012-od] 기근이 가장 심했을 때 수정된 아이들은 기이하게도 이후 조현 스펙트럼 장애의 발생률이 유달리 높았다.[@Brown2008-tf] 연구자들은 산모의 엽산(folic acid) 부족 가능성에 주목했는데, 그 이유는 엽산이 DNA 메틸화에 사용되는 메틸기의 주요 공급원이기 때문이다. 이때 태어난 집단이 장년이 되었을 때 DNA 메틸화 정도를 조사했는데, 몇가지 중요한 유전자에서 메틸화의 정도가 대조군과 다르다는 것이 발견되었다.[@Heijmans2008-mz]

2000년대 후반부터는 당시 취약 유전자로 알려진 몇몇 유전자의 메틸화 정도를 대조군과 비교해보려는 연구가 있었다. Reelin (RELN), catechol-O-methyltransferase (COMT), serotonin receptor type-2 (HTR2A) 등의 메틸화가 대조군과 의미있게 차이가 있었으며, 그 정도는 단백질 발현 양과도 상관관계를 보였다.[@Abdolmaleky2008-ia][@Abdolmaleky2014-aq] 좀더 현대에 접어들면서는 개별 후보 유전자가 아니라, 광범위 유전체 연합 연구의 기법을 동원하여 게놈 전반에 퍼져있는 다량의 CpG 영역을 한꺼번에 조사하기 시작하였다. Wockner 등​[@Wockner2014-vr]**​**은 각 24명의 조현병 환자와 대조군의 사후 뇌조직에서 무려 500,000개 가까운 CpG 영역의 DNA 메틸화 정도를 측정하였다. 그 결과 3,000개 정도의 유전자에서 메틸화의 변화를 감지했는데, 여기에는 기존에 조현병의 취약 유전자로 알려진 유전자들이 대거 포함되어 있었다.

후성 유전학적 조절은 각 장기와 조직마다 다르기 때문에, 뇌 조직의 변화가 혈액에서 나타나는 변화와 동일할 수는 없다. 그러나 살아있는 환자의 뇌 조직을 검사할 수는 없기 때문에, 연구자들은 혈액 내의 후성 유전학적 지표들을 탐색하기 시작하였다. 다행히 뇌 조직과 혈구 세포에서의 후성 유전학 지표 중에 공통되는 부분이 있었기 때문에, 환자의 말초 혈액을 이용하여 개개인의 후성 유전학적 시그니처를 얻어낼 수 있다. Aberg 등**​**[@Aberg2014-bz]**​**은 759명의 환자와 738명의 대조군으로부터 얻어낸 후성 유전학적 시그니처를 서로 비교하였는데, 신경세포의 분화와 도파민 유전자 발현에 관여하는 FAM63B 유전자가 가장 두드러진 차이를 보였으며, 이외에도 RELN을 비롯한 다양한 유전자들이 두 군 간에 유의한 차이를 드러내었다.

비코딩 RNA 역시 전사된 다른 RNA를 분해하거나 번역을 방해함으로써 유전자 발현을 조절할 수 있다. 이중 <s>microRNA</s>는 중수신경계의 정상적인 발달과 성숙, 성인이 된 이후의 신경가소성이나 시냅스 기능에 중요한 역할을 한다. 조현병과 관련해서도 신경세포에 분포하는 miR-132/212, miR-219, miR-195 등이 대조군과 의미있는 차이를 보인다.[@Mellios2012-sy] 말초 혈액의 miRNA 농도를 측정한 실험에서도 miR-130b와 miR-193-3p가 조현병 환자에서 의미있게 변화된 것이 발견되었다.[@Wei2015-be]

<aside>

**MicroRNA (miRNA)**: 약 19\~23개의 염기로 구성된 작은 RNA로 코딩 RNA의 3'-UTR 영역에 결합함으로써 코딩 RNA의 번역을 방해한다. 현재까지 알려진 miRNA의 70%는 중추신경계에서 발견되었으며, 신경세포의 분열, 분화, 성숙, 이동, 세포사 등에 관여한다.

</aside>

![Mechanism of Epigenetic Regulation\
Adapted from [@smigielski2020]](images/02-02/img_1.png){#fig:epigenetic-mechanism}

조현병 환자의 히스톤 단백질 구조 변화에 대한 연구는 상대적으로 수가 적다. Chase 등**​**[@Chase2013-yj]**​**은 조현병 환자의 사후 뇌조직은 물론 말초 백혈구에서 histone H3의 9번째 lysine 메틸화가 대조군과 차이가 있음을 보고하였다. 한편 또 다른 연구에서는 조현병 환자의 말초 혈액에서 H3의 10번째 serine의 인산화 정도가 증가되었음이 관찰되었다.[@Sharma2015-wi]

## 2-4. 후성 유전학적의 한계와 전망

세포의 기능이 단백질 발현의 양에 달려있다고 지극히 단순화시킨다 해도, 단백질 생성의 양을 조절하는 기전 또한 한없이 복잡하고 다양하다. 유전자 발현은 시시각각 달라지는 세포 외 환경에 대응하여 순발력 있게 변화하며, 이는 세포막 수용체와 세포 내부의 정교한 신호전달 네트워크의 역할에 달려있다. 항정신병 약물의 기전을 비롯하여, 질병의 병태생리와 치료기전을 이해하려는 수많은 연구자들은 이 신호전달 네트워크를 이해하기 위해 부단한 노력을 기울여왔다. 그러나 신호전달계를 통한 변화는 비교적 짧은 시간 범위에서 일어나는 것이기 때문에, 뇌 신경망의 구조적 변화와 같이 상대적으로 긴 시간 범위에서 일어나는 현상을 이해하기에는 한계가 있다.

오랜동안 학자들은 구조의 변화를 가져올 정도로 장기간 유지되는 변화는 염기서열의 변이에 의해서만 일어난다고 생각해왔다. 정신유전학은 이런 전제하에 발전해왔으며, 다양한 취약성 유전자를 발견해내는 성과를 이루었다. 그러나 조현병에 높은 빈도로 존재하는 변이 중 상당 수는 비코딩 DNA에 위치하고 있으며, 그 역할을 이해하기 어려웠다. 단백질 발현에 영향을 미치지 못하는 유전자 변이란 의미없는 변이에 불과하기 때문이다.

한편 환경적 영향 역시 이해하기 어렵기는 마찬가지이다. 물론 세포내 신호전달계는 환경적 변화를 감지하고 이에 대응하여 단백질 발현 양을 조절한다. 그러나 구조적 변화를 일으키거나, 발병을 유도할 정도로 스트레스의 영향이 장기간 유지되기 위해선, 신호전달계의 동적 변화만 갖고는 설명하기 어렵다. 후성 유전학은 이러한 두 가지 의문점에 해답을 제공할 가능성을 지니고 있다. 비코딩 DNA 중 상당 부분은 후성 유전학 조절 기전, 즉 유전자 스위치를 켜고 끄는데 관여하고 있다. 비코딩 DNA의 변이 때문에 후성 유전학적 조절 기전이 손상되거나, 혹은 특정 유전자가 장기간 억제되거나 혹은 탈억제 되면 장기간에 걸쳐 코딩 DNA의 발현이 변화되면서 발병/재발을 유도할 수 있을 것이다. 환경적 영향 역시 마찬가지이다. 스트레스가 후성 유전학적 기전에 의해 특정 유전자 발현을 장기간 억제한다면 구조적 변화에 이를 수 있을 것이다. 예를 들어 동물 실험 결과에 따르면, 갓 태어난 새끼 쥐는 엄마의 보살핌 정도에 따라 GAD1 유전자 프로모터 영역의 DNA 메틸화가 달라지며, 더불어 성인이 되었을 때에도 히스톤의 아세틸화 정도가 달라진 채로 유지된다고 한다.[@Zhang2010-tx] 인간을 대상으로 한 연구에서는, 자살자의 사후 뇌조직에서 스테로이드 수용체 유전자인 NR3C1 프로모터 영역의 DNA 메틸화를 조사했을 때, 아동기의 학대 여부와 연관되어 있음이 발견되었다.[@McGowan2009-pq]

하지만 동일한 의미에서 후성 유전학적 설명도 한계에 부딪힌다. 우선 후성 유전학적 변화가 얼마나 오랜 시간 안정적으로 유지되는 지에 대한 자료가 매우 부족하다. 이 역시 세포 외 상황에 적응하여 동적으로 변화되는 것이기 때문에, 성향(trait)을 반영한다기 보다는 상태(state)를 반영한다고 보아야 한다. 지금까지의 연구 중 대부분이 단면조사 연구(cross-sectional study)였기 때문에, 후성 유전학적 기전의 변화 양상에 대해서는 거의 아는 바가 없다. 일례로 해마에서의 DNA 메틸화는 탈분극 정도에 반응하여 변화하는데, 그렇다면 시간적 척도가 세포내 신호전달계와 별다를 바가 없다.[@Nelson2008-cs]

한편 대조군과 환자군 사이에서 DNA 메칠화 정도나 히스톤 단백질의 인산화 정도가 다르다는 것을 발견했다고 해도, 이를 어떻게 해석해야 할 지에 난점이 많다. 이러한 변화가 발병 과정과 관련된 것인지, 오래된 병의 결과인 것인지, 혹은 항정신병 약물에 의한 것인지 전혀 구분되지 못하고 있다. 설령 치료받지 않은 초발 정신병 환자를 대상으로 삼아, 이러한 변인을 배제할 수 있었다해도, 후성 유전학적 변화가 비코딩 DNA의 변이에 의한 것인지, 축적된 환경적 요인에 의한 것인지 구분할 방법이 존재하지 않는다. 만약 전자에 의한 것이 맞다면, 광범위 유전체 연합 연구와 차별되는 장점이 무엇인지도 확실하지 않다.

그럼에도 불구하고, 후성 유전학적 연구는 많은 가능성을 내포하고 있다. 지금까지 보편적으로 알려진 유전자 발현의 조절은 유전자 인근의 제한된 영역의 DNA에 의한다고 여겨져 왔다. 넓게 잡아 5'-UTR (5'-untranslated region)이라고 해도 몇 천 bp에 불과하다. 후성 유전학적 기전의 하나인 DNA 메틸화는 5'-UTR 내에 존재하는 CpG 영역에서 일어나지만, 히스톤 변형을 비롯한 다른 종류의 후성 유전학적 기전은 염색질의 구조 자체를 변화시키기 때문에, 훨씬 원거리 영역에서도 코딩 유전자의 발현을 조절할 수 있다.[@Wood2010-ir] 이러한 원거리 조절의 가능성은 비코딩 유전자 변이의 역할을 이해하는데, 큰 기여를 할 것으로 기대된다.

현재까지 후성 유전학적 기전에 의해 일어난다고 확인된 정신과 질환은 <s>취약 X 증후군</s>과 <s>레트 증후군</s> 등 주로 정신지체를 일으키는 다양한 질환이 있다. 예를 들어 취약 X 증후군에서는 FMR1 (fragile X mental retardation 1) 유전자 프로모터에 변이가 있어서, 환자들은 CpG 영역에 염기서열 CGG가 지나치게 많이 반복된다. CG가 많으면 많을 수록 DNA 메틸화 정도가 심해지기 때문에, 환자들은 FMR1 단백질이 만들어지지 못하게 되어 발병에 이른다. 레트 증후군은 여성에게 주로 나타나는 신경 발달 장애로 X 염색체에 존재하는 MeCP2 유전자 변이에 의해서 초래된다. MeCP2는 CpG 영역의 메틸화된 DNA에 결합하여 다양한 유전자의 발현을 억제하는 역할을 한다. [@Good2021-dr] 이 밖에도, MeCP2는 히스톤 H3의 27번째 lysine을 메틸화시키기 때문에 히스톤 변형을 통한 염색질 구조 변화에 관여한다.[@Lee2020-ja] 따라서 MeCP2에 변이가 생기면 많은 수의 유전자 발현이 혼란에 빠진다. 특히 MeCP2는 신경세포가 성숙을 마친 이후에 대량으로 만들어지며, 이는 레트 증후군의 증상이 생후 6-18개월 지난 후에야 나타나는 것과 무관하지 않다.

<aside>

**취약 X 증후군 (fragile X syndrome)**: 희귀한 유전 질환으로 정신지체의 가장 흔한 원인 중 하나이다. X 염색체의 말단인 Xq27-Xq28 부위가 끊어질듯 말듯 보이기 때문에 이렇게 이름붙여졌다.

**레트 증후군 (Rett syndrome)**: Andreas Rett에 의해 처음으로 보고된 신경발달장애. 생후 6개월에서 18개월까지는 비교적 정상 발달을 한 후 두위 발달의 감소와 함께 이미 습득했던 인지 및 언어, 운동 능력을 상실하고, 손을 씻는 듯한 동작을 반복하는 상동증을 보인다.

</aside>

한편 후성 유전학적 지표는 세대를 넘어서 유전된다는 특징이 있다. 앞서 기근에 빠진 산모에게서 태어난 아이들이 나중에 조현병으로 발병하는 예가 많았다는 것을 살펴보았다. 이는 신경발달학적 가설로 이해하여 태생기 뇌 발달 과정에 산모의 영양 부족이 영향을 끼쳤다고 볼 수 있지만, 후성 유전학적으로는 좀 다르게 해석할 수 있다. 즉 기근에 처한 주민들은 남녀 가릴 것 없이 기근에 적응하기 위해 후성 유전학적 기전을 사용하여 몇몇 유전자 발현을 조절하고 있었는데, 이러한 휴성 유전학적 지표가 정자와 난자를 통해 자손에게 그대로 물려내려갔을 수도 있다. 이를 확장하면 부모 대의 극심한 스트레스(예를 들어 전쟁이나 이민)가 자손의 조현병 발병 확률을 높일 수도 있다는 추론이 가능해진다.[@Lacal2018-wk]

후성 유전학은 아직도 초창기에 머물러 있는 생소한 학문인지라, 알려진 것보다는 아직 알지 못한 부분이 훨씬 많다. 따라서 조현병의 병태생리를 이해하는데 도움이 될 지 안 될 지 조차 분명하지 않다. 그러나 후성 유전에 기인한다고 알려진 질환의 병태 생리적 기전을 이해함으로써, 조현병의 발병 기전, 특히 심리적 스트레스가 발병을 앞당기는 이유, 청소년기 후기에 들어서야 발병에 이르는 이유, 그리고 부모 세대의 스트레스가 자손의 발병 위험에 미치는 영향 등을 밝히는데 도움이 되기를 희망한다.
