---
title: '2장 12절: 언어와 조현병'
description: Language and Schizophrenia
bibliography: references/02-12.bib
link-citation: yes
---

<a href="article-02-11.html"><i class="arrow far fa-arrow-alt-circle-left"></i></a>

DSM-5는 조현병의 진단 기준 중 하나의 항목으로 와해된 언어(disorganized speech)를 포함하고 있다. 단순히 망상을 갖고 있는 것과 언어가 와해된 것은 다르다. 비정상적 생각을 하더라도 이를 온전한 언어로 표현한다면, 이는 사고 내용(content)의 이상이라고 할 지언정 사고 형태(form)의 이상이라고 하지 않는다.[**(Jerónimo et al. 2018)**](https://paperpile.com/c/L64Dvp/XwVvQ) 따라서 사고의 내용과는 독립적으로 언어적 표현의 형태 자체가 조현병을 진단하고 또 이해하는 단서가 될 수 있다.

조현병을 이해하고자 하는 연구자들이 그들의 언어를 바라보는 관점은 크게 세가지로 나눌 수 있다. 첫번째는 언어는 생각하는 바를 그대로 전달해주는 매체일 뿐이라는 관점이며, 둘째는 환자들의 언어에서 언어학적으로 추출된 특징(linguistic characteristics)을 통해 진단이나 병세 평가에 도움을 받을 수 있다는 것, 셋째는 신경회로의 붕괴로 인해 언어의 문법적 구조가 일차적으로 무너지면서, 망상 및 사고장애가 뒤이어 생긴다는 관점이다.

### 12-1. 사고를 반영하는 매체로서의 언어

이는 가장 고전적인 관점이다. 1944년 Kasanin (NOTE: Jacob S. Kasanin (1897\~1946): 러시아 태생의 미국 정신과 의사. 조현정동장애를 구분해낸 것으로 유명하다.)이 "조현병의 언어와 사고(Language and Thought in Schizophrenia" 라는 책을 펴낸 무렵부터 이미 와해된 언어는 그 밑에 깔려있는 와해된 사고에서 비롯된다고 믿어졌다. 이는 조현병 환자가 보이는 언어와 브로카(Broca's aphasia) 혹은 베르니케 실어증(Wernicker's aphasia) 환자가 보이는 언어가 확연히 차이가 나는 것을 통해 엿볼 수 있다.[**(Gerson, Benson, and Frazier 1977)**](https://paperpile.com/c/L64Dvp/ENBE6) 언어중추 자체에 손상을 입으면 언어의 표현 혹은 이해가 불가능해지면서 지리멸렬해지지만, 조현병 환자의 지리멸렬함은 이들 실어증의 경우와 차이가 있다.

따라서 환자들의 언어를 분석하고자 했던 초기 학자들은 생각을 언어로 바꾸는 과정 자체에는 문제가 없다고 잠정적으로 가정하고, 모든 이상을 형식적 사고 장애(formal thought disorder, FTD)의 탓으로 돌렸다. 야스퍼스는 사고의 흐름을 앞의 생각과 뒤의 생각이 연상(association)의 고리로 이어지는 과정으로 시각화하였고, 조현병 환자의 사고를 이러한 연상의 고리가 느슨해진 것으로 이해하였다. 블로일러는 야스퍼스의 견해를 받아들여 기본 증상(4A 증상)에 연상의 이완을 포함시켰다. 초기 이론가들은 연상의 이완 이외에도 형식적 사고 장애를 특징짓는 핵심 법칙을 밝히고자 애썼는데, 대표적인 예가 von Domarus의 원칙 (NOTE: Elihard von Domarus에 의하면 조현병 환자들은, 두 사물의 특성 중 몇 가지가 같으면, 두 사물을 동일한 것으로 여기는 경향이 있다.[**(von Domarus 1944)**](https://paperpile.com/c/L64Dvp/R9nL) 아리에티는 블로일러가 치료했던 한 환자의 예를 든다. 그는 자신도 2차 대전을 혐오하며, 스위스도 2차 대전을 혐오했기 때문에, 자신은 곧 스위스라고 주장하였다.[**(Arieti 1974)**](https://paperpile.com/c/L64Dvp/rdT9)), Goldstein이 주장한 구체적 사고 (NOTE: 구체적 사고(concrete thinking): Kurt Goldstein에 의하면 신경학적 손상으로 언어장애를 앓는 환자 중에서, 사물의 이름을 추상적 개념보다는 구체적 사물에 붙이는 경향을 발견할 수 있다고 하였다. 조현병 환자 역시 이런 경향이 발견되며, 속담풀이나 사물의 공통점 찾기 등에서 수행을 제대로 하지 못한다.[**(Goldstein 1944)**](https://paperpile.com/c/L64Dvp/dVNc)), Cameron이 강조한 지나치게 포괄적인 사고(overinclusive thinking) (NOTE: 지나치게 포괄적인 사고(overinclusive thinking): Cameron에 의하면 조현병 환자들은 추상적 개념의 경계가 모호해서 피상적인 유사성 밖에 없는 개념도 동일한 범주에 포함시킨다. 예를 들어 환자에게 "초등학생, 중학생, 고등학생, 유학생"에서 나머지 셋가 동떨어진 개념을 골라내라고 하면 잘 골라내지 못한다. [**(Cameron 1944)**](https://paperpile.com/c/L64Dvp/DS5A)), Arieti (NOTE: Silvano Arieti (1914\~1981): 이탈리아 태생의 미국 정신과 의사. 1970년대 이전까지 조현병의 최고 권위자로 일컬어져 왔으며, 1955년 펴낸 "조현병의 이해(Interpretation of Schizophrenia)"는 당시까지 축적된 조현병에 대한 지식을 총망라한 책으로 지금까지도 정신의학의 고전으로 알려져 있다.)의 고태적 사고(paleological logic) (NOTE: 고태적 사고(paleological logic): 논리적 사고의 출현을 알리는 아리스토텔레스의 삼단 논리가 등장하기 전, 유사 이전 시대의 논리 형태. 어린아이의 초기 발달단계에서 혹은 전설, 민담, 미신, 토속 신앙 등에서 찾아볼 수 있다. 어린아이는 성장하면서 고태적 사고에서 벗어나게 되나, 조현병과 같이 퇴행하게 되면 다시금 등장한다. 아리에티가 붙인 이름이다.) 등이다.

Kasanin에서 Arieti에 이르기까지, 조현병 환자가 보이는 언어는, 그 밑에 깔린 형식적 사고 장애를 드러내는 증거로서 받아들여졌고, 연구자들은 이러한 사고를 특징짓는 핵심적 논리의 오류를 찾고자 하였다. 그러나 언어가 사고의 충실한 반영이라는 견해는 어디까지나 잠정적 전제였을 뿐, 확인된 진실은 아니다. 언어를 획득하지 못한 청각장애인도 거의 정상적으로 사고하며, 기이한 망상을 갖고 있는 환자가 자신의 망상을 유려한 문장으로 묘사해놓기도 한다. 이에 조현병 환자의 핵심 병리를 사고 장애로 이해해야 할 지, 언어 장애로 이해해야 할 지 점점 논란이 가열되었다.

### 12-2. 사고 장애와 독립된 언어 장애

Chaika**​[(Elaine Chaika 1974; E. Chaika 1982)](https://paperpile.com/c/L64Dvp/o2tow+yRUxH)​**는 조현병 환자의 언어를 형식적 사고 장애의 반영이 아니라 순수히 언어 사용의 장애로 보았다. 그녀는 조현병 환자의 언어 특성은, 1) 적절한 단어를 사용하지 못하고, 2) 주제와 관련없는 음성이나 의미로 인해 주의가 분산되면서 자꾸 맥락에서 벗어나며, 3) 문법이 붕괴되는 것이라 하였다. 이에 덧붙여 궁극적으로는 환자가 자신의 언어가 비정상적이라는 것을 인식하지 못하는 것이라고 하였다. 즉 형식적 사고 장애가 없더라도 병적인 언어 사용을 관찰할 수 있다는 뜻이다.

Andreasen은 1979년에 발표한 논문에서 연상의 이상에 국한된 블로일러식 사고 장애 개념이 한계에 봉착했음을 지적하면서, 조현병의 형식적 사고 장애를 1) 의사소통 장애, 2) 언어학적 장애, 3) 형식적 사고 장애로 나누는 것을 제안하였다.[**(Andreasen 1979)**](https://paperpile.com/c/L64Dvp/NKPwl) 이 즈음부터 언어 장애와 사고 장애는 분리되기 시작하였다. 더군다나 언어를 통하지 않고 환자의 생각을 직접 들여다볼 수는 없기 때문에, 사고 장애보다는 언어 장애가 더 중요시되었다. 이러한 추세를 받아들여, DSM-IV는 조현병의 진단기준 중에서 이전에 사용하던 "사고 장애"를 "와해된 언어"로 바꾸었다.

현대의 연구자들은 사고 장애와 언어 장애 중에서 양자 택일하는 관점에서 벗어나, 환자들이 보이는 언어의 이상은 두 가지 장애가 섞여있기 때문이라고 생각한다. 전자(사고 장애)에 대해서는 집행 기능의 역할이 강조되어, 환자가 자신이 하고 있는 생각과 말을 제대로 모니터링 하지 못하기 때문에 연상의 이완이 발생한다고 본다. 후자(언어 장애)는 생각을 말로 표현하는 단계에서의 기능 장애를 가리키며, 단어를 선택하여 정해진 문법에 맞춰 문장으로 만들어내며, 대명사의 사용, 수식구의 첨가 등을 통해 상대방도 이해할 수 있는 의사소통을 이뤄내는 제반 과정에 문제가 생기는 것이다. 조현병 환자가 보이는 순수한 형태의 언어 장애를 "schizophasia"라고도 하는데, 이는 좁은 의미에서는 단어 범벅(word salad)을 가리키지만, 넓은 의미에서는 지리멸렬한 언어 정도의 의미로 쓰인다.[**(Covington et al. 2005)**](https://paperpile.com/c/L64Dvp/OcTzF)

인간의 언어 자체가 진화론적으로 후대에 나타난 산물이고, 다양한 인지 기능들이 매우 복잡하고도 다층적인 구조로 얽히면서 형성된 구조이기 때문에 이를 체계적으로 분석하는 것은 쉬운 일이 아니다. 언어학에서는 언어 구조를 음성학/음운론(phonetics/phonology), 형태론(morphology), 통사론(syntax), 의미론(semantics), 화용론(pragmatics) 등으로 나누어 분석한다. Covington 등**​[(Covington et al. 2005)](https://paperpile.com/c/L64Dvp/OcTzF)​**은 조현병에서 나타나는 언어론적 이상을 간략하게 요약하였다. 그들에 따르면 음성학/음운론 측면에서는 큰 이상을 보이지 않으며, 억양이나 목소리 등에 이상이 있을 수 있지만, 이는 무의욕, 무감동 등에 의한 2차적인 것으로 생각된다. 마찬가지로 단어 형태를 왜곡하는 형태론적 문제도 드문 편이다. 문법의 경우 두드러진 이상이 나타나진 않으나, 복잡한 문법이 사용되는 빈도가 줄고 대부분 단순한 문법적 표현으로 대체된다. 이렇게 문법적 복잡성이 감소하는 것은 음성 증상 및 질병의 만성화와 상관관계가 있다.[**(Thomas 1996)**](https://paperpile.com/c/L64Dvp/6qOFs)

본격적으로 문제가 드러나기 시작하는 것은 의미론부터이다. 의미론적 차원에서 정상적인 언어가 가능하려면, 개념(혹은 사물)과 이를 표상하는 상징(혹은 단어)가 정확히 연결되어야 한다. 인간은 언어로 사고하기 때문에, 개념과 상징과의 연결은 언어 표현 뿐만 아니라 정상적인 사고를 위해서도 중요하다. 그러나 환자들은 정상적 단어를 비정상적 개념을 표현하기 위해 사용하거나, 정상적 개념을 비정상적 (신어조작증에서처럼) 단어로 표현한다. 한 개인의 머리 속에서 단어들은 의미론적 네트워크(semantic network)로 존재한다. 한 단어가 활성화되면, 그것과 의미가 연결되어 있는 단어 역시 자극된다. 이렇게 자극이 퍼져나가는 범위가 너무 적으면, 단어 사용이 경직되거나 적절한 단어를 찾아내지 못하여 엉뚱한 단어를 사용하게 된다. 반대로 범위가 너무 넓어지면, 사고의 비약과 같이 개념과 개념 사이의 구분이 옅어지면서, 환자 자신만이 이해할 수 있는 독특한 의미로 단어를 사용하게 된다. 조현병 환자는 의미론적 네트워크가 붕괴되어 있으며, 편집형 환자보다 파과형 환자에게서 더욱 와해 정도가 심하다.[**(Paulsen et al. 1996)**](https://paperpile.com/c/L64Dvp/CqtmT)

그러나 뭐니뭐니 해도 조현병의 병리가 확연하게 드러나는 것은 화용론이다. 화용론이란 현실 세계에서 언어를 통해 의사소통을 이루는 것을 가리키며, 좀더 구체적으로는 언어를 상황적 문맥에 맞게 사용하는 것이다. 정확한 단어를 정확한 문법으로 구사한다고 해도, 그 말이 현재 상황과 문맥에서 벗어나면 비정상적인 것이다. 한 가지 예를 들면, 앞문장과 뒷문장, 혹은 발화자와 청취자가 번갈아 나누는 문장은 서로 의미적으로 연결되어야 정상적 의사소통에 기여할 수 있다. 문장 A와 뒤따르는 문장 B가 의미적 결속(lexical cohesion)을 이루기 위해선, 다양한 결속 장치(cohesion device)가 적절하고도 정확하게 사용되어야 한다. 이러한 장치에는 참조(reference), 대치(substitution), 생략(ellipsis), 접속(conjunction), 어휘 항목(lexical item) 등이 있다. 조현병 환자들의 언어는 의미적 결속을 제대로 이루지 못하기 때문에, 환자는 자신이 상대가 충분히 알아들을 수 있도록 말했다고 믿지만, 이를 듣는 청취자 입장에서는 연상이 이완되고 지리멸렬한 것처럼 들린다. 또한 환자들은 대명사 사용도 매우 부정확하기 때문에, 청취자는 환자들이 지금 누구에 대해, 무엇에 대해 이야기하는지 파악하기 힘들어한다.[**(Çokal et al. 2018)**](https://paperpile.com/c/L64Dvp/cLg9s)

조현병 환자의 언어 이상은 사고 장애를 들여다보고 핵심 병리를 이해하기 위해서도 사용되지만, 그 자체로서 진단적 목적으로 사용되거나 생물학적 연구를 위한 내적 표현형으로 이용되기도 한다. de Boer가 이끄는 연구진은 수년간에 걸쳐 전산 언어학적(computational linguistic) 방법을 동원한 자동화 언어분석을 통하여, 환자들의 언어 이상을 정량화해왔다. 그들은 이렇게 얻어진 자료가 진단에 기여하며, 백질내 신경경로 등 생물학적 이상과 관련지을 수 있다고 주장한다. [**(de Boer et al. 2018, 2020)**](https://paperpile.com/c/L64Dvp/Ui9GF+x9CBL) 다른 연구자들 역시 기계학습, 자연어 처리, 딮 러닝 등 인공지능 기법등을 적용한 언어분석을 통해, 환자를 가려내거나, 재발을 감지하고, 사고 장애를 정량화하는데 성공하고 있다.[**(Rezaii, Walker, and Wolff 2019; Corcoran et al. 2020; Hitczenko, Mittal, and Goldrick 2020)**](https://paperpile.com/c/L64Dvp/Xgu25+6i5uZ+GYtG1)

### 12-3. 사고 장애의 근본 원인이 되는 언어 장애

다른 정신질환도 마찬가지이겠지만 조현병은 인간에 국한된 질병이다. 물론 조현병의 동물모델이 없는 것은 아니지만, 동물모델이 진정 조현병과 동일한 지는 누구도 보장할 수 없다. 인간과 그 밖의 동물이 차이가 나는 점은 첫째 자의식이 있다는 것 그리고 둘째 언어를 사용한다는 점이다. 따라서 만약 인간에게 언어가 없다면 조현병이 생겼을 것인가하는 질문을 던져볼 수 있다. 특히 형식적 사고 장애라는 측면은, 언어가 없이는 상상하기 매우 곤란하다.

생각이 먼저냐 언어가 먼저냐는 질문은 마치 닭이 먼저냐 달걀이 먼저냐는 질문과 마찬가지로 언뜻 간단해보이지만 쉽사리 풀리지 않는 질문이다. 분명 비언어적 사고도 존재하기 때문에 생각이 먼저임에 틀림없는 듯 보이지만, 생각이 언어의 굴레를 벗어나기 힘들다는 점에서 언어가 앞서있는 것 같기도 하다. 1916년, 언어학자인 소쉬르 (NOTE: Ferdinand de Saussure (1857\~1913): 스위스의 언어학자로 근대 구조주의 언어학의 창시자라 불리운다. 그는 언어 세계를 랑그(langue)와 파롤(parole)로 나눈다. 파롤은 개인이 언어에 의미를 담아 실제 의사소통에 사용하는 행위를 가리키는 반면, 랑그는 이를 가능하게 해주는 추상적 구조라고 했다. 그의 사후에 제자들이 강의록을 모아 "일반 언어학 강의(Cours de linguistique générale)"라는 제목으로 출판하였다.)의 저서 "일반 언어학 강의(Course in General Linguistics)"가 출간된 이후, 20세기 말까지 구조주의 및 후기 구조주의의 열풍이 불었다. 레비-스트로스 (NOTE: Claude Lévi-Strauss (1908\~2009): 프랑스의 인류학자. 사회와 문화를 이해하는 방법으로 구조주의를 개척하였다. 그는 모든 사회관계나 사회적 행위가 개념적 대립쌍들에 의해 구조화 된다고 보았는데, 이는 언어와 언어행위에서도 동일하게 발견된다고 하였다. 그는 구조주의 언어학자인 Roman Jacobson의 영향을 받아 언어구조를 이해하는 것은 사회구조를 지배하는 법칙을 이해하는 것과 같다고 보았다)에 의해 언어가 어떤 식으로 인간의 사고와 실제 생활을 구속하는지가 분명해졌다. 이를 인간 무의식에 응용한 라캉은 무의식이 언어와 마찬가지의 구조로 되어있으며, 은유와 환유라는 언어적 법칙이 의식과 무의식을 점령하고 있다고 주장하였다.

20세기 후반의 서양철학을 대표하는 이들 이론은 언어가 사고보다 앞서있음을 강조하고 있다. 이를 그대로 조현병에 적용하면, 복잡하기 그지없는 의미론적, 문법적 질서가 붕괴되면서, 환자는 비정상적인 사고를 하게 된다고 해석할 수 있다.[**(Wróbel 1990)**](https://paperpile.com/c/L64Dvp/a0MlZ) 이는 언어는 사고 장애의 반영일 뿐이라는 고전적 견해를 뒤집은 것이다. 몇몇 연구자들은 환자들이 언어를 갖고 마치 장난감처럼 유희하고 있으며, 문법적으로는 문제없지만 현실과 동떨어진 문장을 만들어내면서 그것을 실제와 착각하고 있다고 말한다.[**(Goss 2011)**](https://paperpile.com/c/L64Dvp/U5VQy)

예를 들어 "Mafia tries to kill ***him***"이라는 명제는 망상이라 할 수 없다. 그러나 단순히 "him"이라는 대명사를 "*me*"로 바꾸어 "Mafia tries to kill ***me***"라고 말하면 이는 망상이 되어버린다. 대명사가 지칭하는 대상만 바뀌었을 뿐인데, 멀쩡한 문장이 망상이 되어버리는 것이다. 문법이 정확히 구분하지 못하는 애매모호한 문장이 망상을 유발할 수도 있다. "***I*** am a human like ***you***"는 말은 의미해석에 아무 문제가 없다. 그러나 "***I*** am ***not*** a human like ***you***"라고 하면, 사람같지 않은 것이 *나* 혼자를 말하는 것인지, *나*와 *당신*을 말하는 것인지 애매해진다. 환자들은 이런 애매모호함 속에서 자신의 정서에 부합하는 의미를 임의로 선택해버린다.[**(Hinzen and Rosselló 2015)**](https://paperpile.com/c/L64Dvp/o9ZbU) 앞서 환자들이 문법적으로 복잡한 구조를 자꾸 생략해버린다고 지적한 바 있다. 그런데 "I ***may*** be a God"이라는 문장에서 may를 생략해버리면, "I am a God"이 되어버리면서 영낙없이 망상이 되어버린다. 환청의 경우에 어떤 말소리가 머리 속에서 울리면, 환자는 언어적 습관 때문에 자연스레 말을 하는 발화자(speaker)와 이를 듣는 청취자(listener, 여기서는 환자 자신)를 구분하기 시작한다. 현실에서는 발화자가 동시에 청취자이지만 문법에서는 엄연히 나와 너가 구분되기 때문에, 환자들은 발화자에 해당하는 가상의 존재를 만들어내고, 그가 바로 피해망상 속의 가해자라고 믿어버리게 된다.[**(Hinzen and Rosselló 2015)**](https://paperpile.com/c/L64Dvp/o9ZbU)

이런 예들을 살펴보면, 조현병에서 나타나는 사고 장애의 형식이 언어의 근본 구조와 따로 떼어 생각할 수 없음을 보여준다. 언어와 현실의 관계는 그다지 견고하게 밀착되어있지 않다. 소쉬르는 기표(signifier)와 기의(signified)의 연결 관계는 그 어떤 필연성도 없는 순수한 임의적 관계라고 주장하였다. 이 이론에 따르면 의미는 기표와 기표의 대조에서 비롯되며, 문법 등 구조의 지배를 받는 것 역시 기표와 기표의 관계일 뿐이다. 그런데 기의가 기표의 관계들 속에서 떠오르는 허상과 같은 것이라면, 서로 다른 개인들은 모두 자기만의 기이한 정신세계에 빠져들어 의사소통 자체가 불가능해질 위험이 있다.

라깡 (NOTE: Jacques Lacan (1901\~1981): 프랑스의 정신분석가. 무의식의 정신세계를 언어학적으로 탐구하는 데에 몰두하였다. "프로이트로의 회귀"라는 명분으로 독일 중심의 기존 정신분석계에 도전하였으며, 드높은 명성과 함께 그에 못지 않은 비판을 받았다. 무의식이 언어와 같은 구조를 가지고 있다고 주장하였으며, 정신분석가이자 동시에 구조주의 철학자로 인정받는다.)은 이러한 위험을 유려하게 공식화하였다. 그에 따르면 기표와 기표의 관계로만 이루어진 상징계가 우리 정신세계의 대부분을 구성한다. 그런데 상징계에서는 기표를 기의와 연결시켜주는 고리가 자꾸만 느슨해지기 때문에 실제계와 조금씩 동떨어진다고 하였다. (그는 이러한 현상을 "기표는 기의에 닿지 못하고 계속 미끄러진다"고 표현하였다) 이렇게 동떨어지기만 하면 인간은 내내 상상과 상징 세계에 머물러있게 될 것이다. 그러나 정상인은 끊임없이 기표와 실제계에 속해있는 기의와의 연결을 재설정하며, 실제계로부터의 이탈을 막아낸다. 그런데 인간이 실제계를 직접 접하기는 어렵기 때문에, 대신 타인의 기표들과 비교, 점검함으로써 기표와 기의의 관계를 갱신한다. 이를 위해서는 역시 언어를 사용하여 활발한 의사소통을 해야하며, 내 언어의 구조(기표의 구조)를 타인의 담론에 동조시켜야 한다. [**(Dimitriadis 2018)**](https://paperpile.com/c/L64Dvp/TGEU9)

따라서 정상적인 언어 사용에 문제가 생기면, 타인과의 의사소통이 끊어지고, 기표는 더 이상 본래의 기의와 연결될 수 없게 된다. 기의와 분리된 기표들은 의미와는 상관없이 오로지 문법적인 규칙에 의해 다른 기표들과 관계를 맺는다. 이렇게 되면 앞서든 예처럼, "Mafia tries to kill ***him***"이 말이 된다면, "Mafia tries to kill ***me***"도 말이 된다는 식의 논리가 생겨난다.

### 12-4. 언어 능력의 획득과 조현병

1997년에 Crow (NOTE: Timothy John Crow (1938\~): 영국의 정신과 의사. CT를 이용하여 조현병 환자의 뇌실이 커져 있다는 것을 확인한 것으로 유명하다. 또한 조현병을 양성 증상이 주를 이루는 type I과 음성 증상이 주를 이루는 type II로 나누었다.)는 조현병이 호모 사피엔스가 언어 능력을 획득한 대가로 얻게 된 질병이 아니냐는 도전적인 논문을 발표하였다.[**(Crow 1997)**](https://paperpile.com/c/L64Dvp/yA230) 그는 조현병이 분명히 생존과 번식에 불리한 형질임에도 불구하고 오랜 진화과정 동안 사라지지 않았고, 역사나 지역을 막론하고 1% 남짓이라는 일정한 유병률을 보이는 것은, 조현병을 일으키는 유전자가 동시에 생존에 큰 도움이 되는 형질과 연결되어 있기 때문이라고 짐작하였다. 그는 후자의 형질이 다름 아닌 언어기능이라고 주장하였다. 그가 제시한 가설에 따르면, 약 10만년에서 25만년전, 유전자의 중요한 변이가 일어나면서 인간은 좌뇌와 우뇌의 기능을 분리시켰고, 좌뇌는 언어기능을 도맡게 되었다. 언어기능이 좌뇌로 국한되면서 좌뇌와 우뇌의 정보교환이 무엇보다 중요해졌는데, 이는 뇌량(corpus callosum)을 통해 일어난다. 만약 두 대뇌반구의 정보교환에 문제가 생기면, 좌뇌는 우뇌의 감독을 받지 못하고 자신만의 논리에 따라 세상을 이해하게 되는데 이는 정신병적 증상의 근원이 된다.

Crow가 그리고 있는 좌뇌와 우뇌의 기능 분할은 마치 상징계와 실제계의 구분과 닮아보인다. 잘 알려진 것처럼 좌뇌와 달리 우뇌는 시공간적 감각 및 기타 비언어적 감각을 처리하고, 좌뇌의 의식적 결정에 직감과 같은 무의식적인 영향력을 행사한다.[**(Volz and Gazzaniga 2017)**](https://paperpile.com/c/L64Dvp/2k68e) 또한 좌뇌는 시간적 순서에 지배되는 선형적 사고를 하지만, 우뇌는 시간관계를 초월한 비선형적, 평행적 사고를 한다. 따라서 좀더 현실을 입체적이고 정확하게 파악하는 것은 우뇌라 할 수 있다. 어쩌면 우뇌는 자기, 환경 그리고 실제라는 세 가지 차원을 조율하는 역할을 하는지도 모른다. 인간은 예기치 못한 상황에 직면했을 때 우선은 좌뇌의 힘을 빌어 그 전까지 문제없이 작동했었던 기존 모델을 사용하여 어떻게든 설명하려 한다. 이때 우뇌는 이러한 설명이 무언가 실제와 부합되지 않는다는 것을 감지하고, 모델이 잘못되었음을 좌뇌에 전달한다. 이 과정에 문제가 생기면, 좌뇌는 현실과 동떨어진 설명을 별다른 논리적 모순을 느끼지 않고 받아들이게 된다.[**(Sass and Byrom 2015; Gurin and Blum 2017)**](https://paperpile.com/c/L64Dvp/Z1j8G+XS3J9)**​**우뇌 특히 우측 전두엽에 손상을 입은 환자들이 극히 다양한 형태의 망상을 보이는 것은 이런 식으로 설명될 수 있다. [**(Gurin and Blum 2017)**](https://paperpile.com/c/L64Dvp/XS3J9) 우뇌로부터 적절한 피드백을 받지 못한다는 것은, 라깡이 이야기해듯이 기표가 더 이상 기의와 연결되지 못한다는 뜻이 된다. 이 때문에 문법적으로는 이상이 없지만, 상황과 맞지 않고, 현실적 맥락에서 벗어난 언어가 만들어진다.

Crow의 이론은 발표 후 수년동안 상당한 반향을 이끌어내었다. 현대의 연구자들은 Crow의 이론을 액면 그대로 받아들이지는 않지만, 대뇌 특히 전두엽의 비대칭성과 조현병 사이의 연구가 집중적으로 이루어지고 있다. 대체로 조현병 환자에서 구조적 혹은 기능적 비대칭이 제대로 발달되지 못했다는 연구 보고가 많은 편이다. [**(Ribolsi et al. 2014)**](https://paperpile.com/c/L64Dvp/MVZHj) 최근에는 인간 커넥톰의 관점에서 조현병 환자의 백질에서 관찰되는 비대칭적 연결의 질적, 양적 특성이 활발히 연구되고 있다.[**(Sun et al. 2017)**](https://paperpile.com/c/L64Dvp/TlbFK)
