---
title: "2장 1절 조현병의 유전학적 이해"
description: Genetic Understanding of Schizophrenia
bibliography: references/02-01.bib
link-citation: yes
---

<a href="article-02-02.html"><i class="arrow far fa-arrow-alt-circle-right"></i></a>

## 1-1. 유전학 연구의 태동

모든 정신증은 결국 하나의 질환이 다양하게 변용되어 나타나는 것뿐이라는 단일정신병([1장 1-3절 참조](article-01-01.html#modern-period)) 개념이, 서로 명확히 구분되는 다수의 정신질환이 존재한다는 크레펠린의 혁신적인 개념으로 대체된 이후, 정신의학계는 새로운 희망과 의욕에 몸달아 있었다. 생물정신의학의 기치를 내건 그리징거([1장 1-5절 참조](article-01-01.html\#kraepelin))의 제자들은 그렇다면 다수의 정신질환은 제 각각 특징적인 신경병리를 보일 것이요, 이는 그에 상응하는 독특한 유전적 변이때문에 일어날 것이라 예상하였다. 그들이 이렇게 생각한 것은 경험상 정신질환이 특정 가계(pedigree)에 밀집되어 나타나는 것처럼 보였기 때문이다. 당대 학자들이 가장 먼저 떠올린 가설은 변성 개념([1장 1-4절 참조](article-01-01.html#before-kraepelin))이었다. 그들은 정신질환이 대를 거듭하면서 변이가 누적되어 점점 더 심한 형태로 악화된다고 믿었으며, 그 최종 국면에 조현병과 치매가 놓여있다고 생각하였다.

그러나 제대로 된 역학조사나 가계조사없이 유전적 증거를 확인할 수는 없었으며, 하물며 이를 정량화할 방법도 존재하지 않았다. 이미 다윈은 진화론을 통해 종의 생존적합성을 결정하는 미세한 표현형질(phenotype)들이 세대를 거쳐 유전된다고 주장하였다. 다윈의 사촌이었던 <s>Galton</s>은 가계 구성원 들의 다양한 신체 치수를 서로 비교함으로써, 이들 간의 상호 관계를 알아낼 수 있을 것이라는 아이디어를 구상했다. 그는 이러한 신체계측 자료를 광범위하고도 치밀하게 수집하였으며, 이를 제자였던 <s>Pearson</s>에게 맡겨 분석하도록 하였다. Galton과 Pearson이 몸 담았던 실험실은 유전이 어떻게 일어나는 지에 대한 이론적 문제보다는, 서로 다른 신체 치수 즉 표현형이 얼마나 유전에 의해 결정되는가를 계산하는데 주력하였다. Galton은 <s>중심 극한 정리</s>의 개념을 응용하여, 키나 몸무게 같이 정규 분포에 가까운 변이를 보이는 현상들은, 무수히 많은 요인들의 독립적 영향들이 합쳐져서(평균값을 통해) 나타나는 것이라 생각하였다. 따라서 유전되는 것은 연속적이고 미세한 변이를 일으키는 많은 수의 형질 들이고, 질병을 결정하는 것은 다수 형질 들의 효과의 총합일 것이라 믿었다. 1907년 Pearson의 동료인 <s>Heron</s>은 "광증의 통계 및 광증경향의 유전에 대한 첫번째 연구(A First Study of the Statistics of Insanity and the Inheritance of the Insane Diathesis)"라는 저서를 발간하였다. 이 책은 정신지체, 조현병을 비롯한 광증의 유전 정도를 정량적으로 분석한 첫번째 기록이며, 이 책에 실린 수치들은 현대에 추정된 수치와 매우 근접해있다.[@Kendler2015-lz] 당시 Galton의 실험실에서 함께 일했던 일군의 학자들을 후세 사람들은 "생체계측적 유전학자(biometrical geneticists)"라고 불렀다.

<aside>

**Francis Galton (1822\~1911)**: 영국의 우생학자, 유전학자이자 통계학자. 인류의 발전을 위해서는 부적격자의 탄생을 막고, 적격자의 탄생율 증진시켜야 한다고 주장하였으며 우생학(eugenics)이라는 용어를 처음 사용하였다. 부모의 키와 자녀의 키 간에는 긴밀한 상관관계가 있다는 것을 밝혀내면서, 상관계수, 회귀 등 통계학의 몇가지 기본 개념을 확립하였고, 이를 유전학 연구에 응용하였다.

**Karl Pearson (1857\~1936)**: 영국의 수학자이자 통계학자. Galton의 제자로서 생체계측적 유전이론의 기초를 다지는데 공헌하였다. 유전 현상을 수학적/통계학적으로 이해하는 길을 마련했고, 산포도, 표준편차, 상관계수, 회귀계수, 카이-검정, p 값 등의 개념을 창안하여 현대적 통계분석의 기틀을 세웠다.

**중심 극한 정리(central limit theorem)**: 서로 독립인 무작위 변수가 더해지면, 일정한 평균과 표준편차를 갖는 정규 분포에 흡사한 분포를 갖게 된다는 이론. 더해지는 변수가 많으면 많을 수록 정규분포에 가까워진다. 이 이론이 처음 제시된 것은 1733년 Moivre에 의해서였으나, Galton board를 발명하여 이 이론을 일반인에게 이해시키고 대중화시킨 것은 Galton이다.

**David Heron (1881\~1969)**: 스코틀랜드의 통계학자. Pearson의 연구 조교로 경력을 시작하였다.

</aside>

현대 유전학을 탄생시킨 <s>멘델</s>이 완두콩 교배를 통해 발견한 소위 "멘델의 유전법칙"을 학계에 발표한 것은 1865년이었으나, 그 학문적 중요성이 재발견된 것은 안타깝게도 멘델이 죽은 후 15년이 지난 1900년에 이르러서였다. 연속적이고 미세한 형질이 점진적으로 유전된다고 여긴 Galton/Pearson과 달리, 멘델의 제 1법칙은 유전현상은 이산적 단위(discrete unit)를 통해 일어난다고 주장한다. 예를 들어 그가 연구했던 완두콩의 경우 우성 형질과 열성 형질은 황색/녹색 혹은 둥글다/주름지다 처럼 뚜렷이 구분되는 단위로 나뉘어져 있다. 이러한 대립형질 중 우성 아니면 열성 형질 하나가 발현될 뿐이지, 황색과 녹색 인자가 유전되었다고해서 연두색 콩이 나오는 것은 아니다. 이러한 논리에 따라, 당시에는 아직 DNA가 발견되기 전이지만, 생식을 통해 전달되는 대립유전형(allele)과 그에 의해 결정되는 표현형 사이에는 일대일 대응관계가 성립된다고 믿어졌다.

<aside>

**Gregor Mendel (1822\~1884)**: 오스트리아의 식물학자로 유전학의 기본 법칙을 발견하였다. 천주교 사제로서 일하면서도, 아버지의 과수원에서 일했던 경험을 살려 농학, 원예학에 몰두했다. 30대 중반부터 7년여간에 걸쳐 완두콩을 재배하면서 유전에 대한 실험을 진행했고, 이를 명쾌한 수학적 원리로 발표하였다. 생전에는 인정받지 못하였으나, 1900년에 들어서 유럽의 식물학자들에 의해 재발굴되었다.

</aside>

이는 이후 질병의 유전 연구에 커다란 영향을 미쳤고, 유전형과 표현형은 동일한 현상의 서로 다른 측면처럼 취급되었다. 질병 역시 하나의 표현형이라고 했을 때, 이를 결정하는 유전인자가 어딘가에 존재할 것이라는 추측은 매우 매력적인 가설이었다. 1900년대 초반, 혈우병, 야맹증, 안구색 등의 표현형이 멘델 법칙에 따라 유전된다는 것이 증명되었다. <s>Rüdin</s>은 1907년 멘델의 유전법칙이 조현병에 들어맞는지 체계적으로 연구하기 시작하였다.[@Zerbin-Rudin1996-nn] 그는 비록 단일 유전인자에 의한 멘델 유전으로는 자신이 가계연구에서 얻은 데이터를 설명할 수 없었지만, 두 개의 열성 유전인자에 의한 유전 모델로는 상당히 근접하여 설명할 수 있었다고 주장하였다. 또한 유전인자를 물려받았어도 발병하지 않는 <s>불완전 침투</s> 현상이 있을 것이라고 추측하였다. 크레펠린은 조현병 환자의 형제들에게서, 뚜렷하게 병이 있는 것은 아니지만 좀 유별난 성격이 많다는 것을 관찰하고, 이들이 Rüdin이 말한 불완전 침투에 의한 잠재적 환자일 것이라고 생각하였다.[@Kendler1985-an] 크레펠린과 Rüdin 그리고 그들의 영향을 받았던 독일 정신과 의사들은 질병이 연속적이고 미세한 변이의 총합이라는 생체계측적 모델보다는, 이산적이고 뚜렷이 구분되는 대립형질이 유전된다는 멘델의 모델을 받아들였다. 그들은 유전인자-신경병리-조현병이라는 단순한 인과관계 모델에 매료되었기 때문이었다. 그러나 아무리 애를 써서 관측결과를 모델에 우겨넣으려 해도 잘 맞지 않았다. 좀더 확장된 모델이 필요할 때였다.

<aside>

**Ernst Rüdin (1874\~1952)**: 스위스 태생의 독일 유전학자이자 정신과의사. 비록 정신유전학에서 많은 업적을 남겼지만, 나치의 이데올로기에 동조하여 정신질환자들을 거세하거나 처형하는 것을 암암리에 지지하였다.

**불완전 침투(incomplete penetrance)**: 질병을 일으킨다고 알려진 유전자 변이를 물려받은 개인이 실제로 질병에 걸리게 되는 비율을 침투라고 한다.이 비율이 100%가 아닐 때는 불완전 침투라 한다.)

</aside>

1902년 통계학자인 <s>Yule</s>은, 멘델 법칙에 따라 유전되는 대립형질 다수가 서로가 서로에게 영향을 미친다면, 실제 가계도에서 관찰되는 연속적인 형질 분포를 설명할 수도 있을 것이라고 하였다. 당시 초파리(drosophila)를 대량으로 사육하면서 인공적으로 돌연변이를 일으키는 연구를 진행하고 있던 <s>Morgan</s>은 대부분의 돌연변이가 표현형에 큰 변화를 가져오지 않는 미세한 것이요, 질병을 일으킬 정도의 중요한 돌연변이는 극히 드물게만 일어난다는 것을 보고하였다. 이러한 사실들을 종합하여 1918년 <s>Fisher</s>는 연속적인 변이를 보이는 형질은 조그만한 효과를 갖는 많은 유전인자들의 영향을 단순히 합한 것으로 충분히 설명할 수 있다고 주장하였다.[@Provine2001-iw]

<aside>

**George Udny Yule (1871\~1951)**: 영국의 통계학자. 특히 시계열 분석의 초석을 놓았다.

**Thomas Hunt Morgan (1866\~1945)**: 미국의 진화생물학자. 염색체가 유전현상에서 차지하는 역할을 발견한 공로로 1933년 노벨 생리의학상을 수상하였다.

**Ronald Fisher (1890\~1962)**: 영국의 통계학자이자 유전학자. 근대 통계학의 거의 모든 토대를 혼자서 세웠다 해도 과언이 아닐 정도로 많은 개념과 통계기법을 도입하였다. 진화론에서 다윈주의를 전파하는데도 중요한 역할을 하여 다윈의 가장 위대한 후계자로 불리운다.

</aside>

Fisher가 생체계측적 유전이론과 멘델식 유전이론을 통합한 이후에도, 각 이론을 신봉하는 유전학자들은 제각기 자기들만의 이론을 발전시켜 나갔다. 그러나, 1960년대 중반에 이르러 다유전자 유전모델(polygenic inheritance)[@Gottesman1967-rq]**​**과 경향성-역치(liability-threshold) 모델[@Falconer1967-wf]이 반향을 일으키면서, 조현병의 유전 방식은 서서히 이 두 모델에 의해 설명되기 시작하였다. 이는 진단개념에도 상응하는 영향을 주었다. 멘델식 유전모델에서는 질병과 건강상태의 구분이 비교적 명확하지만, 다유전자 모델에서는 형질의 분포가 연속적이라 이 구분이 애매하다. 이에 대해 조현병 자체가 연속적인 성향 즉 스펙트럼에 가까운 상태이며, 진단을 내리는 것은 이러한 스펙트럼 어딘 가에 임의적으로 역치를 설정하는 것이라고 이해되기 시작하였다. 이러한 개념은 1970년 대 말부터 정신유전학의 분석방법으로 인기를 끌던 <s>구조방정식</s>에서 가정하는 잠재변인(latent variable)의 개념하고도 잘 맞아 떨어졌다.[@Franic2012-ak]

<aside>

**구조방정식(Structural Equation Modeling, SEM)**: 여러 변인들 간의 인과관계를 하나의 모형을 통해 검증하는 분석방법. 특히 잠재변인(latent variable)을 가정하여 직접 측정할 수 없는 구성개념에 대해서도 인과관계를 파악할 수 있다.

</aside>

## 1-2. 가계 조사 및 역학 연구

Rüdin의 선구적 연구를 시작으로 이후 뒤따른 가계 조사에서도, 조현병 환자의 생물학적 친척 중에 조현병 환자가 발생할 비율이 높다는 것이 확인되었다. 한편 당시의 정신분석학적 이론이나 Bateson 등이 주창한 <s>생태 이론</s>에서는 부모의 양육방법이나 가족 내 의사소통 패턴이 조현병의 원인이라고 간주되었다. 따라서 가계 내에 환자가 많은 것, 형제 중에 조현병 환자가 동시에 나타나는 것도 이러한 영향 때문으로 재해석 되었다. 이에 유전 이론을 신봉하는 학자들은 쌍생아 연구를 통해 이런 주장을 정면돌파하고자 하였다.

<aside>

**생태이론**: Gregory Bateson (1904\~1980)은 정신을 독립된 실체가 아니라 생태계적 시스템 속에 내재하고 성숙되어가는 역동적 사건으로 이해한다. 따라서 정신을 이해하기 위해선 이를 둘러싼 시스템을 이해해야 하며, 시스템 구성원 간의 커뮤니케이션을 살펴보아야 한다고 주장하였다. 이 논리대로라면 정신과 환자의 경우 가장 중요한 생태계적 시스템은 가족이며, 가족 내의 왜곡된 커뮤니케이션이 질병을 야기할 것이다.

</aside>

크레펠린의 제자였던 <s>Luxenberger</s>는 1928년 조현병 환자를 대상으로 한 최초의 쌍생아 연구를 수행하였다. 그가 조사한 일란성 쌍생아 중 조현병의 <s>발생일치율(</s>은 58%였던 반면, 이란성 쌍생아 중에서는 두 쌍생아가 모두 조현병에 걸린 사례를 찾아낼 수 없었다.[@Andreasen1994-bx] 이후 수십년간 이어진 유사한 연구에서 일란성 쌍생아에서의 발생일치율은 이란성 쌍생아에 비해 5-10배 정도 높다는 것이 확인되었다. 영국의 베들렘 병원과 모즐리 병원(Maudsley hospital)은 1948년 이래 공동으로 그곳을 거쳐간 모든 환자들의 신상정보와 임상기록을 보관해왔다. Gottesman과 Shields**​**[@Gottesman1972-tr]**​**가 처음 이 자료에 등록된 쌍생아 자료를 분석하였고, 1999년에는 Cardno 등[@Cardno1999-hh]이 재분석하였다. 일란성 쌍생아의 경우 발생일치율이 0.8% 였음에 비해, 이란성 쌍생아는 5.3%에 지나지 않았으며, <s>유전성</s>은 82%에 달하였다.

<aside>

**Hans Luxenberger (1894-1976)**: 독일의 유전학자. 정신유전학의 뮌헨 학파(Munich School of Psychiatric Genetics)의 일원이다. 뮌헨 인근에 입원해있던 조발성 치매 환자 16,382을 조사하여 이중 211명의 쌍생아를 찾아낸 후 발병 일치 여부를 분석하였다.[@Noll2009-av]

**발생일치율(concordance rate)**: 유전적 정보를 공유하는 두 사람이 모두 동일환 질환에 걸릴 확률. 보통 이미 진단을 받은 기준 환자(proband)의 친인척이 동일 질환에 걸릴 확률로 표시한다.

**유전성(heritability)**: 개체 집단에서 발견되는 표현형의 변이 중에서 유전형의 변이로 인해 설명되는 비율.

</aside>

입양아 연구에서도 유사한 결과가 얻어졌다. 이 분야에 탁월한 업적을 낸 <s>Kety</s>는 20 여년간의 꾸준한 연구를 통하여 다음과 같은 사실을 확인하였다. 첫번째, 조현병 어머니에게서 태어나 정상 부모에게 입양된 아이들은, 자신을 낳아준 어머니에게 양육된 아이들과 동일한 발병률을 보였다. 둘째, 입양된 조현병 환자의 현재 가족 구성원(입양한 가족)에서의 발병률보다, 원래의 생물학적 가족에서 훨씬 조현병의 발병률이 높았다.[@Kety1976-ts]

<aside>

**Seymore Kety (1915\~2000)**: 미국의 신경생물학자. 뇌혈류를 측정하는 방법을 최초로 개발하였으며, 미국 국립정신건강연구원(NIMH)의 초대 국장을 역임하였다.

</aside>

쌍생아 연구와 입양 가족 연구는 조현병 발병에 유전적 요인이 차지하는 비중에 대해 귀중한 정보를 제시했음은 물론, 양육방식과 가족 내 갈등이 발병의 주요 요인이라는 당시 심리학자와 정신분석가들의 편견을 일소하는데 기여하였다.[@Holzman2001-rz]

## 1-3. DNA의 발견과 연관연구

크레펠린에 의해 조현병이 개념이 자리잡기가 무섭게, 학자들은 이 질환이 유전적 요인에 의해 일어난다는 것을 입증하고자 애썼다. 이런 배경에는, 조현병 환자가 특정한 가계에 몰려 나타나는 경향이 거듭 관찰되고 있었다는 것, 오염된 혈통과 변성 개념이 사람들에게 은근한 두려움으로 다가왔다는 요인이 자리잡고 있었다. 이에 덧붙여 질병의 원인론에 대한 당시의 지식과 이론도 영향을 끼쳤다. 현재도 마찬가지이지만, <s>아리스토텔레스의 원인 이론</s>및 뉴턴 역학의 영향을 받은 당대의 학자들은 현상 혹은 변화의 근원을 파고들어가면 결국 일차적 원인에 맞닥뜨리게 된다고 믿었다. 아리스토텔레스 철학에서는 물질의 재료나 구성 혹은 외부에서 힘을 가한 존재가 그 역할을 하며, 뉴턴 역학에서도 물체가 운동하려면 맨 처음 힘을 가한 어떤 존재가 있어야 한다. 우주에 존재하는 모든 만물의 운동 역시 태초에 궁극적인 원인이 있어서 시작되었으며, 아리스토텔레스는 이를 <s>원동자</s>라고 하였다.

<aside>

**아리스토텔레서의 4원인 (Four causes of Aristoteles)**: 아리스토텔레스는 변화와 운동에는 반드시 원인이 있으리라 가정하였고, 다음 네가지를 열거하였다. 1) 질료인(material cause)은 대상이 무엇으로 이루어져 있는지, 2) 형상인(formal cause)은 대상이 어떤 특성을 갖고 어떤 법칙을 따르는지, 3) 작용인(efficient cause)은 외부로부터 가해진 변화나 힘, 4) 목적인(final cause)은 대상이 애초에 지닌 의지, 동기, 목적은 무엇인지를 가리킨다.

**원동자(prime mover)**: 아리스토텔레스는 원인 없는 결과는 없다고 보았는데, 그렇다면 애초에 우주가 왜 움직이게 되었는지를 설명하기 곤란해진다. 이러한 난점에 대해 그는 원인이 없이도 스스로 움직이기 시작한 최초의 존재를 가정하고 이를 원동자( 元動者)라고 칭하였다.

</aside>

병인론을 최초로 공식화한 <s>Koch와 Loeffler</s>에게 있어서 prime mover는 다름 아닌 미생물이었다. 그러나 조현병이 미생물에 의한 질병이 아닌 이상, 궁극적 병인으로 가장 걸맞은 것은 유전적 요인이었던 셈이다. 조현병 유전 연구의 초창기에는 가계도 분석과 역학 연구를 통하여 그 유전성 을 조사하는 것이 고작이었으나, 염색체의 발견을 거쳐 DNA의 구조와 기능이 밝혀지면서 유전 연구는 유전적 원인(genetic cause)을 찾는 연구로 거듭나게 되었다. 다유전자 모델이 어느 정도 영향력을 갖게 된 이후에도, 상당수의 유전학자들은 그야말로 "조현병을 일으키는" 단일 유전자를 찾고 있었다.

<aside>

**Koch의 병인론 가설 (Koch postulates)**: 미생물학자인 Robert Koch와 Friedrich Loeffler가 1884에 제안한 가정. 만약 특정한 병에 걸린 환자에서 1) 유달리 어떤 미생물이 많이 발견되고, 2) 그 미생물이 실험실에서 배양될 수 있으며, 3) 배양액을 다른 개체에 주입하면 동일한 병이 생기고, 4) 새롭게 병에 걸린 개체에서도 역시 동일한 미생물을 다량 추출할 수 있다면, 질병의 원인은 처음의 그 미생물이다라는 가설이다.

</aside>

염색체는 19세기 말에 이미 그 개념이 도입되었고, 전술했던 Morgan의 연구를 통해 존재가 증명되었다. 1920년대에는 이미 현미경을 통해 염색체를 육안으로 관찰할 수 있었고, 인간 염색체의 대략적인 개수도 알려졌다. 원래 멘델의 두번째 유전법칙인 독립의 법칙(law of independent assortment)에 따르면, 서로 다른 표현형은 독립적으로 유전되어야만 했지만 실상은 그렇지 않았다. 한 가계 내에서 서로 다른 표현형이 함께 유전되는 유전자 연관(genetic linkage)은 이미 1905년 <s>Bateson</s>에 의해 발견되었다. 선형 구조를 갖는 염색체 개념에 이를 적용하여, 염색체 상에서 서로 거리가 근접한 유전인자는 함께 유전될 가능성이 높고, 역으로 거리가 먼 유전인자는 재조합(recombination)될 확률이 높다는 이론이 고안되었다. 이를 토대로 염색체 지도가 만들어지기 훨씬 이전에 이미 연관 지도(linkage map)가 만들어졌다. 초기에는 대립형질(표현형을 구성하는 우성형질과 열성형질의 쌍) 하나하나가 지도에서의 위치를 가리키는 <s>표지자 </s>의 역할을 하였으나, 이는 초파리 실험과 같이 다양한 형질 변화를 인위적으로 일으킬 수 있는 연구환경이 아니라면 적용하기 어려웠다.

<aside>

**William Bateson (1861\~1926)**: 영국의 생물학자로 "유전학(genetics)"이라는 용어를 처음 사용하였으며, 멘델의 유전법칙을 널리 전파하는데 기여하였다.

**표지자 (marker)**: 하나의 염색체에 들어있는 DNA는 하나의 긴 1차원의 가닥으로 이루어진다. 이 가닥 내에서 상대적 위치를 표시할 수 있는 모든 종류의 변이를 표지자라고 한다.

</aside>

세포 내의 유전물질에 대한 가설은 이미 19세기 중반에 제기되었으며, 이것이 핵산(nucleotide)으로 구성되었다는 것 역시 1919년 <s>Levene</s>에 의해 발견되었다.[@Pray2008-vy] 이후 <s>Watson과 Crick</s>는 DNA가 이중나선 형태를 이루고 있음을 1953년에 발표하였다. DNA의 발견은 부연 설명이 필요없을 정도로 유전 연구를 혁신적으로 진일보시켰다. 연관 지도를 통해 유전인자들이 일렬로 배열되어 있을 것이라 짐작하고 있었지만, 이제 그 실질적 증거를 확보하게 되었다. 바야흐로 연관연구는 표현형을 기반으로 한 원시적 표지자가 아닌 분자 단위의 세밀한 표지자를 이용하여 행해질 수 있었다.

<aside>

**Phoebus Levene (1869\~1940)**: 러시아 태생의 미국 생화학자로 DNA와 RNA의 구조를 분석하였으며, 핵산이 연이어 연결된 구조가 이들의 기본 형태라는 것을 발견하였다.

**James Watson (1928\~), Francis Crick (1916\~2004)**: 미국의 분자생물학자로 공동작업을 통해 DNA의 3차원적 구조를 발견했으며, 이 공로로 함께 1962년 노벨 생리의학상을 수상했다.

</aside>

표지자가 되기 위해선 다른 표지자들과의 상대적 위치를 확정할 수 있어야 하며, 동시에 인구집단 내에 적당한 비율의 변이가 있어야 한다. 초창기에 등장한 표지자는 RFLP (Restriction fragment length polymorphism)라는 것으로, 특정한 염기서열만을 잘라내는 제한효소(restriction enzyme)에 의해 잘려나간 조각들의 패턴을 말한다. 개개인에 따라 염기서열이 조금씩 다르기 때문에, 이렇게 잘려나간 패턴 역시 변이가 생긴다. 이러한 조각들을 전기영동(southern blot)에 통과시키면, 분자량에 따라 잘려진 염기들을 순서대로 배열할 수 있었다. 그러나 RFLP는 특정 염기서열을 인식하는 제한효소가 있어야만 발견할 수 있는 표지자였고, 또 이를 영상화하기 위해서 방사성 동위원소나 형광 염료를 붙여야 하는 등, 자동화하기 어렵고 비용이 많이 드는 작업이었다. 뒤이어 <s>Short Tandem Repeat (STR), Variable Number Tandem Repeat (VNTR)</s> 등의 표지자가 개발되었다. 이들은 많은 수의 대립유전자 변이(allelic variation)를 갖고 있었기 때문에 정보량이 풍부하였으나, 게놈 내에 고루 분포하는 표지자가 아니였기 때문에 제한된 용도로 밖에 쓸 수 없었다.

<aside>

**Tandem Repeat**: DNA에는 특정 염기서열이 연이어 반복되는 경우가 많다. 예를 들어 유전자의 프로모터에 자리잡은 CpG island에는 CG가 100번 이상 반복된다. 반복되는 염기의 길이(bp)가 10개 미만이면 minisatellite, 10\~60개 정도이면 microsatellite라고 하며, STR은 minisatellite, VNTR은 microsatellite가 반복되는 것을 지칭한다. STR, VNTR이 반복되는 수는 개인마다 다르며, 부모로부터 유전되기 때문에 유전적 표지자 역할을 할 수 있다.

</aside>

이전의 연구가 표현형과 표현형 사이의 유전적 거리를 조사했다면, 이제부터는 표현형과 염색체 내 위치를 가리키는 표지자 간의 거리를 조사하기 시작하였다. 대립유전자가 유전될 때는 부모가 갖고 있는 한쌍의 대립유전자 중 무작위로 하나씩만 자손에게 전달되는데 이를 분리(segregation)라고 한다. 만약 특정한 표지자의 대립유전자가 질병과 함께 다음 세대로 전달되는 양상을 보인다면, 그 표지자는 질병유발 유전자와 매우 근접해있다는 증가가 된다. 이러한 동시 분리(co-segregation)을 찾는 것이 연관 연구(linkage study)의 핵심이다.[@2000-mn]

아쉽게도 쏟아졌던 기대에 비해 연관 연구는 큰 성과를 내지는 못했다. 그럼에도 불구하고, 몇몇 연구를 통해 조현병의 발견기전에 한발 다가갈 수 있었다. 강한 연관 신호를 보였던 몇몇 염색체 영역에 대해서 후속 연구가 진행되면서, 그 부위에 위치한 유전자 중 조현병의 병태 생리에 중요한 역할을 할 것으로 기대되는 몇 가지 유전자를 찾아낼 수 있었다. 예를 들어 1q42에서는 DISC1 (Disrupted in Schizophrenia 1) 유전자를, 22q에서는 COMT (Catechol-O-methyltransferase), PRODH (proline dehydrogenase), 8p에서 NRG1 (neuregulin 1), 그리고 6p에서 DTNBP1 (dysbindin) 유전자를 찾아낼 수 있었다. [@Karayiorgou1997-tk][@Karayiorgou2006-vv] 이러한 유전자들은 이후 연합 연구를 통한 후보유전자 검색과정에서도 조현병과 관련되어 있는 것으로 나타났으며, 이후 조현병의 병태생리를 이해하는데 중요한 이정표가 되었다.

그러나 어렵게 얻어진 몇몇 양성 결과들조차 추후 연구에서 결과를 재현하는데 대부분 실패하였으며, 연관 신호가 높게 나타났던 염색체 부위에서 의미있는 유전자를 찾는 것도 쉽지 않았다. 이렇게 기대에 미치지 못한 이유는 다양하다. 무엇보다 연관 연구는 조현병이 기껏해야 몇 개의 드물지만 영향력이 큰 변이에 의해 초래된다는 가정, 그리고 이들이 단순한 멘델식의 우성 혹은 열성 유전모델을 따른다는 가정, 즉 "단일 주요유전자 자리 모형(single major locus model)"에 입각해있다. 설령 다유전자 모델이 맞더라도, 여전히 조현병을 일으키는데 가장 중요한 유전자는 하나라는 뜻이다.[@Elston1970-rg][@Karlsson1974-ts] 이들이 이에 매달릴 수 밖에 없었던 이유 중 하나는 연관 연구의 약한 검증력으로는 영향력이 큰 몇 개의 부위만을 찾아낼 수 있기 때문이다.

검증력을 키워 미세한 연관 신호를 잡아내려면, 많은 수의 환자가 포함되어 있는 대규모 가계를 대상으로 연구해야 하는데, 이런 가계를 찾아내기란 여간 어려운 것이 아니다. 설령 그런 가계를 찾아냈다 하더라도, 포함된 환자들이 많으면 많을수록 그들 모두가 단일한 유전요인에 의해 발병되었을 확률이 떨어진다. 또한 한 가계에서 의미있는 신호를 발견했다 하더라도, 이 신호가 다른 가계에서도 발견된다는 보장이 없다. 즉 발견된 결과는 해당 가계에 국한되는 것이지, 보편적인 조현병의 원인인자로 일반화하기 힘들다. 마지막으로 연관 연구에 사용되는 표지자가 그리 조밀하지 않기 때문에 설령 의심되는 영역을 찾아낸다 하더라도 해상도가 매우 떨어진다.[@Karayiorgou1997-tk] 결국 연관 연구는 역사속의 한 페이지로만 남게 되었다.

## 1-4. SNP의 발견과 연합 연구

유전적 표지자의 문제는 오랜동안 유전 연구를 제약해왔던 사안이다. 보통 인구 집단내에 일정 비율 이상으로 존재하는 돌연변이를 표지자로 사용한다. 그 자신이 질병을 일으키는 경우도 있겠지만, 대부분은 그저 염색체 내의 특정한 위치를 표시하는 역할만 하게 된다. 만약 그 돌연변이가 생명을 위협할 정도라면 인구 집단에 널리 분포할 리가 만무하기 때문에, 그 영향이 너무 크지도 너무 작지도 않아야만 한다. 인간 게놈에는 30억개의 염기가 있다고 하는데, RFLP, VNTR 등과 같은 고전적 표지자들은 기껏해야 몇 만개 정도에 불과하다. 이렇듯 해상도가 낮기 때문에 조현병과 연관된 부위를 찾는다 해도, 그 부위에 포함된 유전자 중 어떤 유전자의 변이 때문인지조차 분명히 알아낼 수 없다.

단일염기다형성(Single Nucleotide Polymorphism, SNP)은 1996년 <s>Lander</s>에 의해 그 개념이 제시되었다. 이는 DNA 염기서열 중 특정 위치의 염기가 다른 것으로 바뀌어 있는 것을 의미한다. 단일 염기의 치환, 삭제, 첨가 등 다양한 기전에 의해 발생하며, <s>소수 대립유전자빈도</s>가 1% 이상인 것만을 SNP라고 말한다. SNP에서 하나의 염기 위치에서 발견되는 대립유전자(allele)은 일반적으로 두 개이다. VNTR과 같이 한 위치에 수십, 수백 개의 대립유전자가 있는 변이보다는 변이의 폭은 좁지만, 그 대신 표지자가 밀집되어 존재하는 것이 특징이다. 평균잡아 1,000bp에 하나 꼴로 염기 치환이 일어나기 때문에, 한 사람의 게놈 내에는 4\~5백만 개의 SNP가 있을 것으로 추정된다. 게다가 커다란 인구집단에서 발견되는 SNP의 수는 무려 1억개에 가깝다.[@1000_Genomes_Project_Consortium2015-dn] 한 유전자 내에도 수십개 이상의 SNP가 분포하는 것이 일반적이며, 따라서 정확히 어떤 부위가 질병 위험과 연관되어 있는지를 높은 해상도로 파악해낼 수 있다. 게다가 1990년 부터 시작된 인간 게놈 프로젝트의 일환으로 DNA 염기서열을 매우 빠르고 정확하게 읽어내는 기술이 부단히 발전하면서, SNP 변이를 확인하는 기술은 속도 뿐 아니라 자동화 정도에서 기존의 표지자들보다 훨씬 더 앞서 있었다.

<aside>

**Eric Lander (1957\~)**: 미국의 수학자이자 유전학자로 MIT와 하버드 대학의 교수로 재직중이다. 유전연구로 유명한 Broad Institute의 초대 국장을 역임하였다. 2021년 출범한 미국의 바이든 행정부에서 백악관 과학기술정책실장(Office of Science and Technology Policy)에 임명되었다.

**소수 대립유전자빈도 (Minor Allele Frequency, MAF)**: 하나의 유전자 자리에는 몇 개의 서로 다른 유전형(변이)이 위치할 수 있다. 이들 변이는 조사된 인구집단에서 일정한 비율로 분포하는데, 그중 가장 드문 대립유전형의 빈도를 의미한다. SNP는 두개의 대립유전자가 있기 때문에 MAF가 너무 작으면 표지자로서의 가치가 떨어진다. 보통 MAF가 1% 이상인 변이를 SNP라고 한다.

</aside>

SNP의 등장으로 말미암아 연관 연구는 연합 연구(association study)로 대체되었다. 연관 연구는 한 가계 내의 구성원을 대상으로 행해지지만, 연합 연구는 전체 인구집단에서 추출된 표본을 대상으로 이루어진다. SNP는 서로 거리가 매우 가깝기 때문에 한 가계의 구성원이 아니라도, 먼 조상이 같다면 근접한 두 SNP는 <s>재조합</s>을 겪지 않은 채 연관된 상태 그대로 세대를 거듭하여 다음 대로 내려갈 것이다. 예를 들어 첫번째 SNP의 대립유전자가 A와 a이고 두번째 SNP의 대립유전자가 B와 b라고 가정하자. 두 SNP가 충분히 가깝다면, 해당 인구집단에서 AB, Ab, aB, ab의 분포는 A, a, B, b의 비율에서 계산되어지는 기대값에 비해 유의하게 어긋나게 된다. 이러한 현상을 연관불균형(linkage disequilibrium)이라고 한다.[@Reich2001-sh]

<aside>

**유전자 재조합 (recombination)**: 유성생식을 하는 포유류는 난자와 정자를 만들때 감수 분열을 하게 되는데, 이 때 두 개의 DNA 가닥이 꼬이면서 유전자 교차가 일어날 수 있다. 이 과정에서 부모 각각으로 부터 받은 유전자들이 뒤섞이는 것을 유전자 재조합이라 한다. 유전자 사이의 거리가 멀면 멀수록 재조합 확률이 높아진다.

</aside>

연합 연구는 지극히 간단한 환자-대조군 연구로서, 조현병 환자군에서 발견되는 SNP 대립유전자의 비율과 대조군에서의 비율을 카이-제곱 등의 통계기법을 이용하여 서로 비교하는 것이다.[@Cordell2005-uk] 환자군에서 특정 대립유전자가 유의하게 자주 나타난다면 그것이 바로 연합의 증거가 된다. 연합이 발견된 SNP 표지자는 그 자체의 변이가 질병의 원인이 될 수도 있고 (직접 연합), 근방에 있는 진짜 질병유발 변이와의 연관불균형 관계를 통해 간접적으로 관련을 맺고 있는 것일 수도 있다 (간접 연합). 간접 연합을 이용하면, 분석에서 의미있게 나온 SNP의 위치를 토대로 질병 유발 유전자가 있는 위치를 점점 좁혀나갈수 있는데, 이를 연관불균형 매핑(LD mapping)이라고도 한다.[@Maniatis2007-bl][@Riley2000-ul]

연합 연구가 도입된 초창기에는 SNP의 유전형을 읽어내는데 높은 비용이 들었기 때문에, 대규모 표본에서 많은 수의 SNP 표지자를 사용하기 힘들었다. 따라서 흔히 "후보 유전자(candidate gene) 연구"를 수행하곤 하였다. 이는 연관 연구나 병태 생리 분석 등을 통해 조현병과 관련되어 있을 것이라 여겨지는 후보 유전자를 설정하고, 이 유전자에 위치하는 대표적인 SNP를 몇 개 뽑아내어 그 대립유전자의 빈도를 비교하는 것이다. 주로 연관 연구에서 강한 신호를 보였던 염색체 부위에 위치하는 유전자를 후보 염색체로 선택하는 경우가 많았다.[@Jorgensen2009-rb]

이 방법을 이용하여 무수히 많은 연구 결과가 발표되었으나, 여전히 재현불가능이라는 벽에 부딪히곤 하였다. 어느 한 연구자가 특정 유전자에 위치한 SNP와 조현병 사이의 긴밀한 연합을 발견했다고 발표했다 하더라도, 뒤를 이어 다른 연구팀이 이를 재현하고자 하면 결국 실패하고마는 일이 반복되었다.[@Ioannidis2001-cl] 혹자는 이를 인종이나 민족 등 인구집단의 차이로 설명하려 하였으나, 재현불가능성은 결국 연합 연구에 대해 부정적인 인상만을 심어주게 되었다.[@Gejman2011-aw]

이러한 후보 유전자 접근에 의한 연합 연구의 결과물들은 <s>SZGene</s>이라는 데이터베이스에 통합되었다. 이 데이터베이스에는 2011년 마지막으로 개정되기 전까지 1,008개의 유전자에 위치한 8,788개의 SNP에 대해 조사한 1,727개의 연구 자료가 실려있다. 관련된 저자들은 이 많은 연구 중에서, DRD1, DTNBP1, MTHFR과 TPH1라는 네 개의 유전자만이 가이드라인에서 정한 기준을 통과한 유의한 조현병 유발 유전자라고 결론지었다.[@Allen2008-we] 이후 후보 유전자 연합 연구는 더 이상 주목을 받지 못하였다. SZGene 데이터베이스 역시 2011년 이후 더 이상 관리가 되고 있지 않다.

<aside>

**SZGene**: Schizophrenia Gene Database ([<http://www.szgene.org/>](http://www.szgene.org/){.uri})

</aside>

## 1-5. 광범위 유전체 연합 연구

앞절에서 살펴본 바와 같이 조현병의 후보 유전자 연합 연구는 무성한 결과만을 내어놓았을 뿐, 그 어느 것도 신빙성 있게 받아들여지지 않았다. 이 문제에 대하여 학계는 물량공세를 통한 대규모 접근으로 방향을 틀었다. 우선 기술의 발전에 의해 유전형을 읽어내는 기술이 점점 더 고속화, 자동화되었고 가격도 현저하게 하락하였다. 차세대 염기서열 분석(Next Generation Sequencing) 혹은 고출력 염기서열 분석(High-throughput Sequencing)이라 불리는 이들 방법은 현재 인간의 전체 게놈을 읽어내는데 하루 정도 밖에 걸리지 않으며, 그 비용도 1,000 달러정도까지 내려가 있다. 따라서 후보 유전자를 가려 뽑거나 그 중에서도 SNP를 선택하는 과정은 불필요해졌으며, 바야흐로 전체 게놈을 한번에 분석하여 연합 연구의 방법론을 적용하는 것도 가능하게 되었다. 이를 광범위 유전체 연합 연구(Genome-Wide Association Study, GWAS)라고 한다. <s>국제 HapMap 프로젝트</s>로부터 시작되어 현재는 <s>1000 게놈 프로젝트</s>로 승계된 국제 공동 연구에 의해 이미 인체에 존재하는 모든 SNP와 그들의 연관불균형 관계가 이미 데이터베이스로 구성되어 있다.[@International_HapMap_Consortium2003-bt][@Sudmant2015-vm] 이를 근거로 전체 게놈에 존재하는 SNP 중 보통 백만 개 이상의 SNP를 뽑아 변이를 조사하고, 유전적 연합여부를 결정하게 된다. 후보 유전자 연구와는 달리, 사전에 어떤 이론적 편견도 갖지 않고 그저 SNP의 전략적 위치만을 고려하여 선택한다. 수백만개에 달하는 변이에 대해 다중 분석을 행하는 것이기 때문에 1종 오류(위양성)의 가능성이 부풀려진다. 이를 해소하기 위해 매우 엄격한 조건 (p \< 5 x 10 ^-8^)을 적용하는 것도 또 다른 특징이다.

<aside>

**국제 HapMap 프로젝트 (International HapMap Project)**: 인간 게놈 내의 변이를 체계적으로 조사하고 이를 데이터베이스화하기 위해 2002년 출범한 국제공동연구로 미국을 포함하여, 일본, 영국, 캐나다, 중국 연구팀이 참여하였다. 얻어진 자료는 전세계 모든 연구자에게 공개되어 유전 연구에 없어서는 안 될 자료가 되었다. 2016년에 서비스가 중단되었다.

**1000 게놈 프로젝트 (1000 Genomes Project)**: HapMap 프로젝트 이후에도 SNP를 비롯하여 발견된 변이의 수는 계속 늘어나기만 하였다. 1000 게놈 프로젝트에서는 표본 수를 3,000명 이상으로 확장하고, 차세대 염기서열 분석을 이용하여 규모가 훨씬 큰 변이의 데이터베이스를 구축하였다. ([<https://www.internationalgenome.org/>](https://www.internationalgenome.org/){.uri})

</aside>

분석하는 SNP의 개수를 대규모화하는 것 이외에, 또 다른 전략은 표본 수를 최대한 늘리는 것이다. 기존에 연구자들이 행한 연합 연구는 기껏해야 수백명 규모의 표본을 사용한 연구였다. 이는 검증력이 떨어지기 때문에, 양성 신호를 붙잡지 못하는 것도 있지만, 음성 결과를 자신있게 음성이라 말할 수 없다는 한계가 있다. 따라서 GWAS는 시작부터 다수의 연구자들이 힘을 모아 컨소시엄을 구성하는 방식으로 나아갔고, 그중 가장 규모가 큰 컨소시엄은 북캘리포니아 대학(University of North Carolina at Chapel Hill)에서 주도하는 Schizophrenia Psychiatric GWAS Consortium과 미국의 7개 대학이 참여한 Consortium on the Genetics of Schizophrenia가 있다. 특히 전자는 조현병을 비롯한 다양한 정신질환의 GWAS 연구를 위해 표본을 수집하고 있는 Psychiatric Genomics Consortium (PGC)의 일환으로 수만명 단위의 조현병 환자 유전체 자료를 모아놓고 있다. PGC에는 무려 45개국, 500여명의 연구자가 참여하고 있기 때문에 다양한 인종과 인구집단이 포함되어 있다.[@Sullivan2018-ld]

이렇듯 거대한 표본과 광범위한 표지자를 통한 분석으로 얻어낸 GWAS의 연구결과는 기존의 후보 유전자 연구를 통해 얻어낸 유전자 군과는 전혀 다른 유전자들을 조현병 유발 유전자로 제시하였다. 전자의 유전자 군은 GWAS 결과 내에서는 별다른 연합 신호를 나타내지 못했으며, 결국 SZGene에 수록된 대부분의 연합 연구 결과가 별 가치가 없다는 것이 밝혀졌다.[@Farrell2015-mi][@Johnson2017-rg]

광범위 유전체 연합 연구 결과를 통해 얻어진 사실은, 결국 조현병을 일으키는 결정적인 돌연변이는 발견할 수 없다는 것이다. 조현병 유전 연구의 선구자들이 꿈꿔웠던 것처럼, 하나 혹은 두 세 개의 유전자 변이가 조현병을 일으키는 것도 아니요, 몇 개의 드문 변이가 상호작용함으로써 발병 위험이 높아지는 것도 아니다. GWAS에서 유의한 관련성을 보이는 유전자는 백여개가 넘으며, 이는 연구의 규모가 커지면서 점점 더 늘어나고 있다. 게다가 이들 중 대다수는 드문 변이(rare variant)가 아니라, 작은 영향력만을 갖는 <s>흔한 변이</s>들이었다. 조현병 발병 위험을 높이는 유전자가 수백개가 되다보니, 이들 유전자 각각의 기능을 분석하는 것은 만만한 작업이 아니다. 대신 연구자들은 유전자 세트 증폭 분석(Gene Set Enrichment Analysis, GSEA)이라는 방법을 적용하곤 한다.[@Schijven2018-pi] 유전자 세트란 세포 내에서 특정 기능에 관여하는 유전자들을 미리 지정해놓은 세트이다. 예를 들어 도파민 신호전달을 담당하는 세포 내 신호전달계와 관련된 모든 유전자 세트 같은 것들이다. GWAS에서 유의한 관련성을 보이는 SNP의 목록과 p 값을 <s>Multi-marker Analysis of GenoMic Annotation (MAGMA)</s>와 같은 소프트웨어에 입력하면, 입력된 SNP 들이 주로 어떤 유전자 세트에 집중되어 있는지를 알아낼 수 있다.

<aside>

**흔한 변이(common variant)**: 흔한 변이란 일반적으로 인구 집단 내에서 1% 이상의 빈도로 나타나는 변이를 말한다.[@Reich2001-sh]

[MAGMA software](<https://ctg.cncr.nl/software/magma>) [@De_Leeuw2015-ag]

</aside>

Pardiñas 등**​**[@Pardinas2018-pf]은 이러한 방식의 GWAS 연구의 대표적인 사례라 할 수 있다. PGC 2세대 데이터를 사용하고 있는 이 연구에는 11,260명의 조현병 환자와 24,542명의 대조군 자료가 이용되었다. GWAS에 통상적인 기준(p \< 5 x 10 ^-8^)을 적용했을 때, 조현병과 유의한 관련성을 보이는 145개의 SNP를 발굴하였다. 저자들은 이들을 MAGMA에 입력하여, 유의하게 집중되어 있는 유전자 세트를 찾고자 했는데, 여기에는 fragile X mental retardation protein (FMRP), 5-HT2c 수용체, 전압 의존 칼슘 채널, 장기 강화(long-term potentiation) 등과 관련된 유전자 세트가 포함되었다.

## 1-6. 유전학 연구의 영향

20세기 초기의 조현병 유전학 연구는 조현병이 진정으로 유전되는 질환인지를 확인하는데 주력하였다. 이후 DNA의 구조가 발견되고, 인간 유전체가 유전자들이 일렬로 배치된 일종의 지도와 같다는 것을 알게 되면서, 표현형과 유전형 들을 하나의 지도로 표시하고자 시도하였다. 1960년대 제한효소(restriction enzyme)가 개발된 후 표지자 개념이 등장하였고, 1977년 <s>Sanger</s>등이 DNA 염기서열을 해독하는 방법을 개발함으로써 바야흐로 현대적 개념의 유전 연구가 시작되었다.

<aside>

**Frederick Sanger (1918\~2013)**: 영국의 생화학자. 1958년에는 인슐린의 구조를 밝힌 업적으로, 1980년에는 염기서열을 분석하는 방법을 고안해낸 공로로 노벨 화학상을 두차례에 걸쳐 수상하였다.)

</aside>

유전 연구에 수많은 연구자가 동참하고 천문학적 규모의 연구비가 투여되는 원인은, 이를 통해 조현병의 근본 원인을 찾을 수 있으리라는 소망 때문이다. 알츠하이머 치매의 경우 1991년에 연관 분석을 통해 19번 염색체에 유발 유전자가 있을 것이라 예상되었고, 2년 후인 1993년에는 apoprotein E (APOE)가 바로 그 유전자임이 밝혀졌다. APOE가 아밀로이드 분해 과정에 직접적으로 참여하며, APOE--ε4 대립유전자를 가진 환자들이 분해과정이 늦을 뿐 아니라 치매 발병 위험이 높아진다는 것도 알게 되었다. 조현병의 원인 유전자를 찾고자 했던 노력은 알츠하이머 치매에서의 극적인 성공에 고무된 바 크다. 원인 유전자를 찾을 수 있다면 병태생리를 이해할 수 있고, 그 과정에 영향을 미칠 수 있는 약물을 개발함으로써 조현병의 치료에 한발 다가설 수 있으리라는 것이 모든 유전 연구자들의 바람이었다.

이 외에도 유발 유전자를 알게 되면, 조현병 고위험군을 미리 찾아낼 수 있다. 물론 조현병의 유전성이 80%에 달한다고 하지만, 이중 SNP 변이가 차지하는 비중은 23% 정도에 지나지 않는다.[@Cross-Disorder_Group_of_the_Psychiatric_Genomics_Consortium2013-tp] 그럼에도 불구하고, 현재로서는 어떤 한개인이 조현병으로 발병할 것인가를 예측하는데 가장 유용한 지표이다. 소위 다유전자 위험 점수(Polygenic Risk Scoring, PRS)란 GWAS에서 얻어진 SNP 변이와 각각의 오즈비를, 한 개인의 전체 유전체 염기서열에 적용함으로써, 그 개인이 앞으로 조현병에 걸릴 위험을 대략이나마 예측하는 기법이다. 아직은 정확도가 높지 않아서 실제 임상에 사용되기에는 무리가 있지만, 초발 조현병 환자나 가족 중 조현병 환자가 있는 고위험군에서는 정확도가 상당히 올라간다고 한다.[@Vassos2017-bo] 10만 명 이상을 대상으로 한 대규모 연구에서 PRS 수치가 상위 10%에 속하는 군은 하위 10%에 속하는 군에 비해 조현병의 발생 빈도가 4.6배 높아졌다.[@Zheutlin2019-ab]
