---
title: '11장 4절: 클로자핀 투여 전략'
description: Treatment Strategies using Clozapine
bibliography: references/11-01.bib
link-citation: yes
---

<a href="article-11-03.html"><i class="arrow far fa-arrow-alt-circle-left"></i></a>

<a href="article-11-04.html"><i class="arrow far fa-arrow-alt-circle-right"></i></a>

## 4-1. 치료저항성 조현병에서 클로자핀의 효과

치료저항성 조현병에 있어 클로자핀 투여가 모든 문제의 해답일 수는 없다. 그러나 그만한 대안도 없는 것이 사실이다. 보수적 의사들은 클로자핀 투여를 최대한 마지막 수단으로 남겨놓으려 하며, 보다 급진적인 의사들은 일찌감치 시도하고자 한다. 전자의 경우에도 이유가 없는 것이 아니다. 클로자핀은 무과립구증이라는 치명적인 부작용 외에도 다양한 부작용을 갖고 있으며, 이는 환자의 신체적 건강 뿐 아니라 삶의 질을 위협할 수 있다. 게다가 치료 초기부터 최종 수단을 사용해버리면, 이마저도 효과가 없을 때 속수무책의 궁지에 몰리게 된다. 의사들의 경험 상 발병 초기에는 비교적 약물에 잘 반응한다는 것을 알고 있다. 따라서 발병한 지 수년 이내의 환자에게는 최대한 다양한 약을 시도해보면서, 클로자핀이 아니고도 환자에게 맞는 약을 찾고자 노력한다. 보수적 의사들에게 클로자핀은 그 이후에나 시도해 보는 약물이다.

반면 급진적인 의사들 역시 확고한 근거를 갖고 있다. 한 연구에 따르면 클로자핀을 사용하기 전에 10.1%--36.2% 환자에서 허가된 최고 용량 이상의 항정신병 약물이 사용되었고, 15.9%-60.5%에서는 다약제 처방이 이루어졌다.[@RN173][@RN172] 그러나 고용량에 반응한 환자는 15.5% 정도, 몇 번 약물을 교체한 후에 반응한 환자는 16.7% 정도였으며, 2가지 이상의 항정신병 약물을 병용한 경우에도 반응률은 고작 20%를 좀 넘는 수준이었다.[@RN175][@RN123] 즉 치료저항성이 드러난 환자에게 클로자핀이 아닌 다른 방법을 시도하는 것은 불필요하게 치료 시기만 늦추는 것에 지나지 않았다.[@RN75] 이렇게 요행을 바라며 질질 끄는 것은, 클로자핀 사용에 대한 환자 및 치료진의 불안감을 해결하지 못했기 때문인지도 모른다.

클로자핀이 치료저항성 환자에게 우수한 효과를 나타내는 것은 의문의 여지가 없다. 결정적인 Kane의 연구[@RN176] 이외에도 클로자핀의 우수성을 입증하는 연구는 셀 수 없이 많다. 물론 타 약물에 대한 우월성이 입증되지 못한 연구도 있지만, 이는 클로자핀의 용량을 과감하게 올리지 못했기 때문인 경우가 많다.[@RN352] 치료반응을 보이는 클로자핀의 적절 혈중농도는 350\~420 ng/ml 정도이나 드물지 않게 500 ng/ml 이상에서 반응이 나타나는 경우가 있으며, <s>천장효과</s>가 나타나는 것은 600-838 ng/ml 이상일 때이다.[@RN203][@RN34] 이 정도 혈중농도에 도달하려면 꽤 높은 용량을 써야 하는데, 실제 임상에서는 다양한 부작용 특히 경련발작의 위험때문에 충분히 용량을 높이지 못하는 경우가 많다.

<aside>

**천장효과(ceiling effect)**: 약물 용량 혹은 농도와 효능의 관계는 어느 정도까지는 비례관계를 보이지만, 농도가 일정 수준 이상을 넘게되면 더 이상 효능이 증가하지 않는 경우를 가리킨다. 천정용량은 최대 효능이 나타나는 최소 농도 라고도 이야기할 수 있다.

</aside>

실제 사용에서의 어려운 점에도 불구하고, 클로자핀은 단기적으로 뿐 아니라 장기적으로도 정형/비정형 약물을 통털어서 가장 효과적이다.[@RN170] 그 우수성은 치료저항성 환자에만 국한되는 것이 아니기 때문에, 무과립구증의 위험이 아니라면 초발 환자에서도 권해질 정도이다.[@RN203] 현재 많은 치료 가이드라인에서 클로자핀은 두차례 이상의 약물 치료 실패 후에 고려될 수 있으며, 자살위험이 높을 때 혹은 지속적인 공격성이나 폭력적인 행동을 보일 때는 좀더 일찍 사용될 수 있다. 그러나 이러한 지침은 잘 지켜지지 않고 있으며, 클로자핀 사용 빈도 역시 일정 수준 이상으로는 그다지 높아지지 않고 있다.[@Warnez2014][@Roberts2018] 의사들의 부담감을 넘어서기에는 위험해 보이는 약물이긴 하지만, 좀더 적극적인 사용이 요청되는 바이다.[@Stahl2014]

### 4-1-1. 클로자핀 투여가 지연되었을 때의 문제점

클로자핀을 보다 적극적으로 투여할 것을 지지하는 연구자들은, 클로자핀에 대한 반응에도 골든 타임이 있다고 주장한다. 정신병의 비치료 기간(duration of untreated psychosis)이 평생의 예후를 결정하는데 중요한 역할을 하는 것처럼, 치료저항성 조현병에서 클로자핀을 언제 시작했느냐가 이후 예후를 결정지을 수 있다고 한다. 재발이 반복될 수록 신경퇴행의 정도가 심화되어 치료 반응이 떨어지는 것처럼, 현저한 증상이 지속되는 기간이 길면 길수록 클로자핀 조차 듣지 않는 지경에 이르게 되기 때문이다.

일부 연구자들은 치료저항성이 불거진 지 3년 이내에 클로자핀이 투여되지 않으면 유일한 기회를 놓치는 셈이라고 경고한다.[@RN189][@RN190][@RN191] 클로자핀의 시작을 늦추는 것 자체가 클로자핀에 대한 반응성을 낮춘다는 과감한 주장이다. Yoshimura 등[@RN192]은 두 가지 이상의 항정신병 약물 치료에 실패한 시점을 치료저항성의 진단시점으로 잡고, 이후 얼마나 빨리 클로자핀이 투여되었느냐에 따라 클로자핀 치료에 대한 반응률을 비교해보았다. 그 결과 2.8년이 지나기 전에 클로자핀이 투여되었던 경우의 반응률이 81.6% 였음에 비해, 더 지연되어 투여되었던 경우에는 30.8%에 지나지 않았다. Üçok 등[@RN191]도 유사한 결과를 얻었는데, 클로자핀 치료의 성공 여부를 결정짓는 것은 클로자핀이 투여될 때까지의 지연 시간과 최대용량이었다. 이러한 결과들을 종합하면, 2\~3개의 항정신병 약물에 의한 치료에 실패한 경우, 적어도 3년이 지나기 전에 클로자핀을 투여하는 것이, 클로자핀 저항성을 최대한 예방하는 방법이라 할 수 있다. 일단 클로자핀 저항성으로 판정된다면, 이들에게 행해볼 수 있는 치료 전략은 매우 제한되기 때문이다.[@RN193][@RN194]

### 4-1-2. 양성 증상 이외의 치료 효과

현저한 양성 증상과 함께 공격성을 보일 때, 또는 감정 기복이 심해 우울에 쉽게 빠지거나 충동적으로 자해나 자살 사고를 보일 때, 전통적으로는 항정신병 약물에 리튬이나 항경련제를 병용투여해 왔다. 그러나 클로자핀은 단일요법으로 사용해도 공격행동을 줄일 뿐더러 자살율을 감소시킨다.[@RN178] 2년에 걸친 무작위 임상시험이었던 International Suicide Prevention Trial (InterSePT)에서도 클로자핀은 올란자핀에 비해 유의한 자살 방지 효과를 보였다.[@RN177] 이 결과에 근거하여 미국 식품의약품 안전처(FDA)는 조현병에서의 자살 위험을 클로자핀의 적응증 중 하나로 인정하였다. 덴마아크의 전국적 약물처방기록을 보면, 클로자핀 이외의 항정신병 약물을 사용한 환자는 클로자핀 사용 환자에 비해 1.36배 높은 자해 위험성을 보이고, 두 배에 가까운 사망률을 보였다.[@RN205] 또한 클로자핀은 양성 효과에 미치는 영향과는 독립적으로 지속적인 공격성과 충동적 과격함을 감소시킬 수 있으며, 공격성에 대한 효과는 특히 치료저항성 환자에서 두드러진다.[@RN182]

## 4-2. 클로자핀 저항성

클로자핀이 아무리 효과적인 대안이라 할 지라도, 40\~70%의 환자는 여전히 효과가 만족스럽지 못하다.[@RN75] 클로자핀에 대한 반응여부는 타 항정신병 약물보다는 좀 더 신중을 기해서, 적어도 혈중 농도 350 ng/ml 이상을 유지한 채 8주 이상 지난 후에야 평가한다. 이 기간 중 BPRS-18 혹은 PANSS 점수가 20% 이상 감소되지 않는다면 클로자핀 저항성으로 판정한다. 클로자핀 사용 후에도 앞서 언급한 케인의 치료저항성 기준([11장 1-3-1 참조](article-11-01.html#kane-resistance)) 을 만족하면 초 저항성(ultra-resistance)이라 부르기도 한다.[@RN266]

클로자핀 치료에 저항적인 환자는 부차적 이유로 해서 클로자핀을 충분히 투여할 수 없었던 경우와, 충분히 용량을 높였음에도 불구하고 치료가 되지 않는 경우로 나눌 수 있다. 무과립구증을 제외하고, 클로자핀을 충분히 쓸 수 없는 가장 흔한 원인은 경련발작이다. 경련의 유병률은 적게는 5%에서 많게는 20% 정도까지 보고되며, 경련에 이르지 않는 뇌파 이상의 비율은 그보다 훨씬 더 많다.[@Williams2015]) 문제는 경련의 위험이 용량이나 혈중 농도와 직접적으로 비례한다는 것이다. 일일 300mg 이하에서는 0.6\~2%, 300\~600mg 사이에서는 1.8\~4%이지만, 600mg를 넘어서면 5\~14%에서 경련발작을 일으킨다.[@Kikuchi2014] 한번 경련을 일으키면 다시 일으킬 가능성이 높기 때문에, 자연히 용량을 높이는 것을 주저할 수 밖에 없다. 이 외에도 침흘림, 진정 작용, 기립성 저혈압 등이 용량 의존적이라고 여겨진다. 클로자핀의 허용 용량은 900mg이며, 최대용량에 근접하는 용량은 적어도 400mg이다. 그러나 적지 않은 의사들은 400mg의 용량도 환자의 삶의 질을 망가뜨린다고 생각한다.[@Yamin2010]

클로자핀 저항성에 대해 다양한 치료 전략이 시도되었다.[@RN194] 클로자핀에 반응이 만족스럽지 못하더라도, 클로자핀을 포기하지 않는 것이 모든 치료 전략의 공통점이다. 대신 다양한 약물을 병용하게 되는데, 아미설프라이드, 설피라이드, 리스페리돈 및 아리피프라졸 등이 비교적 많은 데이터를 갖고 있다.[@RN274][@RN275][@RN272][@RN276][@RN271] 병용 투여 후 오히려 증상이 악화될 수도 있기 때문에, 클로자핀 투여 개시 후 적어도 3-6개월간 반응을 점검한 뒤에 고려하며, 병용 투여 후 10주가 지나도 별다른 개선이 없다면 병용 약물은 중단한다.[@RN269][@RN277] 항정신병 약물 이외의 약물로는 특히 라모트리진이 도움이 된다는 보고가 있다.[@RN278][@Tiihonen2009] 만약 병용 투여 전략이 실패하면 전기경련 치료를 시도하게 된다.

### 4-2-1. 임상적 특징

클로자핀을 투여해도 줄어들지 않는 양성 증상이 클로자핀 저항성의 핵심이다.[@RN266][@RN280] 클로자핀을 투여해도 음성/인지 증상이 좋아지지 않는다고 해서 클로자핀 저항성이라 이름붙이진 않는다. 클로자핀 저항성 환자라고 해서, 일반적 항정신병 약물 저항성 환자와 비교했을 때 인지기능 저하정도의 차이는 없었다.[@RN281]

클로자핀 저항성 환자는 전체 조현병 환자의 12\~20%를 차지한다.[@RN168] 대부분은 발병 당시부터 치료저항성을 보인다.[@RN123][@RN122][@RN62] 치료저항성 환자군에게 클로자핀 투여를 미루면 미룰 수록 클로자핀 저항성의 위험이 커지는 것으로 보인다.[@RN191][@RN200][@RN192]

### 4-2-2. 클로자핀 저항성 환자의 치료 전략

클로자핀에 듣지 않는 환자를 다른 항정신병 약물로 교체한다는 것은 출발점부터 불리한 위치에 서 있다. 애초에 다른 약물에 듣지 않아서 클로자핀으로 넘어왔을 것이기 때문이다. 그러나 너무나 적극적인 의사가 지나치게 서둘러 클로자핀을 투여했던 경우, 혹은 효과는 있었지만 내약성 때문에 클로자핀을 투여할 수 없게 된 경우에는 타 약물로의 교체가 효과적일 수 있다. 이런 경우 전통적으로 클로자핀과 분자구조가 가장 유사한 올란자핀으로 전환하는 것이 고려되었으며 긍정적인 성과를 내기도 하였다.[@Dossenbach2000] 증례 보고에 지나지 않지만, 클로자핀에 의한 장폐색 때문에 클로자핀을 끊을 수 밖에 없었던 환자에게 아리피프라졸을 투여한 이후 오히려 그전보다 증상이 좋아졌다는 보고가 있다.[@Feeley2017] 또 다른 연구에서는 치료저항성 때문에 클로자핀을 사용하던 환자를 장기지속형 주사제로 교체했더니 임상상이 악화되지 않으면서 대사증후군 지표가 모두 좋아졌다고 하였다.[@Martínez-Andrés2020] 그러나 이 연구는 일반적 치료저항성 환자를 대상으로 했지, 클로자핀 저항성 환자를 대상으로 한 것은 아니었다. 결론적으로 말하면, 클로자핀 저항성 환자를 다른 항정신병 약물로 교체해서 긍정적 결과를 얻었다는 데이터는 거의 없다.

따라서 클로자핀 저항성 환자라도 클로자핀을 끊지 않는 것이 보통이다. 대신 다양한 약물을 병용하게 되는데, 이 역시 확실한 결론이 나지 않았다. 몇몇 개방형 연구에서는 다른 항정신병 약물을 병용하여 치료 반응이 나아지기도 했지만, 이중맹검 연구만을 골라서 메타 분석을 해보았더니 유의한 차이가 드러나지 않았다.[@RN288] 또 다른 메타 분석에서는 항정신병 약물 다중 투여가 다소간 이점을 보이는 것으로 나타났으나 미미한 정도에 지나지 않았다.[@RN289] 가장 최근에 이루어진 이중맹검 연구를 대상으로 한 메타 분석에서도, 음성 증상과 우울 증상에 대해서만 다소 효과가 있었을 뿐, 양성 증상 호전에는 위약군과 차이가 없었다.[@RN292]

한 가지 예외는 클로자핀과 아리피프라졸의 병용 투여이다. 두 약물은 작용기전이 전혀 다르기 때문에 일치감치 병용 투여 전략이 제안되었으며, 비교적 많은 이중 맹검 임상 시험이 진행되었다. 클로자핀 단독 투여군과 아리피프라졸 병용 투여군을 비교한 임상 연구를 메타 분석한 결과에 따르면, 분명 병용 투여군이 양성 증상을 비롯한 각 분야에서 우수한 반응을 보였다.[@Wagner2019] Tiihonen 등[@Tiihonen2019]은 스웨덴 국가 데이터베이스를 이용하여 클로자핀을 포함한 다양한 항정신병 약물 다약제 투여 환자의 재입원률을 조사하였는데, 가장 재입원 위험이 낮았던 것은 클로자핀과 아리프프리졸을 병용 투여했던 환자들이었다. 이상과 같이 클로자핀 단독 치료에 비해 아리피프라졸 병용 투여가 좀더 효과적이었다는 보고가 많은데 비해, 다른 병용 투여 전략과 비교해서는 별반 이점이 없었다는 연구 결과도 있다. Clozapine Haloperidol Aripiprazole Trial (CHAT)이라고 이름 붙여진 연구에서는 클로자핀 + 할로페리돌 군과 클로자핀 + 아리피프라졸 군을 이중 맹검으로 비교하였는데, 후자가 내약성이 훨씬 우수했을 뿐 효과 면에서는 두 군이 별 차이를 보이지 않았다.[@Barbui2011][@Cipriani2013]

항경련제 중에서 특히 클로자핀과의 병용 요법이 부각된 것은 전압의존 나트륨 채널 차단제인 라모트리진이다. 라모트리진은 Phencyclidine (PCP) 유발 정신병 모델에서 유의한 치료 효과를 나타내기 때문에[@Quarta2011], 일찍부터 치료저항성 조현병 환자에게 증강 치료로서 시도되었고 상당한 가능성을 보여왔다.[@Large2005] 캐나다의 정신과 의사 Dursun 등[@Dursun1999]이 6명의 클로자핀 저항성 환자에게 시도하여 성과를 얻은 후, 현재까지도 끊임없이 연구가 이어졌다. 2009년에는 첫번째 메타 분석결과가 발표되었는데, 음성 증상 및 양성 증상에서도 위약 대조군에 비해 우수한 성적을 보였다.[@Tiihonen2009]

토피라메이트 역시 유사한 항경련제로서 클로자핀 저항성 환자에게 시도되어 왔다. Zheng 등[@Zheng2017]은 클로자핀과 다양한 항경련제 병용 투여에 대한 메타 분석 결과을 발표하였는데, 여러 연구에서 비교적 일관되게 우수한 성적을 나타낸 것은 발프로에이트와 토피라메이트였다. 라모트리진도 일차 분석에서는 유효한 것으로 나타났으나, 지나치게 성적이 우수한 두 개의 연구를 제외하였더니 더 이상 유효하지 않은 것으로 나타나 제외된 두 연구 결과에 의구심을 불러 일으켰다. 그러나 의사들의 약물 사용 추세를 보면, 토피라메이트는 치료저항성을 해결하기 보다는 체중 증가, 당대사 호전, 다음증 등 부작용을 해결하기 위해 사용하는 경우가 많으며, 정작 효과 증진을 위해서는 라모트리진을 선호하는 편이다.

이 밖에도 항우울제나 글루타메이트 효현제 등을 병용 투여하기도 하는데, 이는 클로자핀 저항성을 해결한다기 보다는 클로자핀을 투여해도 여전히 미진해보이는 영역을 호전시키기 위해서 시도된다. 주로 음성 증상 및 인지 증상이 그 대상이 되는데, 얻어진 결과들이 썩 만족스럽지는 못하다. 항우울제는 클로자핀 투여에도 별반 변화되지 않은 음성 증상을 호전시키기 위해 활발하게 연구되었으나, 얻어진 결과는 초라하다. 플루옥세틴은 거의 효과가 없었으며, 시탈로프람은 중국에서 행해진 단 하나의 연구에서만 효과가 입증되었다. 미르타자핀의 경우 행해지 두 개의 연구가 상반된 결론을 내놓고 있어 결론이 나지 않았다.[@Sommer2012] 이외에도 CX 516, D-cycloserine, D-serine, glycine, sarcosine과 같은 글루타민계 약물도 클로자핀과 함께 투여되었으나 결과는 변변치 못했다.[@Sommer2012]

종합하면 클로자핀에 대해서도 효과를 보이지 않을 때 선택의 폭은 무척이나 좁혀진다. 아리피프라졸의 병용 투여를 제외하고는 근거중심 의학에서 요구하는 근거가 전혀 없는 상황이다. 하지만 여러가지 이유로 클로자핀을 충분히 쓸 수가 없을 때, 대안으로서 시도되는 다양한 전략이 예기치 않게 돌파구가 될 수도 있다. 예를 들어 Lowe 등[@Lowe2018]은 심각한 부작용때문에 클로자핀을 사용할 수 없었던 환자에게 vortioxetine과 lurasidone을 함께 투여하여 눈에 띄는 효과를 보았던 증례를 보고하였다.
