---
title: '11장 5절: 전기경련 치료 및 뇌자극술'
description: ELectroconvulsive Treatment and Brain Stimulation
bibliography: references/11-01.bib
link-citation: yes
---

<a href="article-11-04.html"><i class="arrow far fa-arrow-alt-circle-left"></i></a>

# **5. 전기 경련치료 및 뇌 자극술**

## 5-1. 개요

치료저항성 조현병 환자에서 클로자핀을 사용해도 양성 증상이 조절되지 않는다면 거의 최종적인 단계로 전기경련 치료(Electroconvulsive Treatment, ECT), 반복적 경두개 자기자극(Repetitive Transcranial Magnetic Stimulation, rTMS), 뇌심부 자극술(Deep Brain Stimulation, DBS) 와 같은 뇌자극 치료를 고려하게 된다.[@RN40] 전기경련 치료에 대해서는 임상적 증거들이 꽤 많이 축적된 편이며 비교적 긍정적인 성과를 보이고 있으나, 다른 두 치료법은 역사가 오래되지 않아서인지 효과를 판단할만한 자료가 부족한 편이다. 이들 치료법은 치료저항성 환자에 대한 효과를 고려하기에 앞서 조현병 자체에 효과가 있는지 불분명하지만, 워낙 실험적인 치료법이라 치료저항성 환자들을 중심으로 시도되어 왔다. 비록 전기경련 치료만큼의 효과는 확립되지 않았다고 할 지라도, 접근성이 좋고, 편견이나 낙인에 영향받지 않으며, 인지기능 부작용이 전혀 없다는 점에서 앞으로의 성장이 기대된다.

## 5-2. 전기경련 치료

### 5-2-1. 치료저항성 환자에 대한 급성기 효과

ECT는 치료에 듣지 않는 양성 증상, 특히 폭력성과 호전성을 감소시키는데 상당히 효과적이다. 특히 클로자핀에마저 저항성을 보이는 환자에게는 ECT를 능가할만한 치료 전략이 존재하지 않는다. 클로자핀 투여를 유지하면서 ECT를 병용하는 경우 반응율은 47.4\~72.7%에 이르는데 이는 그 어떤 부가요법 중에서도 가장 높은 반응율이다,[@RN122][@RN313][@RN312] Lally 등[@RN122]이 메타 분석을 통해 조사한 바에 따르면, 클로자핀에 저항성을 보이던 환자에게 평균 11회에 걸쳐 ECT를 시행하였더니 66%에서 효과적이었다. Petrides 등[@RN321]은 충분한 혈중농도에서 12주 이상 클로자핀 치료를 진행했어도 증상이 지속되었던 환자를 두 군으로 나누어, 한 군은 그대로 치료를 계속하고 다른 군은 8주간에 걸쳐 ECT를 실시하였다. 전자에선 반응한 환자가 한명도 없었는데 비해, 후자에서는 50%가 반응하였다. 비교가 끝난 후 전자의 환자군에게도 역시 ECT를 시행하였는데, 여기서도 반응율은 약 47%정도였다.

그러나 이런 높은 반응율은 개방형 연구에서 얻어진 것으로서, 근거자료로서는 불충분하다. Petrides 등[@RN321]의 연구만해도 평가자만이 시행된 치료에 대해 맹검상태였을 뿐, 담당 의사나 환자는 자신이 ECT를 받았는지 아닌지를 알고 있었다. 아무리 연구를 위해서라고 해도 <s>가짜 ECT</s>를 한다는 것이 용이하지 않을 뿐더러 윤리적으로도 문제가 될 수 있기 때문에 위약-대조 연구가 드물었었다. 최초의 이중-맹검 연구가 이루어진 것은 2017년에 이르러서였다.[@RN314] 이 연구에서는 클로자핀에 부분 반응만을 보이는 환자를 두군으로 나누어, 한군은 진짜 다른 군은 가짜 ECT를 시행하였는데, 아쉽게도 두 군의 호전 정도에 유의한 차이가 발견되지 않았다. 자신이 ECT를 받았다는 암시 효과 자체가 상당한 위약 효과를 낼 가능성이 있기 때문에, ECT의 명확한 효과 여부는 연구할만한 가치가 매우 높은 주제이다.

<aside>

**가짜 ECT (sham ECT)**: 현재 대부분의 현장에서는 전신마취하에 이루어지는 수정된 전기경련 치료를 행한다. 가짜 ECT는 ECT 전극을 대고 전신마취까지 하지만 정작 전류를 흘리지 않는 식으로 진행된다.

</aside>

### 5-2-2. 유지 ECT의 필요성

ECT의 급성기 효과는 탁월하지만 이로 인한 호전은 일시적일 뿐이며, 치료 세션이 끝나면 멀지 않아 정신병적 증상이 되돌아온다.[@RN307] ECT 중단 후 1년간 재발율이 42.7\~63.6%에 달하며 이중 대부분은 ECT 중단 후 6개월 이내에 재발한다.[@RN308][@RN309] ECT 치료가 끝나도 항정신병 약물은 그대로 유지한다는 것을 고려하면, 이렇게 재발율이 높다는 것은 문제가 아닐 수 없다. 따라서 급성기 ECT가 끝난 이후에도 정기적으로 유지 ECT를 진행하는 것이 권장된다.[@RN310][@RN311]

항정신병 약물을 유지하면서 정기적으로 ECT를 시행하면, 약물치료만 했을 때보다 재발을 방지하고 인지기능을 호전시키는데 효과적이다.[@RN309] 그러나 언제까지, 어떤 빈도로 유지 ECT를 병행해야 하는 지에 대해선 자료가 부족하다. 클로자핀 저항성 조현병 환자에게 유지 ECT를 최대 24주까지 시행한 무작위 연구에서는, 유지 기간 동안 증상이나 부작용의 급격한 변화는 관찰되지 않았다.[@RN315]

객관적 근거자료가 있는 것은 아니지만 치료저항성 조현병 환자에게 유지 ECT를 시행할 때는, 처음에는 매주 1회 시행하다가 점차 2주 내지 한달 간격으로 시행한다.[@RN309] 양성 증상과 사고 장애가 심할 때는 1\~2주 간격으로, 기분 증상이나 음성 증상이 주된 증상일 때는 3-4주 간격으로 할 수 있다.[@RN317] 유지 ECT의 간격이 길어지면, ECT로 인해 일시적으로 <s>저하된 인지기능</s>이 회복될 수 있는 시간적 여유를 확보할 수 있지만, 그만큼 재발의 위험에 노출되게 된다.[@RN318] 따라서 어떤 간격으로 유지 ECT를 해야할 지는, 인지저하의 정도나 재발 시 증상의 심각성 등 다양한 요소를 고려하여 결정해야 한다.

<aside>

**전기경련 치료의 인지저하 부작용**: 전기경련 후 올 수 있는 인지저하는 1) 비기억력 장애, 2) 전향적 기억상실, 3) 후향적 기억상실로 나눌 수 있다. 치료를 받은 후 3일 내에 집행 기능 및 정보처리 속도의 저하가 현저하게 나타나지만 3일이 지나서 지속하는 경우는 거의 없다. 마찬가지로 3일 내에 전향적 기억장애가 나타날 수 있지만, 2주가 지나면 거의 완전히 정상화된다. 문제가 되는 것은 후향적 기억상실이다. 전기경련 치료를 받기 전에 있었던 일에 대한 기억을 잃어버리는데, 심하면 1년이 지나도 회복하지 못한다. 이러한 인지손상은 전극을 붙이는 위치, 전류의 강도, 빈도 등에 따라 좌우될 수 있다.

</aside>

클로자핀과 유지 ECT 병용에 대한 자료는 드물고 이중맹검 임상시험 결과는 아예 없다. 후향적 관찰연구가 하나 있는데, 여기 포함된 환자들은 2.5주 간격으로 평균 91회 ECT를 받았으며, CGI 점수 상 유의한 호전이 연구 기간 동안 유지되었다.[@RN318] Moeller 등[@RN319]이 보고한 증례에서는, 치료저항성 조현병 환자가 1년간 24회의 ECT를 시행받고 증상이 유의하게 감소되었을 뿐 아니라, 이후에는 약물치료만으로도 안정상태를 유지할 수 있었다. 또한 유지 ECT를 병행하였을 때 입원율이 낮아졌다는 보고도 있다.[@RN320]

한편 클로자핀에 저항성을 보이는 환자가 유지 ECT에 의한 효과를 보기까지 상당한 시간이 필요할 수 있다. 정인원 등이 보고한 증례에서는, 클로자핀 투여에도 불구하고 자살사고와 우울을 부추기는 만성적인 환청이 두드러졌던 30대 여성 조현병 환자에서 3년간 91회의 ECT를 시행하였더니 극적으로 환청 등이 호전되었으며, 이후 클로자핀 용량을 일일 200mg으로 낮춘 후에도 재발없이 안정상태를 유지하였다.[@Chung2021]

### 5-2-4. ECT 시행의 실제

ECT는 급성 강직증이나 신경이완제 악성증후군 등, 항정신병 약물이 불필요하거나 사용할 수 없는 경우에는 단독 요법으로 사용된다. 그러나 치료저항성 만성 환자에게는 대부분 기존의 항정신병 약물을 그대로 유지하거나 약간 용량을 낮춘 채 시행된다. 클로자핀은 경련 역치를 낮추기 때문에, 클로자핀 투여 환자에게 ECT를 시행하면 경련이 지나치게 오래 지속될까봐 우려하기도 한다. 그러나 실제로 그런 경우는 드문 편이며, 굳이 클로자핀의 용량을 줄이지 않고서도 ECT를 시행할 수 있다. Lally 등[@RN122]이 조사한 체계적 문헌검토에 따르면 조사된 166명의 사례 중 오래 지속된 경련은 5명에서 나타났으며, 또 다른 조사에서도 208명의 사례 중 4건 뿐이었다.[@Grover2015] 조현병 특히 치료저항성 환자에게 ECT를 할 때는 우울증 환자에게 ECT를 할 때보다 좀더 과감한 치료가 필요하다. 따라서 단극성 보다는 양극성을 사용하며, 시술 회수도 우울증때 보다 더 많아야 한다.

<aside>

항정신병 약물 즉 도파민 수용체 길항제는 대체로 전기경련 치료에서 경련 역치를 높인다.[@Chi2017] 비정형 약물도 예외는 아니어서 대표적인 예로 아리프프라졸은 항경련 효과를 나타낸다. 이와는 대조적으로 다수용체 길항제인 클로르프로마진과 클로자핀은 고용량에서 경련 역치를 낮추기 때문에, 보통 ECT를 할 때 클로자핀 용량을 다소 낮출 것을 권장한다.

</aside>

치료저항성 환자가 아닐 지라도 조현병에서 ECT는 대체로 주 2-3회 시행되며, 총 투여 횟수는 10회 내외가 된다. 시행 회수를 미리 결정하고 시작하는 것이 아니라 매번 치료 후에 환자를 다시 평가하여 치료를 더 할지말지를 결정하곤 한다. 한번 시술 후에 극적인 증상의 변화가 관찰되는 경우도 있지만, 환자의 호전 정도를 주의 깊게 관찰할 수 있는 표준화된 도구(BPRS, PANSS)등이 준비되어 있지 않으면 치료 성과를 판단하기 어려울 수 있다. 미리 정해둔 치료 목표에 도달하면 바로 중단할 수도 있지만 보통은 1-2회 더 시술하는 것이 일반적이다. ECT 시행에 대한 일반적 원칙이나, 주의할 점, 이전 복용 약물을 어떻게 해야할 것인지에 대한 자세한 설명은 김용식 등[@2019-og]을 참조하기 바란다.

### 5-2-5. ECT를 위한 하드웨어 및 소프트웨어, 법적 규정

ECT는 고도의 전문적 치료로, 우리나라에서는 정신과 치료기관중 극히 일부에서만 시행하고 있다. 안정성과 유용성에 비해 실제로는 널리 사용되지 못하고 있는데, 이는 일반인 뿐 아니라 의료진 역시 ECT를 낯설고 부담스러워하며, 전문적인 시설과 장비 및 인력이 필요하다는 점이 장벽으로 작용한다. 또한 투여하는 자원에 비해 충분한 건강보험 수가를 받지 못하고 있으므로, ECT 건수가 무척 많지 않은 한 장비와 인력을 따로 투자하기 힘들다.

ECT를 위해서는 시술하는 정신과 의사 및 마취과 의사, 시술 보조자 등 최소 3인의 시술자가 필요하고, 수술 회복실 담당 경험이 있는 간호인력도 필요하다. ECT 시술하는 정신과 의사는 기계 조작법, 자극 투여법, 환자 모니터링, 경련이 실패했을 때의 전략, 부작용 또는 위험한 상황에 대한 대책 등을 잘 알고 있어야 하므로 전문적 교육이 필요하다. 시설 측면에서는 산소가 공급되며 안정된 시술을 할 수 있는 처치실, 회복실 등이 최소한 필요한 공간이다. 이런 기초적인 자원이 확보된 뒤에도 ECT 장비 및 다양한 부속장비, 마취 장비 등이 필요하다. 한편, 법적으로 ECT는 특수치료에 속하므로 환자의 동의서가 필요할 뿐만 아니라 병원내 위원회를 통해 5인 이상 전문가의 동의를 얻어야 한다.

## 5-3. 반복적 경두개 자기자극

반복적 경두개 전기자극(rTMS)이란 환자의 두부에 자기 코일을 가까이 위치시킨 후, 여기에 전류를 흘려보내면 강력한 자장이 형성되는 원리를 이용한다. 시간에 따라 변화하는 강력한 자장이 걸리면 대뇌의 신경세포에는 <s>다시 전기 신호가 형성</s>되며, 이는 세포를 흥분시키기도 억제시키기도 한다. 뇌에 전기자극이 가해진다는 면에서 전기경련 치료(ECT)와 유사하나, 근본적으로 비침습적이며, 순간적으로 강력한 전류가 흐르는 ECT와는 달리 상대적으로 약한 전류가 반복적으로 흐르게 된다는 점에서 차이가 난다. 개발 초기에는 신경학적 질환에 널리 사용되었으나, 점차 적응증을 확장하여 공황 장애, 강박 장애, 우울증 등에 효과를 보였으며, 조현병에도 조금씩 시도되고 있다.

<aside>

ECT는 직접 전류를 흘려보내는 방식을 취하는데 비해, rTMS에서는 1) 전류를 자장으로 바꾸고, 2) 자장이 뇌세포 내에서 다시 전류로 바뀌는 방식을 취한다. 따라서 전극을 직접 머리에 대지 않고도 전류의 흐름을 만들어낼 수 있다는 장점이 있는데, 역으로 발생되는 전류의 흐름을 통제할 수도, 측정할 수도 없다는 단점이 있다.

</aside>

조현병 환자에서도 항정신병 약물로 충분한 효과를 보지 못하는 경우 시험적으로 시도되어 왔다. 20여년전 Hoffman 등[@Hoffman1999]이 TMS를 청각피질에 시행함으로써 환청 증상을 억제할 수 있었다고 보고한 이후 지금까지 rTMS 연구는 주로 약물로 잘 잡히지 않는 환청에 집중되어 왔다.[@RN332][@RN330] Kennedy 등[@Kennedy2018]이 행한 메타 분석에서 rTMS는 환청을 줄이는데 우수한 효과를 보였으며, 음성증상에도 긍정적인 효과를 나타내었다. 반면 동일한 연구에서 양성 증상에는 별 도움이 되지 않았을 뿐더러 오히려 악화되는 경향을 보였다. 적지 않은 긍정적 연구결과에도 불구하고 여전히 효과 여부는 논쟁 중에 있으며, 자극의 강도나 빈도, 지속 시간 등이 연구마다 천차만별이라 통일된 치료 프로토콜이 만들어지려면 아직도 한참을 기다려야 할 듯 하다.[@Marzouk2020]

최근 독일 연구진은 주로 음성 증상을 보이는 조현병 환자 175명을 대상으로 진짜와 가짜 rTMS를 이용하여 이중 맹검 임상 시험을 진행하였다.[@Wobrock2015] "rTMS for the Treatment of Negative Symptoms in Schizophrenia (RESIS) trial"이라고 이름 붙여진 이 연구는 흔하지 않은 대규모 연구였지만, 안타깝게도 두 군간의 음성/인지 증상 호전의 차이를 발견하지 못하였다. 그러나 이중 클로자핀 치료저항성을 보였던 26명의 환자 자료만 따로 떼어 분석한 결과에 따르면, 비록 음성/인지 증상에서는 호전이 없었지만, 오히려 양성/일반 증상에서는 대조군에 비해 유의하게 우수한 효과를 보였다.[@Wagner2019a]

ECT와는 달리 rTMS의 자극이 전달되는 부위는 비교적 국한된 영역이므로, 환자의 증상 패턴이나 기능적 영상학 소견에 따라 치료를 행하는 위치를 달리할 수 있다. 애초에 Hoffman 등[@Hoffman1999]이 좌측 측두엽에 TMS를 시행한 것은 이곳이 수용성 언어중추이며, 환청이 들릴 때 좌측 측두두정엽이 활성화된다는 것이 PET 연구를 통해 밝혀져 있었기 때문이다.[@RN329] 마찬가지로 RESIS 임상 시험에서는 음성/인지 증상을 호전시키기 위해 좌측 배외측 전전두엽에 자극을 가하였다. rTMS를 시행하면 해당되는 부위의 혈류가 증가 혹은 감소된다는 것을 fMRI를 통해 확인할 수 있으며[@RN331], 치료 전 측두엽으로의 혈류 정도를 이용하여 rTMS의 효과를 예측할 수 있다고도 한다.[@Hoffman1999]

종합하면 rTMS는 비침습적이고 환자에게 심리적 트라우마를 남기지 않는다는 면에서 ECT의 강력한 대안으로 제시되었으나, ECT와 달리 효과가 명백하게 확인되지 않았다. 일반 조현병 환자에서의 효과도 확실하지 않은 상태에서 치료저항성, 게다가 클로자핀 저항성 환자에 대한 효과를 논한다는 것은 지나치게 성급한 듯 싶다.[@Marzouk2020] Siskind 등[@Siskind2019]이 집계한 바에 따르면 2019년까지 클로자핀 치료저항성 환자에게 rTMS를 시도한 연구는 세개로 총 54명에게 시도되었다. 그러나 이 자료만 갖고는 가짜 rTMS에 비해 우수한 효과를 보인다는 증거는 찾을 수 없었다.

## 

## 5-4. 뇌심부 자극술

뇌심부 자극술(DBS)은 양쪽 대뇌 반구에 신경외과적 시술을 통해 전극을 이식하고, 이를 통해 전기 자극을 보내는 방법이다. 뇌의 특정 부위에 전기자극을 일정한 주파수와 일정한 전압으로 반복적으로 보낼 수 있으며, 이를 통해 교란된 신경 네트워크가 다시 균형을 찾아갈 수 있도록 돕는다. 원래는 약물 치료에 반응하지 않는 진전이나, 피킨슨 병, 근긴장 이상증, 만성 통증 등에 시도되었으며, 2009년 강박증의 치료로 허가를 받은 이후에는 다양한 정신질환에도 시도되고 있다.

워낙 침습적이고 실험적인 치료라 조현병 환자에 대한 자료는 매우 드물다. 현재까지 측좌핵(nucleus accumbens)을 자극한 두 개의 증례보고가 있을 뿐이다. 한 증례에서는 편측 자극을 통해 강박 증상과 정신 사회적 기능은 호전되었지만 음성 증상에는 변화가 없었다.[@RN342] 또 다른 증례에서는 편측 자극에서 양성과 음성 증상 모두에서 감소를 보였으나, 양측 자극을 주었더니 좌불안석이 나타났다고 하였다.(Corripio, Sarro et al. 2016) 가장 최근에는 클로자핀에 치료 저항성을 보이던 7명의 환자를 대상으로 측좌핵 혹은 전측 대상회에 전극을 심었던 사례가 보고되었는데, 그 중 4명에서 극적인 효과를 보였다. 더욱 흥미로운 것은 정기적으로 전기 자극을 주는 것을 멈췄더니 거의 즉시 증상이 재발하였다는 점이다.[@Corripio2020]

DBS는 일부 환자에서는 극적인 효과를 보이고 있지만 여전히 치료 프로토콜이 확립되지 않았으며, 수술의 부작용 혹은 기계적 오작동의 위험을 항시 품고 있다. 애초에 신경학적 질환으로 DBS를 시행했던 환자들 중에서는 심각한 정신의학적 부작용을 일으켜 치료를 중단해야 했던 사례들이 적지 않았다.[@Mosley2015]
