---
title: "2장 3절: 신경발달학적 가설"
description: Neurodevelopmental Hypothesis of Schizophrenia
bibliography: references/02-03.bib
link-citation: yes
---

<a href="article-02-02.html"><i class="arrow far fa-arrow-alt-circle-left"></i></a>

<a href="article-02-04.html"><i class="arrow far fa-arrow-alt-circle-right"></i></a>

## 3-1. 신경발달학적 가설의 탄생 {#neurodevelopment-birth}

만약 조현병의 발병 위험을 높이는데 특정 유전자가 관여한다면, 변이가 발생한 유전자가 어떤 방식으로 질병에 취약하게 만드는지 의문이 생기지 않을 수 없다. 일반적으로 변이된 유전자가 일으킬 수 있는 효과를 다음과 같이 나열할 수 있다.

1.  효소의 결핍 및 기능 저하

    a.  필수 물질의 생성 저하
    b.  기질(substrate) 혹은 중간 대사 산물의 축적
    c.  조직 손상 위험이 있는 물질의 비활성화가 이뤄지지 못함

2.  수용체 혹은 세포 내 수송 시스템의 오작동

3.  구조형성 단백질 같은 비효소성 단백질의 결핍 혹은 기능 저하

유전자 변이가 일으키는 효과는 다양하고 광범위하며, 그중 어떤 것도 조현병의 발병 위험을 높일 수 있다. 예를 들어 선천적 대사 장애라고 불리는 유전적 대사이상은 특징적으로 출생 초기부터 다양한 증상을 드러내며, 심지어 생명을 단축시키기도 한다. 한편 헌팅턴 병과 같은 유전 질환은 성인기 후기부터 운동 기능의 이상이 드러나며, 인지기능 저하와 정신증 증상이 동반되기도 한다. 이런 신경질환들은 신경퇴행성 질환(neurodegenerative disorder)이라고 알려져 있다.

반면 조현병의 임상적 특성과 보편적 경과는 이와는 전혀 다르기 때문에, 다른 형태의 병태생리를 고려해야 한다. 잘 알려진 대로 조현병은 후기 청소년기나 초기 청년기에 발병하며, 그 이후에는 악화와 호전을 반복하지만 완치에 이르기는 어렵다. 발병의 위험시기는 생물학적으로나 사회심리학적으로 큰 변화를 거치는 단계이며, 동시에 상당한 스트레스를 받는 시기이다. 청소년기는 신경발달의 마지막 단계를 거치는 시기로, 피질하 영역에서 시작하여 일차 감각운동 영역을 거쳐 마지막에 전전두엽에 이르기까지 대뇌피질이 두꺼워짐과 동시에 가지치기가 일어나 필요없는 연결을 잘라내는 과정이 이루어진다. 이렇듯 뇌의 재구조화가 마무리되는 동시에 성인으로서의 스트레스가 밀어닥치기 시작하는 시기에 발병한다는 것은, 조현병의 발병이 뇌의 신경학적 발달과정과 모종의 관계가 있음을 강력히 시사한다.

소위 조현병의 "2회 충격 가설(two-hit hypothesis)"은 유전적 요인 혹은 환경적 요인으로 인해 발달과정에 있는 태아의 중추신경계에 일차 충격이 가해져 취약성이 높아져 있는 상태에서, 후기 청소년기나 성인기 초기에 두번째 충격이 가해지면 발병에 이르게 된다는 가설이다.[@Maynard2001-yb] 두번째 충격이 어떤 것인지에 대해선 학자마다 의견이 분분하다. 실직, 도시 거주, 이민, 전쟁 등이 조현병 발병 위험을 높이는 것을 보면, 심한 심리사회적 스트레스가 영향을 끼치는 것이 분명해보인다.[@Dean2005-cb] 한편 신경기능을 유지하고, 외적 변화에 적응하며, 장기 강화를 통한 기억과 학습을 담당하는 경로에 문제가 생기는 것이 두번째 충격이라는 생물학적 이론도 언급되고 있다.[@Maynard2001-yb]

이중 첫번째 충격, 즉 태생기 혹은 영아기 초기에 일어나는 충격이 어떤 식으로 조현병에 취약한 상태를 평생동안 지속시키는지에 대한 유력한 가설이 바로 신경발달학적 가설이다. 이 이론은 특히 임신 제 1, 2 삼분기 동안 활발하게 일어나는 신경계의 구조적 발달과정의 문제가, 결함있는 신경연결망을 만들어내고, 이러한 결함이 아이가 성장하였을 때 겪게되는 환경적 변화에 유연하게 대처하는 능력을 훼손시키기 때문이라고 주장한다.[@Owen2011-rn]

정신증의 신경발달학적 이론이 최초로 제안된 것은 1891년 스코틀랜드의 정신과 의사인 <s>Clouston</s>에 의해서였다. 그러나 크레펠린이 조발성 치매 개념을 대중화시키면서, 조현병은 신경퇴행성 질환이라는 인식이 강해졌다. 1970년대 말초에 접어들면서 조현병의 뇌영상 연구가 첫걸음을 떼기 시작할 무렵, Johnstone 등[@Johnstone1976-hp]**​**은 조현병 환자의 뇌실이 정상인에 비해 유의하게 커져있음을 보고하였다. 1982년에는 일란성 쌍생아에 있어서, 조현병에 이환된 환자의 뇌실은 그렇지 않은 형제의 뇌실보다 크다는 것이 발견되었다.[@Reveley1982-tm] 겨울에 출생한 집단에서 조현병 발병률이 높았다던지, 2차 대전 중 기근으로 말미암아 산모가 영양실조 상태에 놓였을 때 출생한 자녀에서 조현병을 비롯한 조현병 스펙트럼 장애의 빈도가 높았다는 역학적 연구결과도 신경발달과정에 주목하게 된 요인이었다.[@Dalen1968-br][@Hoek1998-gh]

<aside>

**Thomas Clouston (1840\~1915)**: 스코틀랜드의 정신과 의사. 왕립 에딘버러 수용소 소장을 역임하였으며, 에딘버러 대학에서 정신의학을 강의하였다. 청소년 정신의학에 관심이 많았으며, 강박적인 자위가 정신질환을 일으킨다고 믿었다.

</aside>

1987년 <s>Weinberger</s>는 처음으로 신경발달학적 가설을 공식화하였다. 그는 발병하기 전의 조현병 환자의 뇌에서 이미 비특이적인 신경병리학적 소견이 발견되기 때문에, 먼 원인은 이미 태생기 초기에 자리잡았을 것이라 생각하였다. 그럼에도 불구하고 수년 이상 발병하지 않고 있다가 나이가 들어서 발병하는 원인은 이러한 신경병리학적 병변이 정상적인 신경계의 성숙과정과 상호작용을 일으키면서 점차 표면적인 증상이 드러나게 하는 것이라 가정하였다.[@Weinberger1987-ar]

<aside>

**Daniel Weinberger (1947\~)**: 미국의 정신과 의사로 존스 홉킨스 대학 교수로 재직중이다. 조현병을 비롯한 다양한 정신질환의 유전 요인을 찾는데 업적을 남겼으며, COMT 및 NRG-1 유전자와 조현병의 연관관계를 찾아내었다.

</aside>

## 3-2. 신경발달학적 가설의 증거 (#neurodevelopment-evidence)

이후 점차 신경발달학적 이상을 뒷받침하는 증거들이 축적되기 시작하였다. 저체중, 저산소증 등 산과적 합병증, 인플루엔자나 풍진(rubella), 톡소플라즈모시스(toxoplasmosis)와 같은 바이러스 감염 등은 뇌의 구조적 이상을 가져올 뿐더러, 조현병 발병 위험을 높인다.[@Mednick1988-mm][@Brown2000-ga] 또한 조현병 환자의 뇌에서 뇌실의 확장 외에도, 이소성 회백질(ectopic gray matter), 뇌고량(cerebral sulcus)의 깊이나 모양의 차이, 해마 등 부위에서 발견되는 세포구축(cytoarchitecture)의 이상, 축삭돌기나 수상돌기의 분지 패턴 이상 등이 발견되었으며, 이들은 모두 중추신경계의 발달학적 이상과 구조적 결함을 입증하였다.[@Arnold1999-fr] 중추신경계가 발달하는 일련의 과정에는, 뇌실하 영역(subventricular zone)에서 처음 생성되는 신경세포들이 점차 바깥쪽으로 이동하면서 특징적인 6층 구조를 이루는 기전을 비롯하여, 축삭이 자라나면서 신경성장인자(neurotrophic factor)의 안내를 받아 정해진 신경세포를 찾아가는 과정, 그렇게 만난 축삭과 수상돌기가 시냅스를 이루는 과정 등이 포함된다. 신경발달과정의 이상은 그 어느 단계에서도 발생할 수 있다.

신경발달학적 가설을 지지하는 다양한 동물모델도 개발되었다. 갓 태어난 생쥐에게 phencyclidine (PCP)을 투여하면 정신증 유사증세를 보이며, 이들에게 항정신병 약물을 투여하면 증세가 없어진다.[@Broberg2009-jm] Methylazoxymethanol acetate라는 세포분열 억제제를 임신 중인 쥐에게 투여하면, 태어난 쥐가 정신증 증세를 보일 뿐더러, 조현병 환자에게서 보이는 중추신경계의 구조적 이상을 동반한다.[@Grace2017-cb]

만약 신경발달학적 가설이 맞다면, 아직 발병하지 않은 전구기 환자들도 신경연결망의 이상을 지니고 있다는 뜻이 된다. 코호트 연구를 통해 나중에 조현병이 발생한 환자들의 병전 상태를 재조사한다든지, 유전적 위험인자를 지닌 환자의 형제, 자식 등에게서 어떤 구조적, 기능적 변화가 있는 지를 연구하면 좀더 통찰을 얻을 수 있을 것이다. <s>MRC 코호트 연구</s>나 <s>Dunedin 종적 연구</s>를 통하여 조현병 환자들은 발병 전에 이미 다양한 신경운동기능, 언어발달, 사회적 부적응, 성적 저하 등을 보인다는 사실이 관찰되었다.[@Jones1994-kf[@Poulton2000-nk]

<aside>

**MRC 코호트 연구 (Medical Research Council National Survey of Health and Development Cohort)**: 2차 대전 직후인 1946년 영국에서 태어난 5,362명에 대해 이후 성장과정을 50년 이상 추적하는 프로젝트이다. (<http://www.nshd.mrc.ac.uk/>)

**Dunedin 종적 연구( Dunedin Longitudinal Study)**: 뉴질랜드에서 행해진 코호트 연구이다. Dunedin에 위치한 메리 여왕 산모센터(Queen Mary Maternity Center)라는 곳에서 1972년부터 1973년 사이에 태어난 1,037명을 추적하며 현재 44세 시점의 평가가 완료되었다.

</aside>

Weinberger 등이 상정한 신경발달학적 가설은 모종의 원인에 의해 태생기 초기에 이미 신경연결망 이상이 자리잡고, 이러한 이상이 정상 발달과정을 방해하거나 맞물리면서 증상이 발현된다는 것이었다. 그러나 신경발달 과정은 반드시 태생기에만 국한된 것이 아니다. 시냅스 가지치기(synaptic pruning)는 잘 쓰지 않는 시냅스를 제거함으로써, 신경연결망 간의 상호 조절 효율성을 높이거나, 에너지 소모를 줄이는 과정으로 후기 청소년기나 성인기 초기까지 진행된다. 가지치기는 발달과정에서 부적절하게 연결된 원거리 시냅스를 제거하는 거시적 가지치기와, 자주 사용되는 연결만을 남기고 그다지 사용되지 않는 불필요한 연결을 소거하는 미시적 가지치기로 나뉜다.[@Vanderhaeghen2010-wz] Keshavan 등[@Keshavan1994-hy]은 조현병을 일으키는 신경발달학적 이상은 이 가지치기에 있을 것이라 주장하였다. 일부 학자들은 complement component 4 (C4) 유전자에 위치한 <s>유전자 복제수 변이</s>가 조현병과 상당한 유전적 연관성을 보이는 것에 주목한다. C4는 출생 후 가지치기에 깊숙히 관련되어 있기 때문에, 시냅스 가지치기는 새삼스레 조현병 발병기전에 있어 그 중요성이 부각되었다. 최근 한 연구에서는 조현병 환자에서 추출한 단핵구로부터 신경교세포 유사 세포를 유도한 다음, 이들이 <s>시냅토솜</s>을 파괴하는 정도를 측정하였는데, 그 정도가 대조군에 비해 유의하게 높음을 발견하였다. 시냅토솜 파괴는 가지치기가 행해지는 주요 기전이기 때문에 시냅스 가지치기가 얼마나 활발히 이루어지냐를 반영하는 지표가 된다.[@Sellgren2017-ty]

<aside>

**유전자 복제수 변이 (copy number variation)**: 생식세포가 만들어 지는 신생합성(de novo synthesis) 과정에서 유전자의 결실, 중복, 전좌, 역위 등 복제 상의 실수로 말미암아, 유전자가 결실 되거나 하나 이상이 반복될 수 있다. 상대적으로 짧은 염기서열이 반복되는 STR, VNTR과 달리 30\~500kb에 이르는 전체 유전자가 반복된다. 이때 반복되는 갯수가 개인에 따라 다른 것을 유전자 복제수 변이라고 한다.

**시냅토솜(synaptosome)**: 신경 말단을 형성하는 것으로 여겨지는 구조물로 신경세포에서 분리되어 고립된 상태로 존재한다.

</aside>

## 3-3. 신경발달학적 가설의 이론적 난점과 한계

조현병 환자에게서 발병 전에 이미 다양한 신경계 이상이 발견되고, 이들 중 다수가 비정상적인 신경발달과정을 반영한다는 사실은 이제 이론의 여지없이 받아들여지고 있다. 그러나 여전히 풀리지 않은 문제는 이러한 발달학적 이상이 어떻게 발병에 이르게 하느냐는 것이다. 발달이상에 의해 신경연결망에 문제가 생겼다고 해도, 발병 전까지 그 영향이 그다지 드러나지 않는 것으로 보아 이러한 이상은 매우 미세하고 은근한 것이다. 따라서 신경연결망 이상이 직접 조현병을 일으킨다기 보다는, 취약성을 조금 증가시키는 정도로 이해하는 것이 바람직할 것이다. 2회 충격 가설에서 의미하는 두번째 충격은 보통 심리사회적 스트레스를 말한다. 그렇다면 신경발달학적 가설은, 신경연결망 이상이 개체가 다양한 스트레스에 대응하는 과정에 어떤 악영향을 미치는 것인지 설명할 수 있어야 한다.

한가지 힌트는 발달과정의 이상과 도파민 시스템의 연관성이다. Kanyuch와 Anderson은 동물모델에서 초기 신경발달의 이상은 청소년 시기에 도파민 시스템이 스트레스에 과도하게 반응하도록 만든다고 보고하였다.[@Kanyuch2017-nz] 선조체 도파민 시스템의 과도한 반응은 중립적 자극에 대해 부적절한 의미나 과도한 중요성을 부여하는 비정상적 현저성([2장 6-4절 참조](article-02-06.html#aberrant-salience))을 일으킨다.[@Kapur2003-xc] 잘 알려진 바와 같이 비정상적 현저성은 관계사고나 편집사고의 기반이 된다.[@Mishara2013-mc]

그러나 신경발달과정의 이상을 도파민 시스템과의 연관으로 이해하고자 해도, 신경연결망의 이상이 약하는 것은 민감성이나 편집적 경향이지 조현병 자체가 아니다. 이러한 경향은 인구집단 내에서 연속적으로 분포하며, 정상과 질병을 나누는 분명한 기준도 없다. 이는 신경발달과정과 가장 밀접한 연관이 있을 것으로 여겨지는 인지기능의 경우에도 역시 마찬가지이다. 이에 덧붙여, 편집적 경향이나 신경인지기능의 저하가 점진적으로 드러난다 하더라도, 그것이 반드시 조현병으로 발전하리라는 필연성은 없다. 조현 스펙트럼 장애를 비롯하여 양극성 장애, 우울증, 반사회성 인격 등 다양한 질환으로 발전할 수 있다. 따라서 신경발달학적 이상의 진단특이성은 확립되지 않았다고 할 수 있다.[@Murray2017-gx]

이상에서 보듯 조현병의 신경발달학적 가설은 몇가지 해결되지 않는 문제를 지니고 있다. 그럼에도 불구하고 이를 뒷받침하는 든든한 증거체계를 갖추고 있으며, 조현병의 특징적인 경과를 설득력있게 설명해준다. 비록 이론의 초창기에는 출생전에 이미 완료되어버린 발달 이상이 평생동안 조현병 발병 위험을 높이는 것처럼 받아들여지기도 했지만, 고위 인지기능을 관장하는 신경계의 발달은 평생토록 지속된다는 것을 감안할 때, 이 이론은 좀더 확장되어야 할 필요성이 있다.[@Andreasen2010-gc]
